PM Indiya don halartar barkewar haikali a wurin da aka yi jayayya
NEW DELHI (AP) - Firayim Ministan Indiya Narendra Modi zai halarci bikin baje koli a wata mai zuwa ga wani gidan ibada na Hindu a wani wurin da ake fama da rigingimu a arewacin Indiya inda 'yan addinin Hindu suka rushe wani masallaci na karni na 16 a shekarar 1992, a cewar amintaccen da ke kula da ginin haikalin.
An shirya bikin ne a ranar 5 ga watan Augusta, masu shirya kwanan wata sun ce taurari ne mai albarka ga Hindus, amma kuma hakan ya nuna shekara guda tun lokacin da majalisar dokokin Indiya ta kwace matsayinta na mafi yawan musulmi, Jammu da Kashmir.
Wannan alama ba za ta yiwu ba ga magoya baya da kuma abokan adawar jam'iyyar Bharatiya Janata ta Hindu ta Modi, ko kuma BJP, wacce ta yi shekaru da yawa ta hada da alkawarin da ta yi na rage cin gashin kan Kashmir da kuma gina haikali ga allahn Hindu Ram inda masallacin Mughal ya taɓa tsayawa, wani wurin da ke birnin Ayodhya a jihar Uttar Pradesh wanda masu ibada suka yi imanin cewa shi ne wurin haihuwar Ram.
Saboda har yanzu cutar coronavirus na ci gaba da yaduwa a duk fadin Indiya, wacce ta ba da rahoton kashi na uku mafi girma a duniya, za a watsa bikin a gidan talabijin na jihohi kai tsaye kuma za a iyakance adadin mahalarta taron da masu kallo, a cewar Vishwa Hindu Parishad, ko kuma Kungiyar Hindu ta Duniya, wata kungiyar 'yan kishin Hindu da ke kawance da BJP.
Haikalin zai zama " cibiyar dawwama da rashin mutuwa na jituwar jama'a, hadin kan kasa da haɗin kai da kuma farkawa da jin daɗin rayuwar Hindutva" ko kuma hanyar rayuwar Hindu, in ji kakakin kungiyar Vinod Bansal a wata sanarwa da ya fitar a ranar Asabar.
An warware takaddama na tsawon karni a kan wurin a shekarar da ta gabata bayan nasarar da jam'iyyar BJP ta samu a zaben.
A watan Nuwamba, Kotun Koli ta yanke hukuncin amincewa da amintaccen haikalin, tana mai cewa za a bai wa musulmi takarda mai fadin eka biyar a wani wuri na daban.
'Yan Hindu masu tsattsauran ra'ayi sun dade suna jayayya da cewa 'yan mamaya Musulmi na Mughal sun gina masallaci a saman wani haikali da aka riga aka yi a tsohuwar birnin Ayodya.
Rikicin da aka yi a watan Disamba na shekarar 1992 bayan rusa masallacin ya haifar da tashin hankali a tsakanin al'umma inda aka kashe kimanin mutane 2,000 galibinsu Musulmi.
A halin yanzu, ana ci gaba da sauraron shari'ar da ake yi a kotun rusau a wata kotu ta musamman.
Wani mai gine-gine daga Ahmedabad, Gujarat, jihar Modi, ya gabatar da wani tsari mai tsawo na sandstone mai tsawon kafa 161 (mita 49) da ke da tsaunuka biyar.
Yogi Adityanath, babban ministan Uttar Pradesh kuma wani mabiya addinin Hindu, ya bukaci Ayodhya ta gudanar da bikin tsaftacewa da tsarkakewa na musamman da kuma dukkanin gidajen ibada na birnin don haskaka fitilun man fetur gabanin ziyarar Modi, kamfanin dillancin labarai na Indiya ya ruwaito.
Adityanath ya ce wannan lamari ya kawo karshen "gwagwarmaya ta shekaru 500", in ji PTI.
Barazana ga dimokradiyyar Australiya ta fi kusa da gida fiye da China
Amma jerin matakan da aka dauka a baya-bayan nan a majalisar dokokin Commonwealth suna haifar da damuwa game da mulkin mallaka na gida.
Sun hada da fitar da fasahar gane fuska, tilastawa kamfanonin fasaha su sauya bayanan da ke cikin tsarin kwamfuta na abokan cinikin su, tilastawa kamfanonin fasaha su ba da damar yin amfani da bayanan abokan cinikin su ba tare da sanarwa ga mai mallakar bayanan ba da kuma mika ikon yin tambayoyi na wajibi na ASIO.
Wadannan matakai sun haifar da tambayoyi masu tsanani game da iyakar da ke tsakanin 'yan kasa da gwamnati, amma takardar kudi ta ASIO tana da matukar damuwa.
Ba kamar sauran kasashen Five Eyes ba - Amurka, Kanada, Ingila da New Zealand - a farkon ranar 11 ga watan Satumba, an baiwa ASIO ikon tilastawa mutane tambayoyi har na tsawon kwanaki bakwai dangane da laifin ta'addanci.
Duk da cewa za a iya yarda da cewa matsanancin tashin hankali da ke tattare da laifin ta'addanci yana tabbatar da karfi na ban mamaki - matsanancin tashin hankali a kalla yana ba da iyaka mai haske a kan wadannan karfi na ban mamaki.
Babu shakka ba za a iya fadin hakan ba dangane da ma'anonin da aka yi amfani da su a cikin wannan doka don haifar da karfin tambaya na wajibi: magance bayanan da ke nuna wariya ga "dangantakar siyasa, soja ko tattalin arziki da wata kasa" na Australia; ko kuma ayyuka tare da haɗin gwiwar wani karfi na kasashen waje wanda ke da tsattsauran ra'ayi ko yaudara kuma suna "dakatar da manufofin Australiya".
Yana da wuya a yi tunanin karin "kuka da kuma m "tsaron kasa" dokokin" fiye da wannan.
Za a bar ASIO ta tilasta wa kowa tambaya kan wadannan abubuwa - ba wai kawai ana zargin masu laifi ba.
Wannan ya hada da 'yan jarida, 'yan kasuwa, malaman jami'a da ma'aikata, lauyoyi, 'yan ƙasa, mazauna da baƙi.
ASIO kawai za ta nuna cewa wannan tambaya za ta "na taimakawa wajen tattara bayanai" game da tsangwama daga kasashen waje, wanda da alama ita ce babbar manufa ta lissafin.
Sannan za a iya tambayar mutumin har na tsawon awanni 40 (ba tare da hutu ba).
Idan mutumin ya ki halarta, za a kama su.
Ƙin amsawa ko bayar da amsoshin ƙarya ko na yaudara zai ɗauki hukuncin daurin shekara biyar.
Dokokin da suke da muhimmanci a tsarin shari'armu - hakika tsarin mulki a Amurka ya kiyaye su - wannan doka ta rushe su.
Mutane - ciki har da mutanen da suka riga suka fuskanci tuhuma - za a tilasta su bayar da shaidar da za a iya amfani da ita wajen gurfanar da su.
Za su iya samun lauya a wurin, amma za a tsare lauyan don bayyana tambayoyin da ba a bayyana ba ko kuma ba a bayyana su ba.
Sabuwar dokar ta mayar da hukuncin bayar da garantin tambaya daga alkali zuwa ga Mai Shari'a.
Kamar yadda Sufeto Janar na Harkokin Leken Asiri da Tsaro ya nuna, wannan "ya tashi daga yanayin karuwar bukatun izini na waje a sauran yankuna na Five Eyes."
Har ila yau, ya karya ka'idar rabuwa da iko da kotuna ke bincika ayyukan gwamnatin zartarwa.
Sabuwar dokar ta kuma ba da shawarar fadada karfin tambaya ga yaran da shekarunsu ya kai 14 da haihuwa, sai dai kawai ga wadanda suka shiga ko kuma za su iya yin ayyukan da za su yi illa ga kare Australiya da kuma mutane daga tashin hankali na siyasa.
Ko da hukumomin bincikenmu sun kasance mafi kyau a duniya, ba da ikon tilasta tambayar kowa game da bayanan da "ya nuna wariya ga dangantakar tattalin arziki ta Australia da wata kasa", ko kuma ayyukan da suke "kashewa ga manufofin Australiya" sun wuce fahimta.
Mu tsaya mu kadai.
Babu wata kasa ta Five Eyes da ta wuce zuwa yanzu, ba ma ga laifin ta'addanci ba.
Gaskiya dimokuradiyya mai sassaucin ra'ayi na tsare kan matakan mulki.
Halin da hukumomin tsaronmu suka yi dangane da bugawar majalisar Timor ta Gabas, da shari'ar da aka yi wa Shaidu K da Bernard Collaery, da shari'a a asirce da kuma tsare wani tsohon jami'in tsaro, da dokar bincike na baya-bayan nan da aka zartar a kan 'yan jarida biyu, da kuma tuhumar da ake yi wa daya daga cikinsu dangane da labaran da ake zargin kisan da sojojin Australiya suka yi a Afghanistan ya nuna dalilin da ya sa bai kamata mu rage tsaronmu ba.
Sabunta tafiye-tafiye na Coronavirus: Wadanne Kasashe ne ke da dokar takaita tafiye-tafiye ga 'yan Bulgeriya bayan shiga
Yawan ƙasashen da ke sanya dokar hana tafiye-tafiye na ƙaruwa.
Ya zuwa wannan makon, Jamhuriyar Czech na son gwajin cutar Koronabirus ga ma'aikatan kasar Bulgeriya.
Kasar Denmark ta kyale 'yan Bulgeriya a yankunanta ne kawai idan suna da rajistar adireshi a wurin, ko kwangilar aiki ko kuma takarda da ke tabbatar da tafiyar kasuwanci.
Ya zuwa yau, mutanen da suka ziyarci Bulgaria da Romania a cikin kwanaki 14 da suka gabata suna fuskantar kebewa a Italiya.
A Finland, shigarwa ne kawai don "tabbataccen dalili".
Wajibi ne a killace gida a Austria, duk da gwajin PCR mara kyau.
Tuni dai ake bukatar hakan ga wadanda suka shigo Jamus.
A kwanaki 14 masu zuwa, an hana shiga kudancin Romania ba tare da kyakkyawan dalili ba.
Kuma Girka ta kara tsaurara matakai a kan iyakokin ƙasarta.
Daga ranar Talata, wadanda ke tafiya a jirgin sama daga Bulgeriya zuwa Girka za su gabatar wa hukumomin iyakokin Girka wani mummunan sakamako daga gwajin PCR na cutar Koronabirus, wanda aka yi har zuwa awanni 72 kafin shigarsu makwabciyarmu ta kudu, in ji sanarwar ma'aikatar harkokin wajen kasar.
Sun kara da cewa fasinjojin da ke da takardar shaidar yin irin wannan gwajin ne kadai za a bari a kasar nan.
Dole ne a fitar da shi cikin harshen Turanci kuma ya ƙunshi sunaye da lambobi uku na fasfo ko katin shaida na fasinjojin.
Hukumomi a makwabciyarmu ta kudu ba za su karbi takardun shaidar da ba su cika wadannan bukatun ba
"Ya kamata a gwada matafiya a dakin gwaje-gwaje ta hanyar RT-PCR ta hanyar daukar sakonni daga baki ko hanci."
Za a gane gwajin cutar coronavirus idan an yi su a dakunan gwaje-gwaje na kasa, dakunan gwaje-gwaje na kiwon lafiya na kasa ko dakunan gwaje-gwaje masu zaman kansu waɗanda hukumomin da suka dace da takardun shaida na ƙasa suka amince da su (ba lallai ba ne musamman don COVID-19).
Matakin bai shafi 'yan kasar Girka da 'yan kasar da ke zaune a Girka da kuma matafiya ba saboda muhimman dalilai na sana'a.
Ma'aikatar Harkokin Wajen Girka ta kuma sanar da cewa a ranar Talata 28 ga watan Yuli da Laraba 29 ga watan Yuli, fasinjojin da ba su da lokacin da za a gwada su kafin tafiyarsu, hukumomin Girka da suka cancanta za su gwada su a lokacin da suka isa Girka.
Bukatar da ake bukata ga 'yan kasar da ke tafiya a jirgin sama zuwa Girka da su cika akalla sa'o'i 24 kafin a cika wani nau'in fasinjoji na lantarki (PLF) wanda ke samar da lambar QR, wanda suke gabatarwa ga hukumomin Girka a lokacin da suka shiga kasar, ya kasance yana da karfi.
An wallafa ƙarin bayani a kan travel.gov.gr
A halin yanzu babu wani sauyi a bukatun tsallaka iyakokin ƙasar tsakanin Bulgeriya da Girka.
"Masu tafiya zuwa Girka a kan iyakar ƙasar, ba tare da la'akari da 'yan ƙasa ba, dole ne su cika wani nau'i na fasinjoji na lantarki (PLF) wanda ke samar da lambar QR aƙalla awanni 24 kafin isowa", ma'aikatar harkokin waje ta bayyana.
Rufe wuraren binciken Ilinden, Kapitan Petko Voyvoda da Makaza ya kara yawan zirga-zirga a kan iyakar kusa da Petrich.
Babu wata matsala game da sauyin.
Babu jerin gwano na manyan motoci.
Duk wadanda ke jiran zuwa teku a Girka.
Matafiya suna jira kimanin awa daya da rabi su tsallaka Hasumiyar.
Uku daga cikin wuraren da ke kan iyakar Bulgeriya da Girka suna aiki.
An rufe "Ilinden - Exohi" da wannan bangare na Ivaylovgrad.
Yi hankali da kayan aikin lambu da ke da kyau sosai
Zai iya zama abin kunya ga masanin kimiyyar tsirrai ya yarda, amma ni cikakken mai shan giyar lambu ne.
Ina son in yi tunanin shi ne saboda ni mai hankali ne ko kuma mai yiwuwa kawai mai kyakkyawan fata, musamman yadda abubuwa da yawa a duniyar shuka sau da yawa suna da matukar damuwa.
Amma ba na jin kunyar cewa na fadi wa da dama daga cikinsu a tsawon rayuwarsa a aikin gona.
Duk da yake na yi imani da darajar gwada abubuwa da kanka, idan ba ka son koyon hanya mai wuya, ga wasu daga cikin kayan lambu da na saba gani.
Da farko, kuma mai yiwuwa mafi munin laifi, ya shuka tumatir-dankali.
An yaba da shi a matsayin nasara ta juyin juya hali, shuke-shuke na tumatir zuwa tushen dankalin turawa, a hakikanin gaskiya, son sani ne na tsohuwar makaranta, wanda ya samo asali ne daga akalla shekarun 1920.
Da yake dukansu sun fito ne daga iyali guda kuma suna da irin wannan "plumbing" na ciki, hakika za ku iya haifar da irin wadannan abubuwan al'ajabi na tiyata.
Amma ga matsalar: samar da gine-gine mai zurfi kamar 'ya'yan itatuwa da tushe yana dauke da makamashi mai yawa na rayuwa, kuma idan tsirrai suna ƙoƙarin yin dukkanin karfin da suke da shi, babu makawa sai su rabu.
Wannan yana nufin amfanin wadannan tsire-tsire da aka shuka suna da ban tsoro kuma babu wani abu kamar abin da kuke gani a hotunan tallace-tallace.
Sannan akwai gaskiyar cewa amfanin gona ya yi girma da adadi daban-daban, don haka sai a girbe tsiron sai ka kashe tsirrai kafin tumatir ya nunka.
A kan batun hotunan tallace-tallace na tallace-tallace, akwai ma'amala mai yawa a nan.
Na ga wardi Photoshopped sama blue da 'ya'yan itatuwa da physiologically ba zai yiwu adadin 'ya'yan itace a kan rassan a wasu manyan littattafai.
Har na ga hotuna sun "bashi" daga asusun na na Instagram kuma suna amfani da su ta hanyar sadarwar kasuwanci a matsayin hotunan wuraren gwajin su.
Abin baƙin ciki shi ne aikin ƙananan 'yan tsirarun kamfanoni masu rauni yana nufin dole ne ku kalli hotunan tallace-tallace, musamman a kan layi, tare da ido mai sanyin gwiwa.
Idan ya yi kyau ya zama gaskiya, mai yiwuwa ne.
Da yake magana game da wane, launin shudi yana da wuya a duniyar Botanical, don haka idan ka ga wani sabon shayi mai ban sha'awa, orchid ko cactus, yana haskakawa a cikin mafi tsanani "disinfectant" inuwa mai launin shudi, kusan hakika an fesa shi ko kuma an mutu.
Wanda zai yi kyau, muddin masu sayarwa sun bayyana hakan, amma da wuya su yi hakan.
Ƙananan ƙwayoyin cuta masu launin shudi za su koma fararen su na asali, amma ba za su iya rayuwa na tsawon lokaci ba.
A ƙarshe, dole ne in yi tutar kaya na bonsai ko kuma, mafi muni, tsaba na bonsai, wanda ya yi alkawarin ƙananan bishiyoyi za su tsiro daga fakitin su.
Bonsai ba nau'in shuka ba ne.
Hanyar horarwa ce da ake amfani da ita wajen ba da illar bishiyoyi na dā a tsaunuka masu nisa.
Kusan koyaushe ana fara su ne daga gine-ginen da suka manyanta waɗanda aka yi amfani da su a baya da kuma sabon girma da aka yi amfani da su a wurin.
Na san zan ci gaba da faduwa don gimmicks, wani bangare ne na jin daɗin gwaji.
Amma waɗannan na gefe kuma za ka iya samun wanda a zahiri yake da damar cika alkawarinsa.
Kotu ta cinna wuta a lokacin zanga-zanga a California
OAKLAND, Ca. - Masu zanga-zanga a California sun cinna wuta a gidan kotu, sun lalata ofishin 'yan sanda da kuma kai hari ga jami'ai bayan zanga-zangar lumana ta kara tsanani a ranar Asabar, in ji 'yan sanda na Oakland.
Masu zanga-zangar sun fasa tagogi, sun fesa fentin rubutu, sun harba kayan wuta da kuma lasisi mai nisa a jami'an, in ji sashen Oakland a Twitter.
Yawancin tweets sun yi kira ga zaman lafiya kuma sun nemi masu shiryawa da su "taimaka mana samar da wurare masu aminci da wurare masu aminci ga masu zanga-zanga."
An fara zanga-zangar ne da yammacin ranar Asabar tare da kungiyoyi irin su "Wall of Moms", kama daga kungiyar da ta kafa a Portland, Oregon, yayin da masu zanga-zangar suka fuskanci suka tare da jami'an Amurka da aka tura zuwa wannan birnin don tsare wani gidan kotun tarayya.
Shugaba Donald Trump ya tura jami'an gwamnatin tarayya domin su matsa kaimi kan zanga-zangar da ta faru cikin dare tun bayan mutuwar George Floyd a Minneapolis a ranar 25 ga watan Mayu.
Zanga-zangar a Oakland ta soma ne cikin lumana, amma ta rikide ta koma tashin hankali har cikin dare.
'Yan sanda sun kaddamar da wani "taro ba bisa ka'ida ba" da misalin karfe 11:30 na yamma kuma jami'ai sun nemi jama'a su tarwatse.
Wutar ta tashi ne a babbar kotun da ke yankin Alameda kuma ba da jimawa ba, kamar yadda kafar yada labarai ta ruwaito.
'Yan sanda sun ce masu zanga-zangar a wani lokaci suna "watse tagogi da kuma kiran wariyar launin fata a mazauna."
Hotunan da sashen ya wallafa sun nuna gilashin da ya fashe da fenti a wani ginin 'yan sanda.
Kasancewar tsaro sosai a wajen ofishin jakadancin Amurka a birnin Chengdu na kasar Sin
An samu matsanancin tsaro a wajen ofishin jakadancin Amurka da ke birnin Chengdu na kasar Sin a ranar Lahadi, yayin da ma'aikatan Amurka suka shirya barin wurin.
An ga manyan motoci uku masu motsi sun shiga cikin fili na ginin, yayin da 'yan sanda masu dauke da kayan kwalliya da kayan kwalliya suka yi layi a dukkanin bangarorin titin, wadanda aka lissafa su da shingayen karfe.
Editan jaridar Global Times na kasar Sin ya bayyana cewa, an bai wa ofishin jakadancin Amurka da ke Chengdu sa'o'i 72 don rufewa, ko kuma har zuwa karfe 10 na safe (0200GMT) a ranar Litinin 27 ga watan Yuli.
China ta tuhumi wasu ma'aikata a ofishin jakadancin Chengdu da cewa "suna gudanar da ayyukan da ba su dace da halayensu ba".
Ba tare da bayar da cikakken bayani ba, mai magana da yawun ma'aikatar harkokin wajen kasar Sin, Wang Wenbin ya ce irin wannan aiki ya tsoma baki cikin harkokin kasar Sin, ya kuma cutar da manufofinta na tsaron kasar.
An bayar da umarnin China na rufe ofishin jakadancin da ke Chengdu a ranar Juma'a don ramuwar gayya kan umarnin Amurka na rufe ofishin jakadancin China a Houston, Texas.
Washington ta umarci China da ta rufe ofishin Houston "don kare ikon mallakar ilmi na Amurka da kuma bayanan sirri na Amurkawa."
Yayin da rufe ofishin jakadancin kasar Sin a Houston ya fara aiki a ranar Juma'a, an ga wasu maza da suka bayyana a matsayin jami'an Amurka sun kutsa kai zuwa wurin ta wata kofa ta baya.
Wang ya ce a ranar Asabar cewa ya sabawa yarjejeniyar kasa da kasa da kuma bangarorin biyu kuma kasar Sin za ta mayar da martani, ba tare da tantance yadda za a yi ba.
Rufe dokar ta-baci ya kara haifar da tashin hankalin da ke tsakanin kasashen biyu kan batutuwa kama daga harkokin kasuwanci da leken asiri na masana'antu zuwa hakkokin bil'adama.
MDD ta ce dubban 'yan gwagwarmayar Pakistan a Afghanistan
ISLAMABAD - Wani rahoto na Amurka ya ce sama da 'yan tawayen Pakistan 6,000 ne ke boye a Afghanistan, mafi yawansu na cikin kungiyar 'yan Taliban da aka haramta a Pakistan da ke da alhakin kai hari kan sojoji da fararen hula na Pakistan.
Rahoton da aka fitar a wannan makon ya ce kungiyar, wacce aka fi sani da Tehreek-e-Taliban (TTP), ta danganta ta da kungiyar 'yan kishin Islama ta Afghanistan.
Wasu daga cikin 'ya'yan kungiyar TTP har sun shiga kungiyar IS wacce ke da hedkwatarta a gabashin Afghanistan.
Gwamnatin Afghanistan ba ta mayar da martani a ranar Lahadi ga buƙatun da Associated Press ta yi don yin sharhi ba.
Rahoton ya ce kungiyar IS a Afghanistan, wacce aka fi sani da IS a lardin Khorasan, ta sha da kyar a hannun jami'an tsaron Afghanistan da sojojin Amurka da na NATO, har ma a wasu lokutan kungiyar Taliban ta Afghanistan.
Kungiyar masu sa ido kan nazari da takunkumi ta Amurka ce ta shirya rahoton, wacce ke bin diddigin kungiyoyin ta'addanci a duniya.
Rahoton ya kiyasta cewa mambobin kungiyar IS a Afghanistan sun kai 2,200, kuma yayin da shugabancinta ya ragu, IS har yanzu tana cikin shugabanninta wani dan kasar Siriya Abu Said Muhammad al-Khorasani.
Rahoton ya kuma ce tawagar masu sa ido sun samu bayanin cewa wasu manyan kwamandojin gwamnatin Musulunci biyu, Abu Qutaibah da Abu Hajar al-Iraqi, sun isa Afghanistan ne kwanan nan daga Gabas ta Tsakiya.
"Duk da cewa a yankin ja da baya, (Islamic State) ya ci gaba da iya kai manyan hare-hare a sassa daban-daban na kasar, ciki har da Kabul.
Hakan na nufin jan hankalin mayakan Taliban da ke adawa da yarjejeniyar da Amurka," in ji rahoton, yana mai nuni da yarjejeniyar zaman lafiya da Amurka ta kulla da Taliban a watan Fabrairu.
An cimma wannan yarjejeniyar ne domin baiwa Amurka damar kawo karshen ayyukanta na shekaru 19 a Afghanistan, kuma ta yi kira ga 'yan Taliban da su ba da tabbacin cewa kungiyoyin 'yan ta'adda ba za su yi amfani da yankinsu ba.
Har ila yau, ana sa ran yarjejeniyar za ta ba da tabbacin sa hannun kungiyar Taliban a yaki da kungiyar IS.
Bangare na biyu kuma mai yiwuwa mafi muhimmanci na yarjejeniyar ya bukaci tattaunawa tsakanin Taliban da shugabancin siyasa na Kabul.
A ranar Asabar da ta gabata, ma'aikatar harkokin wajen Amurka ta fitar da wata sanarwa da ke cewa, wakilin zaman lafiyarta Zalmay Khalilzad ya sake jigila ta yankin yana mai neman tsallakewa a fara tattaunawar, wacce aka dakatar da ita sau da yawa yayin da bangarorin biyu ke jayayya kan shirin sakin fursunoni.
Yarjejeniyar da ke goyon bayan Amurka ta yi kira ga gwamnatin Afghanistan da ta saki fursunonin Taliban 5,000 da kuma 'yan Taliban don 'yantar da ma'aikatan gwamnati da sojoji 1,000 a matsayin abin da ake kira kyakkyawan nufi gabanin tattaunawa.
Har zuwa yanzu gwamnati ta ki sakin fursunoni kusan 600 'yan Taliban da ta kira manyan masu laifi kuma ta yi tayin ba da wasu hanyoyi.
'Yan Taliban sun ki amincewa.
Sanarwar Ma'aikatar Harkokin Wajen Amurka ta ce "jam'iyyun sun fi kusa da fara tattaunawar cikin gida da Afghan, muhimmin mataki na gaba na kawo karshen yakin Afghanistan na tsawon shekaru 40."
"Duk da cewa an samu gagarumin ci gaba kan musayar fursunoni, amma lamarin na bukatar karin kokari domin magancewa sosai."
Mai magana da yawun harkokin siyasa na kungiyar Taliban a farkon makon nan ta ce a shirye ta ke ta gudanar da tattaunawa da shugabannin siyasa na Kabul bayan hutun addinin Musulunci na Eid al-Adha a karshen watan da ya gabata, lamarin da ya sa aka kammala sakin fursunonin.
Babban abin damuwa ga Pakistan shi ne kasancewar 'yan gwagwarmaya a Afghanistan, musamman wadanda ke da nasaba da TTP ko Jamaat-ul-Ahrar ko Lashkar-e-Islam, da kuma wadanda ke tare da sojojin 'yanci na Baluchistan, wadanda suka dauki alhakin kai manyan hare-hare a wannan watan a kudancin lardin Sindh da kuma kudu maso yammacin lardin Baluchistan.
An kashe sojojin Pakistan da dama a wannan watan a kudu maso yammacin lardin Baluchistan a yaki da 'yan tawayen.
Kungiyar TTP ta dauki alhakin kai daya daga cikin mummunan harin da aka kai a Pakistan a shekarar 2014, lokacin da aka kaiwa wata makarantar sojojin Pakistan hari sannan aka kashe mutane 140.
Yawancin dalibai ne, wasu kuma matasa ne 5.
"An kiyasta adadin mayakan ta'addanci na kasashen waje na Pakistan a Afghanistan, wanda ke zama barazana ga kasashen biyu, a tsakanin 6,000 zuwa 6,500, yawancinsu suna da TTP," in ji rahoton.
Babban bankin Birtaniya HSBC ya musanta "kafa tarko" ga kamfanin Huawei na kasar Sin a binciken Amurka - RT Labaran Kasuwanci
Babban bankin kasa da kasa mai hedkwata a birnin London HSBC ya kai dauki ga kafofin watsa labarun cewa ba haka ba ne, kamar yadda kafofin watsa labaran kasar Sin suka yi ikirarin cewa, "kera hujjoji" a kan Huawei, wanda ya kai ga kama babban jami'in kudi na kamfanin a Kanada.
A wani sako da ya wallafa a shafinsa na WeChat, mai ba da lamuni ya ce ayyukanta ba su haifar da binciken da Amurka ta yi kan babbar mai sayar da kayayyakin sadarwa na sadarwa a duniya ba, yayin da binciken da kamfanin Huawei ya yi kan zargin keta takunkumin Amurka kan Iran ya fara ne tun kafin hannun bankin a karshen shekarar 2016.
"HSBC ba ta da wata kiyayya ga Huawei kuma ba ta "tsarin" Huawei ba," in ji bankin a ranar Asabar, inda ya kara da cewa ba za ta taba gurbata wasu hujjoji game da abokan kasuwancinta ba.
"Da yake mayar da martani ga buƙatun US DOJ [Sashen Shari'a na Amurka] na neman bayanai, kungiyar HSBC ta gabatar da hujjoji na haƙiƙa.
HSBC bai "ƙirƙira" shaida ko " ɓoye" hujjoji ba."
Har ila yau a rt.com matakin da Birtaniya ta dauka na hana Huawei daga cibiyar sadarwa ta 5G ya nuna cewa Amurka ta umurci manufofin harkokin waje na Birtaniya - George Galloway ga Boom Bust
An toshe sakon a dandalin tare da rubuta cewa "ya sabawa ka'idoji" kuma ba a samu ba a yanzu.
Sanarwar na zuwa ne jim kadan bayan da wasu kafofin yada labarai na kasar Sin, ciki har da jaridun da ke da alaka da jihar, suka zargi HSBC da "cigaba" da Washington don kafa wa kamfanin Huawei tarko.
Kamfanin ya kasance a cibiyar wani abin kunya na diplomasiyya fiye da shekara daya da rabi tun lokacin da aka kama shugaban kamfanin Huawei Meng Wanzhou a watan Disamba na shekarar 2018 a Kanada bisa takardar izini daga Amurka.
Meng na fuskantar tuhume-tuhume na zamba saboda zargin yin amfani da kamfanin harsashi wajen kakaba wa Iran takunkumi da kuma zargin yi wa bankuna karya game da alakar da ke tsakanin Huawei da kamfanin Skycom na Iran.
A cewar sabbin shaidun da jaridar Global Times ta ambata, HSBC ta san dangantakar kamfanin kasar Sin da Skycom.
An bayar da rahoton cewa bankin ya yanke shawarar "kauracewa" da gwamnatin Amurka don tserewa daga hukunci mai tsanani a shekarar 2012, lokacin da bankin ya yarda da haramcin kudi da kuma keta takunkumi, ciki har da takunkumi kan Iran.
An umarce shi a lokacin da ya biya bashin kudi kimanin dala biliyan 1.9 da kuma hana duk wani laifi makamancin haka.
"Hujjojin sun nuna cewa HSBC ta fahimci wannan dangantaka amma da gangan ta sayar da takardun kasuwancin kwastominta na sirri ga bangaren Amurka don gwamnatin Amurka ta yi watsi da kuskuren da bankin Birtaniya ya yi, kuma ba za ta hukunta shi ba a karkashin yarjejeniyar tsare-tsare ta 2012", jaridar ta ce a daya daga cikin labarinta game da batun.
A cikin gargadin da ta yi a rufe, jaridar da ke kula da birnin Beijing ta kara da cewa, mai ba da rancen, idan aka tabbatar da cewa yana da laifin wannan "hadari", zai iya fuskantar "horo mai tsanani" a kasar Sin, daya daga cikin manyan kasuwanni na HSBC.
Wannan dai ba shi ne karon farko da mashahurin bankin ke fuskantar wuta ba a'yan makonnin nan.
A watan da ya gabata, HSBC ta sha alwashin goyon bayan sabuwar dokar tsaron kasa ga Hong Kong, birnin da kasuwancinta ya fara kuma wanda ya kai fiye da rabin ribarsa.
Bankin ya fuskanci zarge-zarge daga bangarorin biyu - daga kasashen Yamma, inda Sakataren Harkokin Wajen Amurka Mike Pompeo ya kira wannan tallafi a matsayin "kamfanoni kowanne hali" da kuma Gabas, inda bangaren China ya bayar da rahoton cewa, goyon bayan da yake bayarwa "ya yi watsi da shi".
Masu kashe gobara sun sami ƙasa a gundumar Lassen
Masu kashe gobara na samun karbuwa a kan gobarar daji biyu da ta kone fiye da kadada 30,000 a gundumar Lassen da ke arewa maso gabashin Sacramento.
Wutar Zinariya, wacce ta fara kudu da Adin, tana dauke da kashi 40% yayin da take ci gaba da barazana ga gidaje da gonaki da aikin noma da dabbobi da katako, in ji jami'an kashe gobara a wani sabuntawa a ranar Asabar da safe.
Bayan cin wuta na tsawon kwanaki hudu, gobarar ta tauna fadin eka 21,000, ta lalata gidaje bakwai sannan ta tura masu kashe gobara biyu zuwa asibiti.
A cikin dare, masu kashe gobara sun yi amfani da yanayi mai sauki don gina da kuma karfafa layin sarrafawa.
Amma ana sa ran iska mai guguwa da kuma karancin zafi har zuwa ranar Asabar.
Yammacin Susanville, wata karamar gobara da aka fi sani da Hog wuta ta lalata gine-gine biyu kuma ta cinye kimanin eka 10,000.
Wutar ta kwanta cikin dare yayin da masu kashe gobara suka yi aiki wajen sarrafawa tare da karfafa layukan sarrafawa, a cewar ma'aikatar kula da gandun daji da kare gobara ta California.
Ya zuwa safiyar Asabar, kashi 45% ne ke dauke da shi kuma sun yi kwanaki shida suna cin wuta.
A lokacin zafi na rana, da yanayin zafi sama da digiri 90 a yankin Susanville, wuraren shakatawa suna cikin haɗarin farfadowa.
Yayin da ake barin wasu mazauna gidajensu su koma gidajensu, wasu wuraren da ke wuraren kashe gobara biyu suna karkashin umarnin kwashewa.
An sako masu kashe gobara biyu da suka ji rauni a gobarar Gold daga asibiti.
Algeria: Mutuwar Mahmoud Guemama - Algeria Ta Yi Asarar Wani Dan Takarar Shugaban Kasa, In ji Shugaba Tebboune.
Shugaban kasar Algiers, Abdelmadjid Tebboune, ya aike da sakon ta'aziyya ga 'yan majalisar wakilan jama'ar kasar (APN), Mujahed Mahmoud Guemama, wanda ya rasu a ranar Juma'a, inda ya ce kasar Algeria "ta rasa wani dan kishin kasa da kuma wani dan gwagwarmaya da ya aikata ga al'ummarsa da kuma al'ummarsa."
Algeria ta yi asara a yau, ta hanyar rasuwar Mujahed Mahmoud Guemama, dan kishin kasa kuma dan gwagwarmaya da ya jajirce kan al'ummarsa da kuma al'ummarsa, mutumin da bai taba yin kasa a gwiwa ba, wanda azama ta kasance cikakke tun daga lokacin da ya dauki makami, tare da jaruman 'yan'uwansa Mujahedeen, har zuwa numfashinsa na karshe a wannan rana ta bakin ciki da kawai za mu yi murabus da nufin Allah", Shugaba Tebboune ya rubuta a sakonsa na ta'aziyya.
"Marigayi Mahmoud Guemama, zaman lafiya ya tabbata a gare shi, ya kasance cikin ƙarni na musamman na 'yan kishin ƙasa masu aminci wadanda suka sadaukar da kansu don ƙasarsu", ya kara da cewa shugaban Jamhuriyar.
"Marigayin ya sadaukar da rayuwarsa ga 'yantar da Aljeriya daga azabtarwar mulkin mallaka, ta hanyar shiga cikin sahun juyin juya halin da aka yi a farkon rayuwa a shekarar 1960 a sansanin horarwa na Tahart na tarihi mai lamba VI."
Shugaba Tebboune ya ce "marigayi shugaban kasa sananne ne ga kowa saboda irin karfin da ya ke da shi da kuma irin jajircewar da ya ke yi na ganin an kafa kasar Algeria mai arziki da hadin kai.
"A kudanci mai nisa, marigayi Mahmud Guemama ya yi suna sosai a matsayin mai shiga tsakani, yana mai shiga tsakani domin sulhunta 'yan'uwa a kasa guda a duk lokacin da aka hura wutar sabani" Shugaban ya kara da cewa a sakonsa.
"Dukkanin wadannan halaye da dabi'u sun sa marigayi Mahmoud Guemama girmamawa da amincewar mutanen Tamanrasset wadanda suka zabe shi ya wakilce su a majalisar wakilan jama'a ta kasa (APN) saboda sharudda da dama, a yayin da ya kasance jakada kuma mai kare damuwar yankin da burin al'ummarta, har ma da wakili da kakakin dukkanin 'yan Algeria", in ji shugaban kasar.
"Dukkanin maganganu na ta'aziyya ba za su isa su jinjina wa Mahmud Guemama ba, aminci ya tabbata a gare shi.
Yana barinmu a yau a daidai lokacin da kasar Aljeriya ta bukace shi," a cewar shugaban kasar.
"Ina rokon Allah madaukakin sarki da ya kewaye marigayin da rahamarsa mai tsarki, ya marabce shi a aljannarsa mai dimbin yawa tare da shuhadaa da nagarta.
Ina kuma addu'ar Allah ya baiwa iyalansa da masoyansa hakuri da ta'aziyya...babu wani karfi ko karfi sai da Allah" Shugaban kasar ya kammala.
Zanga-zangar Seattle: An yi ruwan wuta da barkono a yayin da dubban mutane ke tafiya a birni
SEATTLE - Bayan makonni na tashe-tashen hankula tsakanin masu zanga-zanga da hukumomin tarayya a Portland, Ore, taron mutane kimanin 2,000 sun yi tattaki a Seattle a ranar Asabar, suna tafiya a kan tituna tare da yin arangama da 'yan sanda.
Jami'an 'yan sanda uku sun ji rauni, ciki har da wanda aka kwantar da shi a asibiti da wani rauni a kafa sakamakon wani abin fashewa, kuma an kama masu zanga-zanga 16 tun da yamma, in ji 'yan sanda.
Dauke da alamomi kamar su "Feds Go Home" da kuma rera taken "Babu adalci, babu zaman lafiya", masu zanga-zangar sun tsaya a wurin da ake tsare da matasa a nan gaba tare da cinnawa gine-gine wuta a wurin.
Wasu sun fasa tagogin kasuwancin da ke kusa.
'Yan sanda sun fuskanci cunkoson jama'a a unguwar Capitol Hill, inda suka tura gurbataccen ruwa da kuma feshin barkono kafin su fara daukar mutane a tsare.
Bipasha Mukherjee, 'yar shekara 52, na Kirkland, Wash, ta ce tana zanga-zanga a kan tituna tun watan Mayu kuma ta ce abin damuwa ne a gare ta ganin irin wadannan dabaru na 'yan sanda.
"Wannan ba ita ce kasar da na yi hijira ba," a cewar Misis Mukherjee, wacce ta zo daga Indiya sama da shekaru 30 da suka gabata.
"Yana jin kamar muna hanzarin zama jihar fasaha da kuma 'yan sanda."
Michaud Savage na Seattle ya ce zanga-zangar na nufin duka kananan hukumomi ne da kuma tura jami'an gwamnatin tarayya wadanda suka janyo cece-kuce kan zanga-zangar da aka dade ana yi a Portland.
Mista Savage ya ce dabarun tilasta bin doka a Portland, wadanda suka hada da amfani da iskar gas da kuma garkuwa da jama'a, suna da hatsari kuma ba su dace ba.
Mista Savage ya ce a yayin da yake wanke idanunsa da feshin barkono kuma ya ji masa rauni a hannunsa daga gurbataccen ruwa.
Mutuwar George Floyd a hannun 'yan sanda a Minneapolis a watan Mayu ya yi watsi da zanga-zangar jama'a da ta jawo miliyoyin mutane a kan tituna a birane da dama, amma zanga-zangar ta ragu a yawancin birane.
Seattle da Portland, duk da haka, sun ga tsawaita zanga-zanga.
Masu zanga-zangar a Seattle a wani lokaci sun yi ikirarin wasu tubalan unguwar Capitol Hill kuma sun ayyana wani yanki mai cin gashin kai.
Bayan jerin harbe-harbe da aka yi a wurin ya sa 'yan sanda suka share yankin, zanga-zangar ta ragu.
Portland, a halin yanzu, ya ci gaba da zanga-zanga, tare da wasu daga cikin zanga-zanga mafi tsanani a kusa da gine-ginen tarayya a birnin.
Bayan da shugaba Trump ya bayar da umarnin zartarwa don kare mutum-mutumi da dukiyar gwamnatin tarayya, Ma'aikatar Tsaro ta cikin gida ta tura tawagogin dabara zuwa birnin, inda ta fara jerin rikice-rikice da suka yi sanadiyyar raunata masu zanga-zangar, binciken babban jami'in bincike da kuma kira daga shugabannin yankin don jami'an tarayya su tafi.
Taron masu zanga-zanga a wannan birnin ya karu zuwa dubban mutane, kuma ana ci gaba da zanga-zanga a wajen.
A wannan makon, jami'an tarayya sun tura wata tawagar dabara zuwa Seattle, kuma masu zanga-zangar sun ambaci wannan ci gaban a matsayin dalili daya na zanga-zangar ranar Asabar.
Yayin da zanga-zangar Portland ta tsakiya a cikin gari, zanga-zangar a ranar Asabar ta yi tafiya a yankunan da ke gabashin tsakiyar gari, inda gidan kotun tarayya na birnin yake.
Virginia Beach ta saukar da abin tunawa da kungiyar kwadago
VIRGINIA BEACH, Va. - Birnin Virginia Beach ya cire wani abin tunawa da 'yan kungiyar Confederate mai shekaru 115 daga filayen jama'a a ranar Asabar, kasa da kwanaki biyu bayan da Majalisar City ta zabe shi baki daya.
Ma'aikata sun saukar da ginin mai tsawon kafa 27 (mita 8.2) a safiyar ranar Asabar, kamar yadda kafafen yada labarai suka ruwaito.
An naɗa shi a shekara ta 1905 kuma ya tsaya a wajen tsohuwar gidan kotun Yarima Anne County, a daidai wurin da aka taɓa yin gwanjon bayi.
'Yan majalisa sun kada kuri'a baki daya ranar Alhamis da daddare domin fara aikin cire shi.
Majalisar ta saurari jawabai da dama kuma ta yanke shawarar cewa mutane da yawa suna kallon wannan ginin a matsayin rarrabuwa da kuma tunatarwa mai zafi game da abubuwan da suka gabata.
A kwanan nan an rufe mutum-mutumi gaba daya, tare da kulle kofa a kusa da shi bayan zanga-zangar da aka yi a baya-bayan nan da kuma zanga-zangar da aka yi a wasu gidajen tarihi na Confederate.
Za a ajiye abin tunawa a yanzu.
Yanzu dole ne birnin ya jira duk wani tayi daga kungiyoyin tarihi ko wasu abokai da za su so su dauki abin tunawa.
Kotun Masar ta ce mutumin da ya kashe yara uku ya yi nazarin tabin hankali
Babban Mai Shari'a na Kudancin Minya Tamer Motea a ranar Lahadi ya yanke wa wani manomi hukuncin zaman gidan yari na kwanaki hudu a lokacin da ake bincike kan dalilin da ya sa ya kashe 'ya'yansa uku yayin da kuma ya kai shi ga kwamitin kula da masu tabin hankali.
A ranar 24 ga watan Yuli, Mohamed Ali dan shekara 56 ya jefar da 'ya'yansa Khadiga, hudu, Mena takwas, da kuma Omar, shida, a gaban jirgin kasa mai tafiya a tashar jirgin kasa ta Mallawi.
An gano cewa Ali yana babbakewa ba tare da hadin kai ba a lokacin da ake gudanar da bincike, wanda hakan ya haifar da tuhumar cewa yana fama da tashe-tashen hankali.
Matarsa ta musanta cewa ta yi fama da wata matsala da shi kuma ta danganta halayyarsa da tabin hankali.
Mazauna kauyen Massart Mallawi sun daina magana kan lamarin, inda suka yi ta'aziyya kawai ga iyalan yaran.
Kusan kashi 93 cikin 100 na yaran Masar 'yan shekara daya zuwa 14 na fama da tashin hankali, in ji Khalid Darwish, mai ba da shawara ga majalisar kula da yara da 'yan uwa ta kasar a watan Oktoba.
Shari'a na daya daga cikin muhimman ginshikan kawar da cin zarafin yara, ya kara da cewa, yana mai jaddada muhimmancin hadin gwiwa tsakanin majalisa da hukunta jama'a a wannan bangare.
A cewar wani bincike da Hukumar Kula da Yara da Uwa ta Kasa ta shirya, ana fuskantar tashin hankali a wuraren da ya kamata a zauna lafiya, kamar gida, makaranta ko kulake, da kuma fuskantar tashin hankali daga mutanen da ya kamata su kula da su, kamar iyaye ko malamai.
'Yan kwadago masu tsattsauran ra'ayi sun bukaci a kori Corbyn ko kuma su fuskanci kara
Labour zai iya biya diyya na tsakanin £ 3million zuwa £ 8million, a cewar rahotanni.
Yanzu haka shugaba Keir Starmer na fuskantar matsin lamba na korar Mista Corbyn.
A daren jiya tsohon ma'aikatan jam'iyyar sun ce za su sauke matakin shari'a idan aka kori Mista Corbyn daga jam'iyyar.
Ya zuwa yanzu dai jam'iyyar Labour ta ki yin tsokaci kan bukatar.
Sai dai dan majalisar kwadago Jon Trickett ya ce: " Bukata ce ta ban dariya."
Masu goyon bayan Mista Corbyn sun ce Mista Starmer ya bukaci mayar da hankali kan magance matsalar Tories kan cutar Koronabirus maimakon komawa cikin kungiyoyin kwadago na cikin gida.
Wata majiya daga jam'iyyar Labour ta fadawa jaridar Daily Mail cewa za su dauki matakin shari'a ko da Mista Starmer ya kori Mista Corbyn.
"Ina nufin da gaske ne, ya sa jam'iyyar Labour ta sake yin takara."
"Har yanzu akwai wata hanya mai nisa da ya kamata a ci gaba da siyasa amma ya fara da ban sha'awa sosai kuma ya shiga wani yanayi inda ga mutane da yawa da suka bar jam'iyyar Labour da gaske, masu jefa kuri'a kamar yadda suke, ina ganin yanzu suna sake kallon hakan sosai kuma suna ɗaukarsa a matsayin wani mutum mai tsanani."
Mista Blair ya damu da cewa har yanzu ana ganin Labour a matsayin jam'iyyar da ke kara haraji.
Ya ce: "Abubuwan da na fuskanta game da haraji a lokacin da kake cikin jam'iyyar Labour suna mai da hankali sosai saboda jama'a da ke waje ba sa zaune a wurin suna damuwa ko za ku kara haraji ko a'a, mai yiwuwa suna damuwa cewa za ku kara haraji don haka kawai ku tuna da wannan damuwa."
Covid-19 za ta sauya tattalin arzikin duniya har abada (ra'ayi)
Binciken kwayar cutar zai iya zama wani bangare na rayuwarmu, kamar dai yadda matakan tsaro suka zama ruwan dare bayan 9/11.
Yana da muhimmanci a zuba jari a cikin kayayyakin da ake bukata don gano barkewar kwayar cutar a nan gaba.
Wannan zuba jari na kare tattalin arziki idan rigakafi ga Covid-19 ya zama na ɗan lokaci.
Yawancin tattalin arziki sun karbi nau'in tallafin Kurzarbeit na Jamus a lokacin annobar.
Wannan siyasa ta rike ma'aikata aiki a rage sa'o'i da biyan albashi, tare da gwamnati ta biya wasu daga cikin karancin albashi.
Ta hanyar ajiye wasanni tsakanin kamfanoni da ma'aikata, tattalin arziki ya fi dacewa a shirye don farfadowa cikin sauri.
Yana da muhimmanci a inganta aiwatar da wadannan manufofi da kuma sanya su zama wani bangare na dindindin na kayan aikinmu na farfado da tattalin arziki.
Aiki mai nisa zai zama ruwan dare gama gari.
Muna da wasu hujjoji da ke nuna cewa aiki daga gida yana da amfani sosai kamar aiki a ofishin.
Duk da haka, kamfanoni da yawa sun yi jinkirin rungumar aiki na nesa.
Yanzu da mutane da yawa sun gwada shi da kyakkyawan sakamako, aikin nesa na iya kasancewa a nan don zama.
Matsalar annobar ta hanzarta saurin sauya fasalin zamani, tare da kara fadada kasuwancin e-commerce da kuma karuwar saurin karɓar telemedicine, videoconferencing, koyarwa ta yanar gizo da kuma fintech.
Kamfanoni masu samar da kayayyaki na kasa da kasa suna fuskantar karanci da kuma cutar kwalara.
Mai yiwuwa za mu ga yawancin wadannan kamfanoni sun sake samar da wasu kayayyakin da suke samarwa.
Abin takaici, wannan yanayin ba zai haifar da ayyukan yi da yawa ba saboda yawancin abubuwan da ake samarwa suna iya sarrafa kansu.
Gwamnatoci za su fi girma bayan sun taka rawar inshorar da kuma saka hannun jari na karshe a lokacin rikicin.
bashin da jama'a za su ci, zai haifar da kalubalen kudi a duniya.
Darasi mafi muhimmanci daga annobar Covid-19 shi ne muhimmancin yin aiki tare kan matsalolin da suka shafi dan adam baki daya.
Mu ne mafi karfi da haɗin kai fiye da rarrabuwa.
Sarauniya da Adam Lambert: Brian May na murnar zagayowar ranar haihuwar Roger Taylor
Jaridar Sarauniya ta ba da labarin ranar haihuwarsa a yau tare da mai gabatar da kara na Rolling Stones Mick Jagger, wanda yanzu yake da shekaru 77 da haihuwa.
Brian May ya yi bikin zagayowar ranar haihuwarsa karo na 73 a karshen mako a ranar 19 ga watan Yuli kuma ya yi godiya ga magoya bayan da suka yi murnar zagayowar ranar haihuwar.
Tauraron dan wasan ya rubuta a wani rubutu da ya yi kusa da shi da matarsa Anita Dobson cewa: "Abincin dare na ranar haihuwa a gare ni - wanda Anita ta kirkiro - mun yi ado don mu zauna a gida!"
Sakataren Cikin Gida Priti Patel ya bukaci bayani daga Twitter da Instagram a kan 'abun ciki' Wiley tweets
Priti Patel ta bukaci bayani daga Twitter da Instagram a tsawon lokacin da aka dauka don cire sakonnin da Wiley ya yi.
A halin yanzu 'yan sanda suna bincike kan wasu kalamai na jayayya da aka wallafa a asusun mai zane-zane na Grime a kafofin watsa labarun.
Sakataren Harkokin Cikin Gida ya bayyana a ranar Lahadi cewa: "Sakamakon jayayya daga Wiley abin kunya ne."
"Bai kamata ba su samu damar ci gaba da kasancewa a Twitter da Instagram na tsawon lokaci ba kuma na nemi cikakken bayani a kansu."
"Dole ne kamfanonin kafofin watsa labarun su yi aiki da sauri don kawar da irin wannan kiyayya mai ban tsoro daga dandalin su."
An zargi Twitter da "karin jayayya" yayin da har yanzu ana ganin tweets na Wiley sa'o'i 12 bayan da aka fara sanya su.
Tun daga lokacin an cire wasu tweets kuma an sanyawa dan shekara 41-shekara dokar hana fita na tsawon kwanaki bakwai ta shafin.
A baya Twitter ya ce an kulle asusun Wiley na wani dan lokaci "saboda keta manufofinmu na nuna kyama", yayin da Facebook ya ce "babu wani wuri na kalaman nuna kyama a shafin Instagram."
'Yan sandan birni sun ce a ranar Asabar: "Ganawar tana daukar dukkan rahotannin jayayya da matukar muhimmanci, ana tantance abubuwan da suka dace."
A halin yanzu, kamfanin gudanarwa na Wiley, A-List Management, "ya yanke dukkanin dangantaka" da tauraron.
Tsohon manajan mai zane-zane a yanzu, John Woolf, wanda Yahudawa ne, ya rubuta a dandalin sada zumunta na Twitter cewa: "Bayan tweets na jayayya na Wiley a yau mu a @A_ListMGMT mun yanke dukkanin alaka da shi. Babu wani wuri a cikin al'umma don jayayya."
A baya ya ce bai goyi bayan ko kuma ya amince da abin da Wiley ya wallafa ba, amma zai yi magana da shi a asirce kuma "ta taimaka wajen ilmantar da shi."
Sai dai a wani bidiyo a shafin sada zumunta na Instagram, Wiley ya bayyana cewa shi ne ya yanke alaka da gudanarwarsa.
Sauran 'yan majalisar sun zargi Twitter saboda barin tweets su kasance a bayyane.
Kwamitin kwadago Jess Phillips ya ce a ranar Asabar:
"Kawai ga dukkanin kayan Wiley. Me ya sa a duniya @Twitter ta bar irin wannan tsattsauran ra'ayi na jayayya da ƙiyayya? Tana fuskantar dukkanin mummunan bugun jini, Yahudawa suna samun abubuwan da ba ku samu ba, suna da iko, suna tunanin cewa sun fi kyau... Wannan abu ne mai haɗari. Tabbas ya kamata ya sauka."
Dan majalisa Neil Coyle ya kara da cewa: "Gudanarwarsa na iya yin aiki da sauri fiye da @Twitter yana mai jaddada cewa, dokar (ciki har da Lissafin Harms na Yanar Gizo) ya kamata ta tabbatar da cewa ba a amfani da dandamali na kafofin watsa labarun don yada kiyayya ba."
John Mann, mashawarci mai zaman kansa na gwamnati a kan jayayya, ya ce tweets "ya nuna ainihin dalilin da ya sa doka ke bukatar canzawa don rike su zuwa lissafi mai kyau."
A halin yanzu, Gangamin Yaki da Cin Hanci ya bukaci 'yan sanda da su bincika abubuwan da Wiley ya yi, kuma ya yi kira ga a rufe asusunsa na kafofin watsa labarun "don hana ci gaba da zubar da dafin Yahudawa."
Wiley, wanda aka fi sani da Godfather of Grime wanda ainihin sunansa Richard Cowie, ya karbi MBE don ayyukan waƙa a 2018.
"kashe-kashe" da Amurka ke yi na dakile neman magungunan cutar Koronabirus
Ƙoƙarin da duniya ke yi na samar da magungunan yaki da cutar Covid mai amfani na kawo cikas ga Amurka saboda masu bincike suna gwajin magunguna ta "hanyar da ba ta dace ba", ƙwararren masanin da ke jagorantar shirin na Burtaniya ya yi gargadin.
Shirin farfado da cutar Birtaniya, wanda ya shafi marasa lafiya 12,000 a asibitocin Birtaniya da yawa, ya riga ya gano wani sabon magani mai ban al'ajabi don magance cutar sannan kuma ya nuna wasu biyu - wanda a baya ake zaton cewa masu ceton rai ne - a matsayin marasa amfani.
Amma gazawar tsarin kiwon lafiya na Amurka ya dace da wannan fitarwa ya sa sauran magunguna masu ban al'ajabi da za a iya sharewa don amfani da su sosai, har yanzu ba a tantance su ba.
Musamman ma, plasma mai dauke da kwayar cutar (blood plasma wanda aka dauka daga masu dauke da cutar Covid-19 wanda ke dauke da garkuwar jiki wanda zai iya kare wasu daga cutar) har yanzu ana gwada shi yadda ya kamata a wani babban gwaji na bazuwar cutar.
Farfesa Martin Landray, daya daga cikin wadanda suka kafa shirin farfado da cutar, ya ce "an riga an bai wa dubban mutane kwayar cutar plasma a Amurka amma ba a yi watsi da wadannan magunguna ba.
"Suna ba wa mutane kwayar cutar plasma ne kawai da fatan za ta yi aiki. An bayar da adadi mai yawa kuma har yanzu ba su san ko tana taimakawa ko cutarwa ko kuma ba ta da tasiri," in ji Landray, wani kwararre a fannin kafa manyan gwaje-gwajen magunguna.
Amurka ta kasa yin manyan gwaje-gwaje da bazuwar gwaji kuma hakan ya kawo karshen samar da magani mara kyau.
Gwajin magunguna marasa kyau sune ma'aunin zinare don gano magunguna masu amfani.
Suna cire nuna bambanci da ba a sani ba wanda zai iya haifar da hukuncin likitocin asibiti.
Ana bai wa dubban mutane magani sannan a ba dubban wasu magunguna.
Babu wanda ya san wanda aka ba su.
Sannan an kwatanta sakamako kuma an bayyana ingancin maganin.
Ta wannan hanyar, farfadowa ya iya nuna cewa steroid dexamethasone ya rage mutuwar da kashi uku a cikin marasa lafiyar Covid-19 a kan na'urar bada iska.
Haka kuma ya nuna cewa maganin hydroxychloroquine mai yawa - da kuma maganin hada-hadar magungunan lopinavir da ritonavir - ba su da wani tasiri wajen ceton rayukan marasa lafiya.
Abin da ya fi muhimmanci wadannan gwaje-gwaje suna bukatar adadin marasa lafiya da yawa kuma babu wani asibiti da ya isa ya yi irin wannan bincike.
Birtaniya ta sami wata fa'ida mai mahimmanci - Hukumar Kiwon Lafiya ta Kasa.
Sabanin haka, ma'aikatar kiwon lafiya ta Amurka ta rarrabu kuma nasararta kadai ta nuna yiwuwar magani ta nuna amfani da maganin remdesivir mai tsada sosai don hanzarta warkewar wasu marasa lafiya na Covid-19.
"Akwai gwajin kananan magunguna da yawa da suka shafi 'yan dozin ko 'yan daruruwan marasa lafiya da ke gudana a Amurka amma babu wani abu," in ji Landray.
"Sun kasa yin manyan gwaje-gwaje da bazuwar cutar kuma hakan ya kawo karshen samar da magani marar kyau. Hakan ya sa al'adar magani ba ta da kyau kuma sakamakon marasa lafiya ba shi da kyau."
Landray ya ce wannan gazawar ta yi matukar baƙin ciki idan aka yi la'akari da amfani da plasma mai dauke da cutar, wanda likitoci da yawa ke ganin zai iya taka muhimmiyar rawa wajen kula da marasa lafiya masu fama da cutar Covid-19.
"Idan ka kalli Amurka, an yi amfani da adadi mai yawa na wannan magani a kan wani abu mai ban sha'awa. Birtaniya ta fi dacewa idan aka kwatanta da abin da ke faruwa a can", ya kara da cewa.
Farfesa Peter Horby, wani kwararre a kan cututtuka da kuma wanda ya kafa shirin farfado da cututtuka, ya ce: "Akwai rahotannin marasa lafiya 20,000 da ke samun kwayar cutar plasma a wani lungu amma babu wani daga cikin wadanda suka kamu da cutar.
Da a ce sun saka wadannan marasa lafiya cikin gwaji na bazata, yanzu za mu samu cikakkiyar amsa game da ingancin kwayar cutar plasma."
Horby ya kara da cewa, a yanzu Burtaniya ta kaddamar da gwajin cutar plasma na bazata amma ba ta sa ran samun sakamako a shirye sai nan gaba a wannan shekarar.
Masar ta fara rijistar bayanan masu kada kuri'a a kasashen waje domin zaben 'yan majalisar dattijai
Hukumar Zabe ta Kasa (NEA) a ranar Asabar ta fara rijistar bayanan masu kada kuri'a a cikin jirgin domin fara jefa kuri'unsu a zaben'yan majalisar dattijai da za a gudanar a ranakun 9 da 10 ga watan Agusta, a cewar shafin intanet na NEA.
Dole ne masu jefa kuri'a su yi rajistar bayanan su da kuma aikin diplomasiyya da ke da alaƙa da mazauninsu a ƙasashen waje a shafin yanar gizo na NEA daga ranar 25 ga watan Yuli har zuwa ranar 31 ga watan Yuli.
Hukumar NEA ta kuma wallafa wani bidiyo da ke bayyana matakan da masu jefa kuri'a za su iya dauka don jefa kuri'arsu a nesa ta hanyar imel, a matsayin wani bangare na matakan kariya daga annobar coronavirus.
Lokacin shari'a na farfagandar zaben 'yan takarar majalisar dattijai ya gudana ne daga ranar 26 ga watan Yuli har zuwa ranar 8 ga watan Agusta, in ji NEA.
Ministan kula da harkokin shige da fice na Masar Nabila Makram ya yi kira ga 'yan kasar Masar masu kada kuri'a a kasashen waje da su shiga zaben a matsayin hakkinsu na tsarin mulki.
Majalisar wakilan Masar a ranar 17 ga watan Yuni ta amince da dokar kafa majalisar dattijai, wacce za ta yi aiki a matsayin babba a majalisar dokokin kasar.
An zartar da dokar ne da rinjaye kashi biyu cikin uku, tare da kin amincewa da wasu 'yan majalisar dokoki hudu
Majalisar za ta kunshi mambobi 300, 100 daga cikinsu an zabe su ne ta hanyar tsarin jerin sunayen da aka rufe, 100 an zabe su ne bisa tsarin daidaikun mutane, da kuma mambobi 100 da shugaban kasar ya nada
Wa'adin zama mamba a majalisar dattawa zai cika shekaru biyar, wanda zai fara daga ranar da za a fara ganawarsa ta farko.
Za a zabi sabuwar majalisar ne a cikin kwanaki sittin gabanin karshen wa'adin mulkinta.
'Yan sanda sun gwada sabbin kayan aiki marasa karfi yayin da zanga-zanga ke ci gaba
Yayin da ake ci gaba da fama da rikice-rikice tsakanin masu zanga-zanga da masu zanga-zanga a Portland da kewaye da kasar, ana ci gaba da muhawara kan yadda 'yan sanda za su iya yanke hukuncin kisa.
Wasu kamfanoni suna ci gaba da samar da sabbin kayan aiki na fasaha kamar na hannu mai nisa don 'yan sanda su yi amfani da su a maimakon zaɓuɓɓuka masu haɗari kamar fesa barkono, harsasai na roba da kuma gurbataccen walƙiya.
Kungiyar kare hakkin bil adama ta Amnesty International ta yi nazarin bidiyo 500 daga zanga-zangar daga ranar 26 ga watan Mayu zuwa ranar 5 ga watan Yuni kuma ta gano aukuwar karfi da ya wuce kima a jihohi 40 da kuma gundumar Columbia.
"Mun ga rashin amfani da iskar gas mai sa hawaye, da feshin barkono, da kwallayen barkono, da zagaye masu tasiri na tsawon millimita 40, ainihi duk wani nau'in makami marar karfi ana amfani da shi ta hanyoyin da ba su dace ba", a cewar Brian Castner, mai binciken makamai na kungiyar Amnesty International.
Duk da haka, wasu sun nace cewa samun zabin yana da muhimmanci don kaucewa bukatar bindiga.
Corey Pegues, tsohon mataimakin Sufeto na 'yan sanda na New York, ya ce "ya kamata dukkanin wadannan na'urori su kasance a hannun 'yan sanda su yi amfani da su ban da karfi na jiki da ake amfani da shi ta hanyar bindiga saboda ita kadai ce sana'a a Amurka inda 'yan ƙasa ke ba ku damar ɗaukar rayuwarku.
Daya daga cikin sababbin kayan aikin shine sunan Bola Wrap, na'urar hannu da ke harba igiyar Kevlar mai ƙafa 8 da ke kewaye da wanda ake zargi.
Akwai na'urorin Acoustic na dogon zango, wanda kuma aka fi sani da canons na sauti, da makaman makamashi da ke amfani da lasers don zafin fatar mutum, da sabbin kayan aikin da aka yi da su daga abubuwa kamar kumfa da zangarniya, da bama-bamai na stink, da kuma ba shakka Taser.
Hannun jari na Axon, kamfanin da ke yin Taser, ya kai sama da kashi 18%, wanda ya kai tsawon lokaci lokacin da zanga-zangar ta juya kwanaki bayan kisan George Floyd da 'yan sanda suka yi.
Ana sa ran kasuwar makamai marasa karfi za ta kai dala biliyan 11.85 nan da shekarar 2023.
Ku kalli bidiyon don duba sabbin kayan aiki na fasaha da 'yan sanda ke amfani da su don karfi mai karfi, yadda aka tsara su, da kuma abin da ke tattare da makomar 'yan sanda da kuma al'ummomin da suke hidima.
Magajin garin Kansas ya yi maraba da taimakon gwamnatin tarayya wajen magance kisan gilla, amma ya damu da muradin Trump
Magajin garin Kansas Quinton Lucas ya yi tambaya a ranar Lahadi kan dalilin Shugaba Trump na tura jami'an tsaro na tarayya zuwa biranen Amurka - yana mai cewa yayin da zai yi maraba da taimakon da aka bayar wajen magance kashe-kashen da aka yi a tsakiyar yammacin birnin, yana ganin matakin zai fi dacewa da samun damar sake zaben Trump.
"Na yi kyakkyawan takaici a wannan makon [cewa] shugaban kasar ya ambaci zanga-zangar George Floyd, ya ambaci yunkurin Black Lives Matter" Lucas, dan jam'iyyar Democrat, ya ce a "Fox News Lahadi" na zanga-zangar da aka yi a baya-bayan nan kan rashin daidaituwar launin fata da kuma zaluncin 'yan sanda.
"Ba haka lamarin yake ba a Kansas City. Mun samu karuwar shekara-shekara [amma] abin da muke bukatar taimako a kai shi ne a zahiri share wasu daga cikin kisan da ba a warware su ba."
Lucas ya kara da cewa: "Bari mu yi ƙoƙari mu mai da hankali kan magance kisan kai... Ina ganin idan kun saurari maganganun da aka yi a baya-bayan nan... muna farin cikin yin aiki tare da jami'an tsaro na tarayya cikin iyaka."
Duk da cewa a shirye yake ya sa jami'an tsaro na tarayya su yi aiki tare da masu bin doka a yankin, Lucas ya ce wannan rikici na Trump - musamman dangane da rigingimun da ke tattare da dabarun da jami'an gwamnatin tarayya ke amfani da su a Portland, Ore, ya sa yawancin 'yan majalisarsa su nuna damuwa game da kasancewar jami'an tsaro a titunan birnin.
"Abin da ba mu bukata ba shi ne karin wuta daga jami'an tsaro na tarayya da za su yi, ina tsammanin, wani lamari ne mai ban sha'awa na siyasa", in ji shi.
Trump a ranar Laraba ya sanar da cewa yana tura jami'an gwamnatin tarayya 100 zuwa Chicago don taimakawa wajen yaki da hauhawar wasu laifuka - wani yunkuri da ke nuna fadada sa hannun Fadar White House a kan tilasta bin doka a yankin yayin da Trump ke ci gaba da sanya kansa a matsayin shugaban "doka da oda".
"karuwar" jami'an da aka sanar a ranar Laraba zuwa Chicago da sauran biranen Amurka wani bangare ne na Operation Legend - wanda aka yi wa lakabi da LeGend Taliferro dan shekara 4 da haihuwa, wanda aka harbe shi a lokacin da yake barci a wani gida na Kansas City a karshen watan da ya gabata.
Yayin da tura jami'an gwamnatin tarayya don taimakawa masu bin doka a yankin ba wani abu ba ne - Babban Mai Shari'a Bill Barr ya sanar da irin wannan karuwar a watan Disamba ga birane bakwai da suka ga tashin hankali - irin wakilin tarayya da aka aika, da kuma wasu dabarunsu, sun tayar da damuwa tsakanin 'yan majalisar jihohi da na yankin.
'Yan majalisar dokoki da dama daga New York zuwa Portland sun yi kakkausar suka kan gwamnatin Trump na tura jami'an tsaro zuwa garuruwansu, musamman bayan rahotannin da ke cewa wasu jami'an gwamnatin tarayya da ba a san ko su wanene ba sun tsare masu zanga-zanga a Portland kuma sun tafi da su a cikin motocin da ba a nuna ba.
Portland ta fuskanci zanga-zanga a kusa da kullum a kan zaluncin 'yan sanda da kuma wariyar launin fata tun bayan mutuwar George Floyd yayin da yake tsare a hannun 'yan sanda a Minneapolis a ranar 25 ga watan Mayu.
Har ila yau, hukumomin karkara sun yi korafin cewa karuwar ta haifar da tashin hankali ne kawai, kuma masana shari'a masu laifi sun ce kokarin ya kauce wa bayanin saboda lokacin da Amurka ke rayuwa - tare da annoba, rashin aikin yi na tarihi da kuma yin la'akari da wariyar launin fata da kuma yadda 'yan sanda ke kula da mutanen launin fata.
AP ta dakatar da sakataren yada labarai na Fadar White House Kayleigh McEnany saboda tattaunawar "siyasa" - amma manema labarai suna ci gaba da yin tambayoyin siyasa - RT USA News
Jaridar Associated Press ta zargi sakatariyar yada labaran fadar White House Kayleigh McEnany da damuwa da kafofin yada labarai ta hanyar yi mata bayani ta fuskar siyasa maimakon bayanai - a bayyane ta manta cewa manema labarai sun zabi tambayoyin.
Wani labarin a ranar Asabar na kamfanin dillancin labarai na AP, mafi girma a Amurka, ya ce tattaunawar manema labarai na Fadar White House na iya zama "al'ada mai karyewa", kamar yadda McEnany ya sanya su "tallace-tallace mai zurfi ga shugaban kasa da ke fuskantar sake zabe, wurin kai hare-hare a kan kafofin watsa labarai da kuma dandalin tattaunawa kan bayanai" game da abin da gwamnati ke yi.
Na karshe daga cikin wadannan maganganu ba za a iya tabbatar da su ba, kamar yadda babu wani sabon bayani da aka bayyana a tattaunawar.
Abin da AP ta kasa ambata shi ne cewa babu wani sabon bayani da ake nema a zahiri a tattaunawar.
'Yan jarida na yawan amfani da 'yan jarida na fadar White House don jawo hankalin kansu, wani nau'i na fasaha da Jim Acosta na CNN ya kammala.
Suna wuce dangantakar kafofin watsa labarai masu adawa da juna, suna maimaita juna wajen yin tambayoyin gotcha da nufin tursasawa Shugaba Donald Trump kawai.
A wasu lokuta, suna mai da kansu labarai, kamar lokacin da jaridar CBS News Weijia Jiang ta mayar da martani ga wani "tambaya China" da Trump ya yi ta hanyar yin wani abin da bai dace ba game da wariyar launin fata: "Sir, me ya sa kake fadin hakan a gare ni musamman?"
Tattaunawar ranar 6 ga watan Yuli ta ba da misali mai kyau game da yadda tattaunawar ta daina zama tushen bayanai masu ma'ana ga Amurkawa.
A wani sako da ya wallafa a shafinsa na sada zumunta na Tuwita a safiyar yau, Trump ya bayyana cewa tashar talabijin ta NASCAR ta cutar da wani zargi na nuna kyama ga direba Bubba Wallace da kuma hukuncin da ta yanke na hana nuna tutar kungiyar kwadago a abubuwan da suka faru.
A tsinkaya, yawancin tambayoyin sun kasance game da tweet a matsayin mai rahoto bayan da mai rahoto ya tambayi McEnany tambayoyi da aka tsara don ya sa ta ce Trump na goyon bayan tutar Confederate.
McEnany ba ta bayar da amsar da manema labarai ke so ba - cizo mai sauti da zai cutar da Trump - amma ta mayar da martani sau da yawa ta hanyar cewa shugaban kasa ba ya daukar wani matsayi a tutar Confederate kuma abin da ya faru a sakonsa shi ne cewa an yi kuskuren nuna magoya bayan NASCAR a matsayin masu nuna wariyar launin fata.
AP ta ce ta yi "baƙin ciki" a lokacin tattaunawar.
Labarin na AP ya maimaita wani shafi na jaridar Washington Post a farkon watan nan na dan jaridar ABC News Jonathan Karl, wanda kuma shi ne shugaban kungiyar masu ba da amsa a fadar White House.
Karl ya yi jayayya da cewa, "karin gaskiya da kuma amfani da fadar White House a kan manufofi na siyasa kawai, keta yarda da jama'a ne."
Duk da haka hanzarin da McEnany ta yi da kuma salon kame-kame ya sa ta zama jarumar wasu magoya bayan Trump, tun bayan da ta gabatar da jawabinta na farko a ranar 1 ga watan Mayu bayan da ta karbi mukamin sakatariyar yada labarai a watan Afrilu.
'Yan jaridar sun shafe fiye da shekara guda kafin nadin nata.
Kamar sauran fannoni na rayuwar siyasa a Washington, dangantakar sakataren yada labarai na fadar White House da kafofin yada labarai ta sauya sosai a zamanin Trump.
Wannan canji ya fito ne daga bangarorin biyu kuma ya yi hasashen zuwan McEnany.
Tsohuwar sakatariyar yada labarai Sarah Huckabee Sanders ta hannun 'yar wasan kwaikwayo Michelle Wolf a wurin cin abincin dare na 'yan jarida na Fadar White House a watan Afrilun shekarar 2018 ta yi muni sosai har ma mai masaukin baki na MSNBC Mika Brzezinski ya kira shi "m."
Jill Colvin, 'yar jarida a fadar White House, ta gaishe da McEnany a jawabinta na farko ta hanyar tambayar cewa, "Shin za ku yi alkawarin cewa ba za ku taba yi mana karya ba daga wannan matsayi?"
Mai sharhi kan harkokin siyasa na Fox News Brit Hume, wani tsohon dan jarida da ya shafe sama da shekaru 50 a aikin jarida wanda ya yi zamansa a shekarar 1989-1996 a matsayin babban wakilin fadar White House ta ABC, ya ce a yau manema labarai na nuna "matsanancin hali" a dakin tattaunawa saboda cin mutuncin da suke yi wa Trump.
Saboda yadda suka mayar da hankalin Trump, ya ce a wannan makon a shirin Fox na Tucker Carlson Tonight, 'yan jarida suna yin watsi da tattara labaran siyasa.
"Ba wasan gotcha ba ne kawai," Hume ya ce game da manufar 'yan jarida.
"Ba wai kawai kokarin kunyatar da wani jami'in jama'a ba ne, don fitar da bayanai ne."
Wuraren shakatawa na shakatawa da aka gani dauke da makamai da wukake, masu sukurori da kuma CHAINSAW a matsayin 'yan fashi suna ba su makamai don lalata motoci'
The primates a Knowsley safari shakatawa, Merseyside, an dade da sani su pounce a kan duk wanda ya dakatar da a cikin yadi da kuma ripping kashe wani windscreen wiper ko madubi.
Baboons sun kasance dauke da makamai da wuka, masu sukurori har ma da sarkakiya a wurin shakatawa na Knowsley, Merseyside.
Ma'aikata suna tsoron 'yan wasan kwaikwayo suna ba da makamai masu ban sha'awa, wadanda aka san su da yin watsi da duk wanda ya dakatar da shi kuma ya cire kayan shafawa da madubai.
Yanzu ma'aikata suna tsoron cewa suna dauke da makamai masu kisa "don dariya" da baƙi suka yi don ƙarfafa hare-haren da suke kaiwa, har ma an ga afkawa a kusa da akwatunan kayan aiki da kansu.
Wani ma'aikacin wurin shakatawa ya shaida wa jaridar The Sunday Times cewa: "Ba mu da tabbacin ko wasu daga cikin baƙin da ke son ganin sun kai wa motoci hari, ko kuma sun kama su ne daga manyan motoci da motocin daukar kaya."
"A zahiri za su shiga cikin akwatunan kayan aiki na mutane kuma su dauke su. An ga daya daga cikin magungunan cutar yana tafiya a kusa da wata motsa jiki."
Wani ma'aikacin ya ce: "An same su da wuka da kuma masu sukurori, ina mamakin ko wasu daga cikin baƙin ne suke mika su."
Kuma hare-haren da ake kaiwa a yankunan da ke arewa maso yammacin Ingila ba makawa ne cewa injiniyoyi a arewa maso yammacin Ingila sun san abin da ke faruwa sosai.
Wani injiniya a Sale, Greater Manchester ya ce mutane sun san abin da za su yi tsammani a wurin shakatawa kuma ya sami kwastomomi biyu da suka kamu da cutar a wannan shekarar.
Sun kara da cewa minti daya yara suna son dodanni a motar kuma na gaba ba su da farantin rajista - amma batun ya samar da "kudi mai kyau" ga garejin.
Knowsley ya sake buɗewa a ranar 15 ga Yuni tare da matakan tsaro na Covid-19 bayan da ya nace cewa yana da aminci kamar yadda McDonald ya yi tafiya yayin da baƙi ba sa barin motarsu a tafiyar kilomita biyar.
Gidan shakatawa mai girma 550, da ke dauke da zakuna, damisa, rhinos, bawa da raƙuma, ya yi watsi da rahotannin afuwa mai dauke da makamai a matsayin tatsuniyoyi na birane.
Wani mai magana da yawunsa ya ce: "Mun yi imanin cewa da yawa daga cikin wadannan labaran sun karu da wuce gona da iri yayin da aka sake maimaita su, tare da yin kwalliya don sanya abubuwan da a wasu lokuta ake samu a cikin gidan su zama masu ban sha'awa da kuma rashin yarda."
A shekarar 2012 kamfanin kera motoci kirar Hyundai ya bar dodanni 40 daga wurin shakatawa a kan samfurinsa na New Generation i30 na tsawon awanni 10 don tabbatar da cewa yana da karfin gwiwa ga iyalai da ke da kananan yara.
Kudlow ya ce lissafin cutar coronavirus na gaba zai hada da karin bincike, tsawaita dokar hana fita
Mai ba da shawara kan harkokin tattalin arziki na Fadar White House Larry Kudlow ya yi alkawari a ranar Lahadi cewa gwamnatin tarayya za ta tsawaita dokar hana fita tare da aika wani zagaye na bincike a matsayin wani bangare na kunshin cutar coronavirus mai zuwa.
Kalaman na Kudlow na zuwa ne bayan mako guda da fadar White House ta yi fatan rage harajin albashi daga Majalisa.
"Akwai rajistan $1,200 yana zuwa. Wannan zai zama wani ɓangare na sabon kunshin. Da na fi son a yanke harajin albashi, a saman wannan rajistan," Kudlow ya ce a CNN ta "State of the Union."
"Amma, kamar yadda ya kamata, a siyasa, ba ya aiki."
Duk da cewa ba a sanar da wata yarjejeniya a hukumance ba, Sakataren Baitulmalin Steve Mnuchin da shugaban ma'aikatan fadar White House Mark Meadows sun kasance a Capitol Hill kwanan nan don tattauna cikakkun bayanai game da sabon kayan agaji tare da shugabannin majalisa.
Bayan kawo karshen karin dala 600 na rashin aikin yi da gwamnatin tarayya ke bayarwa, Kudlow ya yi zargin cewa karin kudin na cutar da kananan kamfanoni daga hayar ma'aikata.
"Mun samu ambaliyar tambayoyi da kiran waya da kuma korafe-korafen cewa kananan shaguna da kasuwanci, gidajen cin abinci ba za su iya dawo da hayar mutane ba," in ji shi.
"Sun yi nisa sosai, watakila a watan Maris da ya gabata, hakan ya zama dole, amma, hakika, akwai sakamakon da mutane ba sa komawa bakin aiki."
Mnuchin a farkon wannan rana a "Fox News Sunday" ya fadi hakan a fili cewa: "Ina tsammanin ma'aikata da Amurkawa sun fahimci manufar cewa bai kamata a biya ku kudin da za ku ci gaba da zama a gida ba fiye da aiki ba."
Mnuchin ya ce sabuwar dokar za ta samar da ƙarin amfanin marasa aikin yi, amma ya lura cewa za ta kasance ƙasa da biyan kuɗin da aka bayar a ƙarƙashin Dokar CARES.
Ya ce wasu ma'aikata suna tattara fiye da yadda suka samu a aikin.
Sakamakon haka, a lokacin da aka sake bude harkokin kasuwanci wasu ma'aikata ba su da wani dalili na komawa bakin aiki.
Sakataren ya ce gwamnatin Trump da 'yan Republican Majalisar Dattijai suna kan wannan shafi tare da kunshin dala tiriliyan 1, amma ya lura cewa don sha'awar zartar da doka cikin sauri, za a iya tsayar da batutuwan da suka fi wahalar tattaunawa da 'yan jam'iyyar Democrats don wata doka.
An Kama Mutumin Da Ake Zarginsa Da Kashe Ɗan'uwan Barasa A Greater Noida: 'Yan sanda
An kama wani mutum dan shekara 37 a ranar Lahadi saboda zargin kashe ɗan'uwansa, wanda aka gano gawarsa a wani wuri da aka ware a makon da ya gabata, a Uttar Pradesh's Greater Noida, in ji 'yan sanda.
Wanda ake zargi ya shaida wa 'yan sanda cewa shan giya da kuma mummunan hali da ɗan'uwansa ya yi da mata 'yan iyalinsu na hadin gwiwa, wanda hakan ya kai shi ga aikata laifin, a cewar jami'ai.
An tsinci gawar Bhisham Singh, mazaunin kauyen Bisrakh a Greater Noida, a kusa da daji a wani kebabben wuri kusan mako guda da ya wuce.
Wani kakakin 'yan sanda ya ce, gawar ta haifi alamomi kuma an kwashe wata FIR a ofishin 'yan sanda na Bisrakh kuma an gudanar da bincike.
"A lokacin binciken, shaidu sun kai 'yan sanda ga mutumin, wanda ya mutu, ɗan'uwansa Deepak kuma an tambaye shi. A lokacin da aka tambaye shi, Deepak ya yi ikirarin cewa ya kashe ɗan'uwansa. Ya gaya wa 'yan sanda cewa Bhisham zai ci giya akai-akai, ya haifar da ruckus a gida kuma ya yi kuskure da 'yan uwa mata saboda haka ya yanke shawarar kashe ɗan'uwansa", in ji kakakin.
An kama wanda ake zargi kuma an tuhume shi da laifin kisan kai da sauran tuhume-tuhume masu nasaba da hakan, in ji 'yan sanda.
Dutse daga duniyar Mars ya nufi gida bayan ya cika shekaru 600,000 a Duniya
A karamin dutse za a jefa a cikin sararin samaniya a wannan makon a daya daga cikin mafi ban mamaki interplanetary tafiye-tafiye taba yunkurin.
Za a kaddamar da wani dan karamin basalt na Martian mai girman tsabar kudin 10p a cikin wani bincike na robot na Amurka a ranar Alhamis da kuma motsawa zuwa ga duniya mai launin fata a wata tafiya na watanni bakwai zuwa duniyarsa.
Wannan tashin hankali na ban mamaki, wanda ya yi daidai da tura garwashin zuwa Newcastle, zai zama wani bangare mai mahimmanci na balaguro na Nasa mai zuwa a duniyar Mars 2020.
Injiniyoyin sararin samaniya sun ce dutsen - wanda gidan adana kayan tarihi na Natural History da ke London ya bayar - za a yi amfani da shi wajen daidaita masu bincike a cikin jirgin na'urar robot rover Perseverance bayan da ya sauka kuma ya fara neman alamun rayuwar da ta wuce a duniya.
Wasu daga cikin meteorites na Martian da muke da su ba su da kyau, amma mun zabi wannan musamman saboda yana da wuya kamar tsofaffin takalma
"Lokacin da ka kunna kayan kida kuma ka fara kunna su kafin ka yi amfani da su don bincike, sai ka daidaita su a kan kayan da za su zama kamar abubuwan da ba a san su ba da za ka yi nazarin su. To, me ya fi kyau a yi nazarin duwatsu a duniyar Mars fiye da wanda ya samo asali a wurin?" in ji Farfesa Caroline Smith, mai kula da kayan tarihi na Meteorite.
Masana kimiyya sun yi amannar cewa dutsen da suke komawa duniyar Mars ya samo asali ne daga doron kasa, in ji Smith, wanda shi ma mamba ne a kungiyar kimiyya ta duniyar Mars 2020.
"Kananan kumfa na gas da aka kama a cikin wannan meteorite suna da daidai da yanayin duniyar Mars, don haka mun san dutsenmu ya fito daga wurin."
Ana kyautata zaton cewa an halicci sararin samaniya ne a lokacin da wani dan kunar-bakin-wake ko tauraro ya kutsa cikin duniyar kimanin shekaru 600,000 zuwa 700,000 da suka wuce, inda ya fesa tarkace zuwa sararin samaniya.
Daya daga cikin wadannan gine-gine ya fadi a fadin hasken rana kuma daga baya ya fadi zuwa duniya.
Wannan meteorite - wanda a yanzu ake kira SAU 008 - an gano shi ne a Oman a shekarar 1999 kuma yana kula da gidan adana kayan tarihi na dabi'ar halitta tun daga wannan lokacin.
Daga cikin kayan da suka dace da na'urar Perseverance rover akwai na'urar daukar hoto mai suna Sherloc, wacce za a yi amfani da ita wajen fassara sinadaran da ke cikin duwatsu da kuma tantance ko za su iya dauke da kwayoyin halitta da ke nuna cewa rayuwa ta wanzu - ko kuma ta wanzu - a duniyar Mars.
Haɗa wani yanki na SAU 008 an yi shi ne don tabbatar da cewa an yi hakan tare da iyakar daidaito.
"Dutsen da muke aikawa an zabi shi ne musamman saboda abu ne da ya dace a fannin ilimin sunadarai, amma kuma dutse ne mai matukar wahala," in ji Smith.
"Wasu daga cikin meteorites na Martian da muke da su suna da karfi sosai, wannan meteorite yana da wuya kamar tsofaffin takalma."
Da zarar Perseverance ta zabi duwatsu mafi alfanu da za ta iya samu, za ta zuba su a cikin tsabar kudi a saman Martian.
Wadannan za a dawo da su ta hanyar ayyukan robot na gaba kuma a busa su cikin sararin samaniya zuwa Duniya don bincike.
Barcelona 'suna da dukkanin bangarorin da za su sayar' a wannan bazara kamar yadda Coutinho, Dembele, Rakitic da Vidal suka lissafa don canja wurin
BARCELONA za a san shi a matsayin kulob din da ake sayarwa a wannan bazara, a cewar rahotanni.
Babu kasa da taurari 12 na farko da aka canjawa jerin sunayen 'yan wasan La Liga, da'awar Marca.
Barcelona ta bayar da rahoton cewa Philippe Coutinho ya canja sheka
Kuma wadanda suka hada da 'yan wasan gasar Premier Philippe Coutinho da Ousmane Dembele da Ivan Rakitic da kuma Samuel Umtiti.
An danganta Coutinho da Umtiti da komawa Arsenal, yayin da dan kasar Brazil kuma Chelsea ta lura da shi.
Yayin da ake cewa Manchester United da Tottenham na fama da aiyukan Rakitic.
Dembele wanda ya lashe gasar cin kofin duniya ta Faransa, wanda ya yi fama da lokacin wasa a Camp Nou, a baya-bayan nan an alakanta shi da komawa PSG a yarjejeniyar canza sheka da Neymar.
Sauran'yan wasan da ake ganin sun fi biyan bukata sun hada da Neto, da Nelson Semedo, da Junior Firpo, da Arturo Vidal, da Martin Braithwaite, da Carles Alena, da Rafinha Alcantara, da kuma Jean-Clair Todibo.
Barcelona na fatan fitowa fili ba kawai zai bunkasa kudadensu ba, amma zai taimakawa kasuwancin canja wurin su a nan gaba.
An kuma ce Ousmane Dembele ya zarce abin da ake bukata
A cewar jaridar Spain, Barcelona ta riga ta gano manufofin canja wurin su na kakar wasa mai zuwa - tare da dan wasan gaba na Argentina Lautaro Martinez a saman jerin sunayen da suka buga.
Amma Inter Milan na ci gaba da neman a sako shi fam miliyan 101 kafin tattaunawa da Catalans.
Barcelona za ta sayar kafin su saye, amma ta ci gaba da kasancewa da kwarin gwiwar cewa za su iya kulla yarjejeniya da kungiyar ta Serie A.
Barcelona "ta baiwa dan wasan Arsenal Philippe Coutinho damar canja sheka ga dan wasan tsakiya Guendouzi" yayin da Gunners ke kokarin kashe dan wasan tsakiya
Mutane 200 da suka kashe gobara sun mayar da martani ga cinnawa Karen wuta a kwarin Jurupa - CBS Los Angeles
JURUPA VALLEY (CBSLA) - Wata gobara daji ta tashi a ranar Asabar da yamma a kwarin Jurupa, lamarin da ya kai ga mayar da martani ga masu kashe gobara sama da 200.
An bayar da rahoton gobarar ta Karen ne bayan karfe 3 na yamma a kan titin Sierra Avenue da Karen Lane.
Wutar ta karu ne daga kimanin eka 5-10 zuwa wajen eka 250 tun daga karfe 8 na yamma.
A karshe binciken ya kasance a 50% da kuma 225 kashe gobara daga Cal Fire, Riverside County Fire Department, City of Corona Fire Department, da kuma San Bernardino County gobara sun kasance a wurin fama da wuta.
An dakatar da ci gaba a kan wutar amma ana sa ran albarkatun za su ci gaba da kasancewa a cikin dare don lura da yanayin.
Babu rahoton raunuka ko lalacewar tsarin, kuma ba a ba da umarnin kwashewa ba.
An rufe titin Sierra tsakanin Armstrong da layin gundumar San Bernardino.
Babban jami'in Majalisar Dinkin Duniya ya kauracewa ziyarar Pakistan, yana mai ambaton batun jirgin
ISLAMABAD (AP) - Shugaban Majalisar Dinkin Duniya mai shigowa ya sanar a ranar Lahadi cewa ya dage ziyarar da ya shirya kaiwa kasar Pakistan "saboda wasu matsalolin jirgin sama na fasaha."
An zabi jami'in diplomasiyyar Turkiyya Volkan Bozkir a matsayin shugaban babban taron Majalisar Dinkin Duniya karo na 75 a watan da ya gabata kuma an shirya zai isa birnin Islamabad a ranar Lahadi.
Amma a wani sakon da ya wallafa a shafinsa na sada zumunta na Twitter, ya ce ziyarar da zai kai babban birnin kasar ta Pakistan za ta dakata.
Ministan harkokin waje na kasar Pakistan Shah Mahmood Qureshi ya mayar da martani ga Bozkir yana mai cewa "Ina fatan in marabce ku zuwa kasar Pakistan nan ba da jimawa ba don kyakkyawar ziyara mai cike da albarka."
A ranar da ta gabata, wani mai farin ciki Qureshi, yayin da yake sanar da ziyarar, ya yi fatan zai tattauna batutuwa daban-daban da Bozkir, ciki har da Kashmir, wanda ya rabu tsakanin Pakistan da Indiya mai makwabtaka da kuma ikirarin dukkanin su.
Pakistan da Indiya sun yi yaƙe-yaƙe biyu daga cikin yaƙe-yaƙensu uku a kan yankin da ke fama da rigingimu tun bayan samun ƴancin kai daga mulkin Birtaniya a 1947.
Bangarorin biyu sukan yi musayar wuta a Kashmir, lamarin da ya yi sanadin mutuwar sojoji da fararen hula a bangarorin biyu.
Pakistan na son Majalisar Dinkin Duniya ta taka rawarta wajen magance matsalar Kashmir a karkashin shawarwarinta ta hanyar barin mutanen da ke zaune a yankin Himalaya su yanke shawarar ko suna son hadewa da Indiya, da Pakistan ko kuma su fi son 'yancin kai.
'Me ya faru a wurin?!'
Jirgin yakin UFC Correia ya yi kamari bayan ya juya baya ga abokin hamayyarsa cikin kuskure yana tunanin zagaye ya ƙare (VIDEO) - RT Sport News
'Yar Brazil mai nauyin Bantamweight Bethe Correia tsohuwar 'yar wasan UFC ce amma ta yi kuskure ta hanyar juya wa abokiyar hamayyarta Pannie Kianzad baya ta kuma yi kuskuren tunanin zagayen da aka yi a fafatawar da suka yi a tsibirin Fight Island, kuma ta samu tagomashi sakamakon haka.
A karshen jerin wasannin farko na wasan kwaikwayon da suka yi a kan katin a Abu Dhabi, Correia mai shekara 37 ta bayyana cewa ta yi kuskuren gargadi na 10 na biyu game da ainihin karshen zagayen, inda ta kai ga safar hannu kafin ta juya wa Kianzad baya kuma ta koma kusurwarta.
'Yar gwagwarmayar kasar Sweden ta yi jari-hujja ba tare da bata lokaci ba, inda ta alakanta abokiyar hamayyarta da hannun dama kafin ta biyo bayan jerin bugun da ta yi na mayar da Correia a kan keji.
A wani lokaci da ya bayyana a cikin hatsari, dan Brazil ya sake karbar iko don hana barazanar kuma ya mayar da Kianzad sama kafin a kira ainihin karshen zagayen.
"Me ya faru a wurin? Oh maganata," an ji tawagar masu sharhi a kan ESPN+ suna ta furtawa.
Sai dai wani bangare ne na wani abin takaici a daren ga tsohuwar mai kalubalantar gasar Bantamweight Correia, wacce ta yanke hukuncin daurin talala wacce ita ce rashin nasararta ta uku a wasanninta hudu da suka gabata kuma ta bar bajinta na gaba daya da kashi 11,5 tare da samun nasara daya.
Ga 'yar kasar Iran da haihuwa Kianzad mai shekara 28, nasara ce ta biyu bayan nasarar da ta samu a kan Jessica-Rose Clark a UFC Fight Night a Moscow a watan Nuwamba.
Kianzad a yanzu ita ce ta 13-5 a gaba daya da kuma 2-1 a UFC, kamar yadda matar da aka fi sani da 'Banzai' ke da niyyar sauyawa a matsayin naira 135.
A wani wuri a cikin dare, Robert Whittaker na Australia ya fitar da Darren Till na Ingila a babban taron nauyi na tsakiya, yayin da dan wasan da aka haifa a Rasha Khamzat Chimaev ya yi tarihi ta hanyar samun nasara a karo na biyu a cikin kwanaki 10 a tsibirin Fight Island, mafi karancin lokaci tsakanin nasarori a UFC na zamani.
Watford ta fice daga gasar Premier yayin da Aubameyang ya ci wa Arsenal kwallo
Wasu daga cikin 'yan wasan Watford sun nutse a gwiwarsu; wasu kuma sun yi wa rami ba tare da wani lokaci ba.
Dan kwallon ya cika shekaru biyar da suka yi a gasar Firimiya kuma babu wanda zai iya cewa, a lokacin da lamarin ya bukace su da su jefa kwanon dafa abinci a Arsenal, sai suka sauka babu kakkautawa.
Wannan wani wasan kwaikwayo ne da ke cike da tsattsauran ra'ayi, gaggawa da kuma zalunci da suka nuna mafi kyawun ayyukansu a cikin rabin shekaru goma da suka gabata, amma ya zo da makara, kamar yadda fadace-fadacen da suka yi kusan gyara kasafin kudi na uku a ranar.
Da a ce Emiliano Martínez bai ceto dan wasan baya na Danny Welbeck minti 16 daga lokaci ba, jim kadan bayan da tsohon abokin wasansa ya shigo ya saka Watford cikin kwallaye biyu na aminci, da akwai duk wata dama da za su iya kammala komawa baya na tsawon shekaru.
A karshe sun yi kasa a gwiwa kuma manajan mai kula da su, Hayden Mullins, na iya nuna cewa ba za a taba mika masa wannan aikin da ya fi dacewa ba idan kungiyarsa ta nuna aikace-aikacen da aka yi daidai da su a baya.
A tsawon lokacin ba su da kyau, amma kuma ba su da kungiyar da ke dauke da su.
Wata gwagwarmayar talakawa ba za ta iya lalata daular ba, amma kuma tushen da iyalin Pozzo suka kafa ba su ba da kowane irin tabbacin cewa za su koma sama daga mataki na biyu.
Yana da wuya a gujewa ma'anar cewa dabi'ar Watford na fitar da manajoji ta gudu daga hanya.
Sakonsu na gaba na dindindin - watakila a ma'ana mafi sauki - zai zama na 12 a cikin shekaru takwas kuma akwai iska mai yawa da sabon tsintsiya zai iya shigowa.
Troy Deeney ya fuskanci komawa ƙaura duk da cewa ya shiga takaddama a Emirates.
'Yan wasan za su tashi, Ismaïla Sarr ya sake nunawa a nan cewa ya kamata a gane cewa zai buga gasar kwallon kafa ta Championship a watan Satumba, kuma ya kamata a ba shi fifiko.
Babu wani abu da ya yi tsayin daka game da takaddamar da aka yi a wata gamuwa da Mikel Arteta da aka bayyana a matsayin "wasan kwallon kwando" duk da cewa hakan ya haifar da nishaɗi mai kyau.
Arteta ya ce daga bisani dan wasan gaba na Watford ya yi "fashe-fashe", ko da yake ya yi saurin bayyana cewa a matsayin kalmar kwallon kafa na "wasan kwaikwayo, kasancewa a gaba."
Babu shakka sun bukaci: duk wata shawara da wani batu na fadace-fadace mai yiwuwa a karshe ya cika da sauri kuma suna iya mamakin yadda abubuwa za su faru idan ba a tilasta musu su yi wasa da kama-karya ba.
A maimakon haka sun yarda da hukunci kusan nan da nan.
Craig Dawson ya yi kunnen uwar shegu da Alexandre Lacazette a cikin dakika 40 amma ya dauki VAR kusan minti uku kafin ya samu kwarin gwiwar bayar da kyautar bugun fenariti, wanda Pierre-Emerick Aubameyang ya aika ba tare da bata lokaci ba.
Watford ta tattara kansu don dannawa, tare da Sarr a cikin wutar lantarki a dama, kuma ya zo kusa da Roberto Pereyra da Troy Deeney.
Amma sai Aubameyang ya zura kwallo a ragar Kieran Tierney a karo na biyu, kuma a lokacin da aka dawo hutun shan giya na farko, wasan ya yi ban mamaki sosai har Arteta shi ne manajan da ya ragargaji 'yan wasansa duk da cewa Arsenal ta samu nasara.
Bayan haka Aubameyang ya sarrafa dogon kwallon da Tierney ya jefa kuma ya maida wani kyakkyawan kwallo na sama wanda ya sa ya zura kwallo daya a raga, lambar yabo da zai raba wa Jamie Vardy idan Ben Foster bai toshe wata dama ta karshe ba a kusa da karshen.
Watford ya fito ya yi domin amma sun jure kuma, bayan da David Luiz ya sake fitar da wani kalubale na hukuncin kisa ga album a Welbeck, Deeney ya rammala a kansa hukuncin kafin a tafi hutu.
Deeney, yana tafiya ya ji rauni a yawancin lokacin, ya kwashe kansa a kusa da filin kuma yana cikin yanayin gladiator a ko'ina.
Wataƙila ya yi watsi da damar da Adam Masina ya rasa a farkon lokaci na biyu kuma an ci gaba da buɗewa.
Kyakkyawan Martínez, wanda Arteta ya tabbatar da cewa zai fara wasan karshe na gasar cin kofin FA a ranar Asabar, sannan kuma ya sami dukkanin filayen wasa na Watford a kan ƙafafunsu a lokacin da ya sauya gicciye daga Sarr.
Amma burin Watford ya ragu lokacin da aka kawar da kokarinsa na gaba kuma binciken rai, daga sama zuwa kasa, zai bukaci ya yi yawa.
Jikin uwa, jarirai 2 da aka samu a cikin mota da ke cikin tafki
AUGUSTA, Ga. - Hukumomi sun ciro wata motar da ke cikin ruwa daga wani tafkin Georgia kuma sun gano gawar wata mata da tagwayenta 'ya'yanta 'yan watanni 10 a ciki.
Ofishin Sheriff na Gundumar Richmond ya ce ma'aikatan sun gano motar a cikin magajin gari a watan Augusta a ranar Juma'a da yamma, jaridar Augusta Chronicle ta ruwaito.
Coroner Mark Bowen ya ce dukkanin wadanda suka mutu sun mutu a wurin.
Hukumomi sun gano gawarwakin a matsayin Shaquia Philpot mai shekara 25 da kuma 'ya'yanta Caysen da Cassius Williams.
Jami'ai ba su fitar da cikakken bayani game da yadda iyalin suka ƙare a tafkin ba.
Wani shaida, wanda ke kamun kifi a yankin, ya gano motar, in ji Bowen.
Za a aika da gawarwakin zuwa ofishin bincike na Georgia don binciken.
Ana ci gaba da gudanar da bincike kan shari'ar.
Mutumin da aka samu da raunukan harbin bindiga a Mambourin kusa da Werribee
An garzaya da wani mutum asibiti bayan an harbe shi a yammacin Melbourne cikin dare.
An kira 'yan sanda zuwa Mambourin, kusa da Werribee, da misalin karfe 8 na dare inda suka tarar da wani mutum mai shekaru 20 da haihuwa da ake zargi da raunukan harbin bindiga a kasan jikinsa a Yard St.
An kai mutumin asibiti tare da jikkata wadanda ba su da rai.
'Yan sanda sun ce ana ci gaba da bincike.
Kamfanonin tallace-tallace na tura rangwame daga filayen jiragen sama, majalisa
OOh! Kafofin watsa labarai sun tara jari a farkon wannan shekarar don samar da ƙarin tabbacin kudi yayin da annobar ta fara lalata masu tallace-tallace.
Sources ya ce, kamfanonin suna tattauna hanyoyin da za su iya magance yawan raguwar da aka samu ta hanyar rage kudin haya ga wuraren da suke aiki ko kuma ta hanyar cirewa ko rage garanti na kudaden shiga mafi karanci, wanda yawanci ana gabatar da shi ne lokacin da aka fara rattaba hannu kan yarjejeniyar.
Wata majiya ta nuna cewa mai yiwuwa manyan kamfanonin tallace-tallace sun ba da tabbacin kashi 85 cikin 100 na tsinkayen kudaden da suke samu a hayar.
Wasu kwangilolin suna da maganganun da ke ba su damar rage karancin lamunin idan yawan mutanen da ke wani yanki ya ragu da wani kaso, amma ba a sani ba ko wannan yanayin yana cikin kowane irin kwangilar da ke tsakanin kamfanonin tallafin da masu gidajen su.
A lokaci guda, kamfanonin suna ba da rangwame mai yawa ga masu tallace-tallace don cika wuraren da ake da su a kan allon talla da kuma ba su kudi mafi daraja.
Gidajen tallace-tallace a Sydney CBD da kuma unguwannin waje waɗanda yawanci ke karɓar tallace-tallace guda shida suna fama don cika dukkanin wuraren da ake da su.
Amma an kyautata wasu shafuka - kamar su allon tallace-tallace na kafofin watsa labarai na mita 40 x 10 a filin jirgin saman Sydney.
OOh! 'Yan jarida sun ki yin tsokaci, amma a wani taro da suka yi a Macquarie Australia a watan Mayu, sun ba da tutar fiye da dala miliyan 20 na ajiyar kuɗin haya.
JC Decaux ya ki yin sharhi.
Filayen jiragen sama da zirga-zirgar jama'a kwangilar tallace-tallace ne na kamfanonin talla.
A cewar rahoton kungiyar 'yan jarida na waje na shekarar 2019, kudaden shiga daga sufuri - ciki har da filayen jiragen sama - ya kai dala miliyan 169.4 yayin da kudaden shiga daga kayan titi da waje na motocin bas da motoci ya kai dala miliyan 266.5.
Kasuwancin JC Decaux yana da kwangila tare da filin jirgin saman Sydney, Yarra Trams, filin jirgin saman Perth da kuma Sydney Buses. OOh! Media yana da allon tallace-tallace a wurare kamar wuraren shakatawa na Qantas, a wajen filin jirgin sama na Sydney, filin jirgin saman Adelaide, filin jirgin saman Darwin da kuma tashoshin jirgin kasa a Sydney da Melbourne.
An yi awon gaba da filin jirgin saman Melbourne da jiragen kasa na Sydney a lokacin annobar kuma ba a yanke hukunci a hukumance ba.
Melbourne ita ce kwangila ta biyu mafi girma a filin jirgin sama a Australiya kuma riga-kafin cutar coronavirus ya kai miliyoyin miliyoyi a kowace shekara.
A sakamako na cikakken shekara a watan Fabrairu, oOh! Media ya ce ya samar da dala miliyan 65.9 daga nau'in 'fly' wanda yawanci ya kunshi kudaden shiga daga filin jirgin saman Sydney.
Kudaden da aka samu daga 'commute', wanda ya ƙunshi kwangilar layin dogo da kayan titi da Adshel ya mallaka a baya kafin a saye shi ta hanyar oOh!, ya kai dala miliyan 234.8.
JC Decaux Australia ta samu kudin shiga dala miliyan 37.7 daga sufuri a shekarar 2018, bisa ga sakamakon kudi na shekarar 2018 da ta shigar ga Hukumar Kasuwanci da Zuba Jari ta Australiya.
To amma dukkanin wadannan adadi za su iya raguwa sosai a wannan shekarar.
Alkaluman jaridar Standard Media Index, wadanda suka bayar da rahoton kashe kudade hudu daga cikin manyan kungiyoyin talla biyar, sun ce kasuwar tallace-tallace ta waje ta karu da kashi 68 cikin 100 a watan Yuni.
Ta hanyar kwatanta, sakamakon wucin gadi na watan Yuni ya nuna cewa kashe kuɗi na dijital ya ragu kashi 37 cikin dari, yayin da rediyo na birni ya fadi kashi 48 cikin dari.
Gidan talabijin na birni ya fadi kashi 34 cikin 100 a watan Yuni, yawan kuɗin jarida ya ragu da kashi 49 cikin 100 kuma yawan kuɗin da ake kashewa a mujallu ya ragu kashi 66 cikin 100.
Leicester na farin cikin samun gurbi a gasar kwallon kafa ta Turai in ji Jamie Vardy wanda ya lashe gasar Golden Boot
Jamie Vardy ya yarda da rashin jin dadinsa na rashin samun gurbi a gasar kwallon kafa ta Champions League, amma ya ce Leicester City ta cimma burinsu na farkon kakar wasanni na neman cancantar shiga gasar Turai.
Foxes sun kasance na biyu a watan Disamba kuma na uku a lokacin da aka sake fara kwallon kafa bayan kullewa, amma sun dauki maki hudu ne kawai daga wasanni biyar da suka gabata don kammalawa na biyar a gasar ta Premier.
Nasarar da aka yi a ranar karshe a kan Manchester United za ta kai wasan daf da na kusa da na karshe, amma kungiyar Brendan Rodgers ta yi rashin nasara da ci 2-0, abin da Vardy ya ce shi ne abin da ya fi tayar da hankali.
"Ya kasance abin baƙin ciki, mafi yadda muka ƙare har rasa wasan," ya ce a kan Sky Sports a cikakken lokaci.
"Amma mun ce a dakin miya, mun yi niyya a bayan kofofin da aka rufe don mu cancanci zuwa Turai kuma mun yi hakan."
"Mun samu damar shiga gasar zakarun Turai kuma hakan ya fi kyau, amma za mu yi tunani a kan hakan kuma mu dawo da karfi a shekara mai zuwa."
"Yana da wuya a dauka, amma babban burinmu shi ne Turai kuma mun sami nasarar hakan."
Yayin da kungiyarsa ta yi kasa a gwiwa, Vardy da kansa ya kawo karshen kakar wasa ta bana a matsayin dan wasan da ke kan gaba a gasar ta Premier yana dan shekara 33, inda ya ci kwallo sau 23.
Ya jinjina wa abokan wasan kungiyarsa wajen karbar kyautar, ya kuma ce har yanzu akwai nisan mil da yawa a cikinsa a matakin sama, duk da cewa shekarunsa na cigaba.
"Na yi farin ciki, duk game da kungiyar ne, da ban kasance a matsayin da nake da shi ba tare da su ba, kuma na ajiye wasu 'yan kaɗan."
"Zan ɗan huta yanzu kuma in dawo kakar wasa mai zuwa a shirye in tafi. Abin farin cikin shi ne cewa ba na jin shekarata, ƙafafuna suna da kyau kuma suna taɓa itace ba na ɗaukar rauni da yawa, don haka ya kamata in ci gaba da kasancewa a kan hakan kuma in dawo da karfi kamar yadda zan iya a shekara mai zuwa."
Coronavirus: Matafiya daga Spain sun ce a killace su
Matafiya da suka isa Burtaniya daga Spain dole ne a killace su na tsawon kwanaki 14, a karkashin sabbin dokokin tafiye-tafiye na coronavirus.
An sanar da su a ranar Asabar bayan karuwar wadanda suka kamu da cutar coronavirus a Spain, inda aka samu sabbin mutane sama da 900 da suka kamu da cutar a ranar Juma'a.
Jami'an Mutanen Espanya sun kuma yi gargadin cewa za a iya samun tashin hankali na biyu yayin da manyan birane suka ga karuwar cutar.
Kamfanonin jiragen sama da suka hada da British Airways sun zargi sabbin matakan a matsayin "duk da haka wani abin takaici" ga masu hutun Birtaniya.
Ma'aikatar sufuri ta shawarci mutanen da ke hutu a Spain da su bi dokokin yankin, su koma gida kamar yadda aka saba, kuma su duba shafin yanar gizon kula da tafiye-tafiye na ofishin harkokin waje don ƙarin bayani.
Ofishin Harkokin Wajen yana ba da shawara game da tafiye-tafiye masu mahimmanci zuwa babban yankin Spain, duk da haka matakan kebewa sun shafi waɗanda suka dawo daga babban yankin Spain, da Canary Islands da Balearic Islands, kamar Mallorca da Ibiza.
Shawarwarin ofishin harkokin waje yana da tasiri ga inshorar tafiye-tafiye.
Cikin wadanda sabbin dokokin suka shafa har da Sakataren sufuri Grant Shapps, wanda ya soma hutunsa a kasar Spain a ranar Asabar.
Ana sa ran zai ci gaba da tafiyarsa kamar yadda aka tsara kuma ya ware bisa jagorancin dawowarsa.
An fara gabatar da matakan killace matafiya a Burtaniya a farkon watan Yuni.
Amma bayan matsin lamba daga masana'antun sufurin jiragen sama da tafiye-tafiye, gwamnati da gwamnatocin da suka rage sun wallafa jerin sunayen kasashen da aka kebe daga dokokin.
Kamfanin jiragen sama na British Airways ya ce ya yi "bacin rai" game da sabbin sauye-sauye ga shawarwari da ka'idojin tafiye-tafiye na gwamnati, duk da cewa kamfanin jirgin ya ce jiragensa na ci gaba da aiki.
Ya ce wannan mataki shi ne "ya jefa dubban tsare-tsaren tafiye-tafiye na Britaniya cikin rikice-rikice."
Kungiyar masu kula da zirga-zirgar jiragen sama ta ce sabbin matakan za su ci gaba da lalata abin da ya riga ya zama wani gagarumin sake farawa a fannin sufurin jiragen sama wanda ke ci gaba da fuskantar babbar kalubale a tarihinsa.
Babban kamfanin yawon shakatawa na Birtaniya, Tui, ya soke jiragensa saboda tashi zuwa babban yankin Spain da tsibirin Canary a ranar Lahadi.
Abokan ciniki a halin yanzu suna hutu za su iya dawowa a cikin jirgin da suka yi niyyar komawa gida.
Duk da haka, kamfanin jirgin sama na kasafin kudi EasyJet ya ce "abin baƙin ciki ne" kuma zai yi aiki da cikakken jadawalin a cikin kwanaki masu zuwa.
"Abokan ciniki da ba sa so su yi tafiye-tafiye za su iya canja wurin jiragen su ba tare da kudin canji ba ko kuma su karbi takardar shaidar darajar ajiyar," in ji kamfanin a cikin wata sanarwa.
Mai magana da yawun kungiyar jami'an kula da tafiye-tafiye na Birtaniya (Abta) ya ce canjin dokar killacewa ta gwamnati "abin baƙin ciki ne."
"Muna ba da shawarar gwamnati ta yi la'akari da cire ka'idojin killace jiragen da ke zuwa da kuma daga wasu yankuna da ke da karancin kamuwa da cutar, ko kuma zuwa wurare kamar tsibirin Balearic ko Canaries - waɗanda suka bambanta da babban yankin Spain - don kauce wa ƙarin lalacewar masana'antun yawon shakatawa na Burtaniya da ke shigowa da waje", in ji shi.
Ya zuwa yanzu kasar Spain ta samu mutuwar mutane sama da 28,000 da suka kamu da cutar coronavirus.
A ranar Alhamis, ta ga karuwar masu kamuwa da cutar a kowace rana tun lokacin da aka kawo karshen kullewarta.
Yankin na Catalonia ya zama wani yanki na baya-bayan nan da ya yi fama da tashe-tashen hankula.
Yankin arewa maso gabas mai arziki, wanda ke da gida a Barcelona, ya ba da umarnin rufe dukkanin wuraren shakatawa na tsawon makonni biyu tare da sanya dokar hana fita ta tsakar dare a mashaya a yankin Barcelona mai girma.
Guy Hedgecoe na BBC a Madrid ya ce yaduwar cutar a tsakanin matasa wani abin damuwa ne musamman yadda suke taruwa da yawa a birane da daddare.
Faransa ta gargadi 'yan kasarta da kada su yi balaguro zuwa Catalonia yayin da Norway ta ce za ta fara killace mutanen da ke zuwa daga Spain.
Gwamnati ta bukaci ma'aikata da su "fahimci wadanda suka dawo daga Spain wadanda yanzu za su bukaci su kebe kansu."
Amma sakataren gidauniyar Labour Nick Thomas-Symonds ya yi kira ga gwamnati da ta yi cikakken bayani kan yadda za ta tallafawa wadanda abin ya shafa, inda ya kara da cewa labarin zai kasance "na matukar damuwa ga iyalan da suka kama a Spain ko kuma suke shirin tafiye-tafiye."
Ministan farko na Scotland Nicola Sturgeon ya bayyana cewa an yanke wannan shawarar ne bayan da aka yi nazarin bayanan baya-bayan nan a ranar Asabar.
"Hakan ya ƙarfafa batun cewa waɗannan al'amura suna fuskantar sauye-sauye a takaice don haka shawarata ita ce in yi taka tsantsan game da tafiye-tafiye da ba su da muhimmanci a ƙasashen waje", in ji ta.
John Blackmore, daga Hampshire, saboda ya tashi zuwa iyalinsa a Spain tare da matarsa da kuma kananan yara biyu.
Amma sabbin dokokin na nufin dole ne ya soke, saboda tsoron cewa ma'aikaciyar matarsa ba za ta iya saukar da ita ba ta dauki karin makonni biyu don killacewa a lokacin da suka dawo.
Ya ce yana ganin ba zai yiwu su samu kudin fansar jirgin ba, saboda ba a soke shi ba.
"Na fatattake ni," ya shaida wa BBC.
"Ina da iyali a Spain waɗanda ba su ga jikokinsu kaɗai ba tun lokacin Kirsimeti."
Lois Stothard, daga Kudancin Yorkshire, ta shaida wa BBC cewa ta shirya hutun zuwa Sevilla a matsayin abin mamaki don ranar haihuwar saurayinta na 30 - saboda tashi daga ranar Lahadi da safe - amma yanzu tana jin cewa ba za ta iya tafiya ba.
"Ni ma'aikaciya ce - ni malama ce - kuma saurayina yana da sadaukarwar aiki don haka ba za mu iya killace kanmu na tsawon kwanaki 14 ba idan muka dawo," in ji ta.
"Ba za mu iya dawo da kuɗi ba kuma mu canza kamfanin yana so ya ninka abin da na riga na biya a cikin kudade.
Ina matukar baƙin ciki da damuwa yayin da muke cike da shirye-shiryen tafiya."
Ted Cruz ya ce manufofin Pelosi su ne "tatsar da tsabar kudi kan matsalar da kuma rufe Amurka"
Washington - Sanata Ted Cruz dan jam'iyyar Republican na Texas ya zargi kakakin majalisa Nancy Pelosi da 'yan jam'iyyar Democrats da tura wani kunshin kayan agaji na coronavirus wanda ya mayar da hankali kan "tatsar da tsabar kudi kan matsalar da kuma rufe Amurka" yayin da ake ci gaba da tattaunawa kan mataki na gaba.
A wata hira da ya yi da "Face the Nation" a ranar Lahadi, Cruz ya ce kasar na fuskantar rikice-rikice guda biyu a lokaci guda: annobar cutar da ta lakume rayukan mutane sama da 600,000 a duniya da kuma "hadarin tattalin arziki" a Amurka.
Amma Cruz ya ce Pelosi, wanda ya fito a kan "Face the Nation" a gaban sanata, "ba ya mai da hankali kan ko wanene ba."
"Manufofinta na girgiza tsabar kudi a matsalar da kuma rufe Amurka," in ji Texas Republican.
"Kuma musamman, ka kalli takardar kudi ta dala tiriliyan 3 da ta ke kokarin turawa, kawai tana tura wa kawayenta kudi ne ba tare da magance matsalar ba a zahiri. Manufarmu ita ce Amurkawa suna son komawa bakin aiki. Suna so su iya samar da iyalinsu."
'Yan Majalisar Republican da Fadar White House sun kwashe makon jiya suna tattaunawa kan sharuddan kashi na hudu na martanin coronavirus, wanda suke sa ran za su kashe dala tiriliyan 1.
A karshen mako, shugaban ma'aikatan fadar White House Mark Meadows da Sakataren Baitul Steven Mnuchin sun koma Capitol Hill don ƙarin tattaunawa da ma'aikatan majalisar dattijai, kuma Mnuchin ya fada wa Fox News a wata hira da aka yi a ranar Lahadi, an bayyana cikakkun bayanai daga Shugaban Majalisar Dattijai, Mitch McConnell a ranar Litinin.
Batun da ya fi daukar hankali ga 'yan majalisar dokoki - kuma wani batu na jayayya tsakanin 'yan Republican da 'yan Democrats - shi ne karewar karin albashi na rashin aikin yi, wanda ya fara gudana a wannan karshen mako.
Yayin da 'yan jam'iyyar Democrats ke son kunshin coronavirus na "lokaci na hudu" don kiyaye karuwar dala 600 ga amfanin, 'yan Republican suna kiran a dawo da shi tare da jayayya da cewa wasu Amurkawa sun fi samun karfi daga rashin aikin yi fiye da yadda suka yi a albashi.
Cruz ya ce fiye da rabin Amurkawa da ke karbar kyaututtukan rashin aikin yi ana biyan su fiye da lokacin da suke aiki kuma ya ce yana tattaunawa da kananan 'yan kasuwa a Texas wadanda ke fuskantar matsala wajen sake ma'aikata.
"Tabbas, ba za su dawo ba saboda gwamnatin tarayya tana biyan su, a wasu lokuta, sau biyu na kudin da za su zauna a gida," in ji shi.
Cruz ya ce kamata ya yi Majalisa ta mayar da hankali kan zartar da wata doka ta farfadowa da za ta sa Amurkawa su koma bakin aiki ta hanyar sassauta haraji da ka'idoji kan kananan kamfanoni: "maimakon kawai kawar da tiriliyan daga kofa, takardar dawo da kudin zai dakatar da harajin albashi, wanda zai ba da albashi ga duk wanda ke aiki a Amurka. Hakan ya sa mutane su koma aiki", in ji shi.
A makon da ya gabata ne shugaba Trump ya bukaci kunshin taimako na gaba da ya hada da yanke harajin albashi, amma Mnuchin ya ce ba zai kasance cikin dokar ba, saboda an samu karbuwa a tsakanin 'yan Republican.
Mista Trump ya yarda cewa yanke harajin albashi zai kasance ba tare da doka ta gaba ba amma ya nemi ya dora laifin kan 'yan jam'iyyar Democrats.
Cruz, wanda a makon da ya gabata ya ki amincewa da kudin kunshin na gaba, ya ce a ranar Lahadi ba ya cikin jirgin tare da matakin daga 'yan'uwansa 'yan Republican.
Amma kuma ya soki lissafin dala tiriliyan 3 da 'yan majalisar da ke rike da madafun iko na jam'iyyar Democrat suka zartar a watan Mayu, ya kuma zargi abokan hamayyarsa na siyasa da cewa da gangan suka kirkiro wani mataki na damfarar shugaban kasa gabanin zaben watan Nuwamba.
"Maƙasudin da 'yan jam'iyyar Democrats ke da shi kawai shi ne su yi nasara a kan Donald Trump, kuma sun yanke shawarar hanyar da ta fi dacewa wajen kayar da Donald Trump ita ce rufe duk wata kasuwanci a Amurka, rufe kowace makaranta a Amurka," in ji shi.
"Kun sani, Nancy Pelosi ta yi magana kan maza da mata masu aiki. Abin da ta ke gabatarwa shi ne hana maza da mata masu aiki daga aiki."
Rahul Gandhi Ya Jefi Mutane Kan Batun Rajasthan
Rahul Gandhi na majalisa ya wallafa wani bidiyo a yau yana ƙoƙarin yaɗa jama'a a kan jam'iyyar BJP kan abubuwan da suka faru a Rajasthan.
Amfani da hashtag #SpeakUpForDemocracy, sakonsa na Hindia ya bukaci jama'a da su "haɗa kai da kuma ɗaga muryarmu ga dimokuradiyya."
Majalisa na shirin gudanar da zanga-zanga a karkara a ranar Litinin kan halin da ake ciki a Rajasthan, inda gwamnatin Ashok Gehlot ke fama da tsira.
Yayin da jam'iyyar ta ce za a gudanar da zanga-zanga a wajen Rashtrapati Bhavan, mazaunin shugaban kasa Ram Nath Kovind.
A cikin bidiyon, Majalisa ta zargi BJP da "karkatar da kundin tsarin mulki da kuma rushe dimokuradiyya" yayin da kasar baki daya ke yaki da cutar coronavirus.
Haka ya yi a Madhya Pradesh, in ji Majalisa.
"Mun bukaci nan da nan a gudanar da zaman majalisa wanda ke cikin hakkokinmu na tsarin mulki," in ji jam'iyyar a cikin bidiyon.
Gwamnan Rajasthan Kalraj Mishra ya karyata shawarar daya gabatar na fara zaman majalisa.
An gabatar da na biyu a yau wanda ya ce yana nazari.
Gwamnatin Mr Gehlot ta shiga cikin rikice-rikice mai zurfi bayan da mataimakinsa Sachin Pilot ya mayar da 'yan tawaye tare da wasu 'yan gwagwarmaya da ke goyon bayansa.
Jam'iyyar ba ta iya rabuwa da 'yan tawayen don saukar da alamar mafi yawa a cikin taron.
Mista Pilot - wanda aka kwace mukaminsa a jam'iyyar da kuma gwamnati - ya samu sauƙi na ɗan lokaci daga rashin cancanta daga babbar kotun Rajasthan, wacce ta ce Kakakin ba zai iya ɗaukar mataki ba har sai an yanke hukunci kan babbar tambaya ta tsarin mulki game da ikonsa.
A gobe ne Kotun Koli za ta karbi wannan tambaya, wacce kuma za ta yanke hukuncin ko wata kotu za ta iya tsoma baki cikin hukuncin da Kakakin ya yanke.
Majalisa ce kadai ta wuce alamar mafi rinjaye a taron mai mambobi 200.
Kungiyar Pilot ta yi ikirarin goyon bayan 30 MLAs, amma ya zuwa yanzu, shaidar ta nuna cewa 19 ne kawai.
BJP tana da 72 kuma ciki har da masõya da 'yancin kai, tana tsaye a 97.
Idan kotu ta yanke shawarar goyon bayan Mista Pilot, Majalisa za ta iya rasa na biyu daga cikin gwamnatoci uku da ta kafa a jihohin tsakiyar kasar bayan zaben 'yan majalisa na 2018.
A watan Maris, ta rasa gwamnatin Kamal Nath a Madhya Pradesh bayan da Jyotiraditya Scindia ya koma jam'iyyar BJP tare da 22 daga cikin 'yan majalisarsa.
An kama jami'an 'yan sandan Kenyan bayan harbi mai tsanani a Garissa
An kama jami'an 'yan sanda biyu a Kenya dangane da wani harbi da aka yi inda aka kashe mutane biyu.
Wannan harbi ya faru ne a kasuwar Soko Ng'ombe da ke gabashin gundumar Garissa a ranar Asabar, yayin zanga-zangar nuna adawa da kama wani mutum da ake zargi da kisan kai.
An bayyana sunan wadanda suka mutu a matsayin Aden Abdi Madobe da kuma Muhiyadin Adow Shibin.
'Yan sandan kasar Kenya sun kaddamar da bincike kan harbin.
Zai hada da "binciken bincike" na bindigogi na jami'an.
Garissa MP Aden Duale ya kira mace-macen "mutuwa" kuma ya yi la'akari da " zaluncin 'yan sanda" a cikin wata sanarwa da aka sanya a Facebook.
Masu zanga-zangar sun nuna damuwa game da 'yan sanda a lokacin annobar.
A cewar Amnesty International, jami'an Kenyan sun kashe mutane 21 tun daga watan Maris saboda rashin bin matakan kariya daga cutar Koronabirus kamar dokar hana fita da kuma sanya takunkumin rufe fuska.
A farkon wannan watan 'yan sanda a babban birnin Nairobi sun harba gas mai sa hawaye kuma sun kama masu zanga-zanga da dama da suka shiga zanga-zangar Saba Saba na shekara-shekara - wani zanga-zangar da aka fara shekaru 30 da suka gabata a kan mulkin mallaka na shugaban kasa Daniel arap Moi.
Masu aiko da rahotanni sun ce abin da ya faru a wannan shekarar ya samu karin karfi ne ta hanyar fushi kan hargitsin da 'yan sanda suka yi a lokacin kullewar Covid-19.
Shivraj Singh Chouhan Na Gwajin Covid Mai Kyau
Babban Ministan Madhya Pradesh Shivraj Singh Chouhan, wanda a ranar Asabar ya tabbatar da cewa ya yi gwajin cutar COVID-19, ya yaba a ranar Lahadi da safe don ya ce yana da "kyau" kuma ya yaba wa ma'aikatan gaba-gaba a yakin da ake yi da cutar coronavirus.
Babban Ministan ya kuma maimaita gargadin da ya yi daga jiya, lokacin da ya bukaci mutane da su bi ka'idoji, kamar nisantar jama'a da kuma amfani da takunkumin fuska.
"Ina da kyau, abokaina. sadaukar da kai na mayaƙan coronavirus, waɗanda suka sadaukar da rayukansu cikin haɗari, abin yabo ne. Ina sarautar dukkanin mayaƙan coronavirus na jihar", Mr Chouhan ya aiko da rahoto daga asibitin Chirayu na Bhopal, inda aka shigar da shi a jiya.
"Ku nisan mita biyu, ku wanke hannuwanku akai-akai kuma ku sanya takunkumin fuska - wadannan su ne manyan makaman da muke da su don kauce wa cutar Koronabirus. Ina kira ga dukkan mutane - ku yi amfani da wadannan makamai don kanku da kuma masoyanku", in ji shi.
"Dukkanku ku yi taka tsantsan, ku zauna lafiya lafiya, wannan shi ne abin da nake addu'a ga Allah" Mista Chouhan ya kara da cewa.
A ranar Asabar Mista Chouhan ya bayar da rahoton cewa ya yi gwajin cutar duk da kokarin da ya yi na kauce wa kamuwa da cutar kuma ya yi gargadin cewa "kamar rashin kulawa ne kawai ke gayyatar cutar coronavirus."
Da yake zantawa da manema labarai a safiyar yau Mr Chouhan ya ce duk da barazanar kamuwa da cutar "babu bukatar fargaba" ya kuma bukaci wadanda ke nuna alamun cutar da su yiwa kansu gwaji.
"Idan ka kamu da cutar, babu bukatar ka ji tsoro. Kada ka ɓoye alamun cutar amma ka gaya wa likitoci nan da nan, don haka za a iya fara magani.
Madhya Pradesh na da mutane kusan 27,000 da suka kamu da cutar COVID-19, daga cikinsu sama da 7,600 na aiki sannan 799 na mutuwa da ke da nasaba da kwayar cutar.
Indiya ta samu karuwar wadanda suka kamu da cutar COVID-19 a cikin makonnin da suka gabata, inda aka gano sabbin kamuwa da cutar sama da 45,000 a kowace rana tun daga ranar 23 ga watan Yuli.
Adadin wadanda aka tabbatar sun kamu da cutar coronavirus ya kusan kai 14 lakh; daga cikin wadannan sama da 4.67 lakh sun kamu da cutar kuma sama da 32,000 sun mutu da ke da alaƙa da kwayar cutar.
Karuwar wadanda suka kamu da cutar, wanda ya yi daidai da sassauta ka'idojin kulle a yankunan da ba su da matsuguni a kasar, ya sa Indiya ta zama ta uku a jerin kasashen da cutar ta fi shafa.
Sai dai Amurka (41.78 wadanda suka kamu da cutar) da Brazil (23.94 wadanda suka kamu da cutar) sun fi muni.
Ministan cikin gida na Tunisiya ya kira sabon PM, da zai kafa gwamnati a cikin wata guda
An nada ministan cikin gida na Tunusiya Hichem Mechichi don kafa gwamnati ta gaba, in ji ofishin shugaban kasar, a tsakiyar tashin hankalin siyasa tsakanin manyan jam'iyyu a arewacin Afirka.
Lauyan mai shekaru 46 ya maye gurbin Elyes Fakhfakh, wanda ya yi murabus a matsayin firayim minista a farkon watan nan.
Amma Mechichi ba ya daga cikin sunayen da jam'iyyun siyasar da ke mulki suka gabatar wa shugaba Kais Saied.
A cikin wata sanarwa bayan sanarwar ranar Asabar, Mechichi ya ce zai "yi aiki don samar da gwamnatin da ta dace da tsammanin dukkanin 'yan Tunisiya."
An yabawa Tunisiya a matsayin wani labari mai wuya na samun nasara ga sauyin mulki na dimokuradiyya bayan tashin hankalin yankin bazara na Larabawa wanda ya haifar da juyin juya halin da ta yi a shekarar 2011.
Amma shugabanninta sun yi kokarin cika tsammanin al'ummar Tunisiya kuma tattalin arzikin da ya riga ya yi kasa a gwiwa sakamakon rufe iyakokin kasar saboda annobar COVID-19.
Cutar ta kashe mutane kusan 50 kuma ta kama sama da 1,400 a Tunisiya.
Tare da kasancewa ministan cikin gida a gwamnatin mai barin gado, Mechichi ya kasance mai bai wa shugaba Saied shawara kan harkokin shari'a.
A baya ya kasance shugaban ma'aikata a ma'aikatar sufuri kuma ya yi aiki a ma'aikatar kula da harkokin jama'a.
Yanzu yana da wata guda da zai kafa gwamnati, wacce a lokacin za ta fuskanci kuri'ar amincewa da majalisar dokoki kuma za ta bukaci cikakken rinjaye don samun nasara.
Idan ba haka ba, za a rushe majalisar kuma za a gudanar da sabon zabe cikin watanni uku.
A zaben da ya gabata da aka yi a watan Oktoba, jam'iyyar Ennahdha ta zo kan gaba amma ta kasa da yawancin mutane kuma daga bisani ta amince ta shiga gwamnatin hadin gwiwa.
Fakhfakh ya yi murabus a ranar 15 ga watan Yuli, bayan kasa da watanni biyar a ofis, ya yi barazanar sake barkewar siyasa a kasar yayin da yake fama da faɗuwar tattalin arziki na annobar.
Murabus din ya zurfafa jayayyar siyasa da Ennahdha kan zargin da ake yi wa Fakhfakh na rikice-rikice na ban sha'awa.
Dangantaka tsakanin shugaban mai shekaru 47 da haihuwa da Ennahdha ta yi tsami tun bayan zaben 'yan majalisar dokoki na watan Oktoba.
Fakhfakh ya sauka a ranar da jam'iyyar ta shigar da karar rashin amincewa da shi.
Tun da farko Ennahdha ya zabi firaminista mai zaman kansa, amma ya kasa samun goyon bayan majalisa, wanda hakan ya sa shugaban kasar ya sanya sunan tsohon ministan kudi Fakhfakh a matsayin mukaddashin.
Fuskantar tsammanin za a gudanar da sabon zabe, daga bisani Ennahdha ya amince ya shiga cikin gwamnatin hadin gwiwa.
Mota na tafiyar da jama'a, mai zanga-zanga ya harbe a Colorado
AURORA, Colo. (AP) - Wata mota ta kutsa cikin taron jama'a kuma an harbi wani mai zanga-zanga a unguwar Denver da ke Aurora a lokacin da ake zanga-zangar adawa da rashin adalcin launin fata.
Ma'aikatar 'yan sanda ta Aurora ta bayyana a Twitter cewa masu zanga-zangar suna tafiya a kan babbar hanyar 225 a ranar Asabar lokacin da wata mota ta ratsa.
'Yan sanda sun ce wani mai zanga-zanga ya harba wani makami, inda ya bugi akalla mutum guda da aka kai shi asibiti cikin yanayi mai karko.
Hukumomi sun ce an tura motar kuma suna bincike.
Masu zanga-zangar sun kuma fasa tagogi zuwa gidan kotu sannan aka soma cinna wuta a wani ofishi, in ji 'yan sanda.
An kaddamar da wani taro ba bisa ka'ida ba kuma 'yan sanda sun umarci masu zanga-zangar da su bar yankin, in ji hukumomi.
An kara samun tashe-tashen hankula a zanga-zangar da aka yi a baya-bayan nan kan rashin adalcin launin fata tun bayan da aka tura jami'an gwamnatin tarayya domin dakile zanga-zanga a Portland, Oregon.
'Yan sanda sun bayyana tashin hankali a Seattle a ranar Asabar.
Zanga-zangar da ta haifar da mutuwar George Floyd a ranar 25 ga watan Mayu, wani bakar fata a Minnesota wanda ya mutu bayan da wani jami'in farar fata ya rike shi a kasa tare da gwiwa a wuyansa, sun kuma nuna wasu lokuta na mummunan tashin hankali na 'yan sanda.
A jihar Colorado, masu zanga-zanga sun ja hankali kan mutuwar Elijah McClain, wanda 'yan sanda suka dakatar da shi a lokacin da yake tafiya a kan titin Aurora a watan Agusta na shekarar 2019 bayan da wani mai kira 911 ya ba da rahoton cewa yana da zargi.
'Yan sanda sun ajiye shi a wani wurin shakatawa, kuma ma'aikatan kiwon lafiya sun ba da gudummawar ketamine mai nauyin mil 500, don kwantar da hankalinsa.
Ya shiga bugun zuciya, daga baya aka bayyana cewa kwakwalwa ta mutu kuma aka cire shi daga tallafin rayuwa.
Canjin yanayi ya gurbata tafkin Tahoe da ya shahara a bayyane
South Lake Tahoe, California - Duk da annobar, har a ranar mako guda, har yanzu mutane suna cunkoso a bakin tekun Paparoma a tafkin Tahoe.
"Ina son yin zango da hawa keke da kuma yin iyo a tafkin," in ji wata yarinya mai suna Dakota.
"Wannan wani kyakkyawan abu ne da kowa ke son ziyarta," a cewar Emerica Benitas.
Wannan shi ne dalilin da ya sa harkokin kasuwancin ruwa na Matt Meunier ke ci gaba da karfi, har ma a cikin annoba.
Ya ce yana ganin "abin ban mamaki. Tafkin Tahoe shi ne tafki mafi tsabta, mafi ban mamaki, ina tsammanin, a kasar nan."
Yanzu mummunan labari: Tafkin Tahoe ba shi da tsabta, ba a bayyane ba, kamar yadda ya kasance a lokacin da ya koma nan sama da shekaru biyu da suka gabata.
"Abin da muke lura da shi da yawa ya sauka a kan duwatsu," in ji Meunier.
"Kana samun wannan algae mai ban mamaki a kan duwatsu."
Canjin yanayi, masana kimiyya sun yi imanin cewa, ya shafi zafin ruwa da haka, haske.
Kuma mutane miliyan 15 ne ke ziyartar tafkin a duk shekara - tare da shara da suke fita.
Meunier ya ce tafiye-tafiye na ruwa don tsabtace kasan tafkin ya sami tsohuwar shara.
"Kuma idan na ce tsohon shara, ina nufin '60s, '70s," in ji Meunier.
"Gwani na giya, gwangwani na soda, gwangwani na coci daga zamanin dā."
Masana kimiyya suna lura da tsabtace tafkin Tahoe a kowace shekara ta hanyar sauke farin faifai, sannan su auna yadda za su iya ganin sa.
Farfesa Geoff Schladow na UC Davis ya ce "muhimmin alama ce ta yadda tafkin yake da lafiya."
Lokacin da aka auna shi a shekarar da ta gabata, tsabtace tafkin ya kai kimanin kafa 80.
Wannan yana nufin za ka iya ganin cewa Disc 80 feet saukar.
Amma, ka yi la'akari da wannan, kimanin shekaru 20 da suka wuce, tsabtace tafkin ya kai kafa 100.
Wannan shine yanayin da masana kimiyya ke kokarin juyawa.
Amma suna yaki da tasirin sauyin yanayi, ci gaban da ke kewaye da tafkin da kuma wani abu da aka kara a tafkin a shekarun 1960: Kananan jatan lande masu cutarwa da aka shigo da su don ciyar da kifin.
Bai yi aiki ba.
"Da zarar jatan lande ya shigo, ba zato ba tsammani babu masu tsabta a cikin tafkin," in ji Schladow.
Irin wadannan kalubale na fuskantar tafkuna da jikin ruwa a fadin duniya.
"Darasi a nan shi ne, idan ba za ka iya yi a Tahoe ba, to, wane fata ne ake da shi ga dukkanin koguna da bakin teku, da koguna da tafkuna a fadin kasar da ba za su taba samun irin wannan kulawa ba, da irin wadannan albarkatu?" in ji Schladow.
Meunier ya ce yana da "fatan alheri" saboda "idan akwai ruwan azurfa na annobarmu, ina tsammanin hakan ya nuna cewa yanayi zai dawo kuma ya warkar da kansa idan kawai muka sauƙaƙa wannan matsin lamba, wannan matsin lamba na dan adam, daga ciki kuma muka bar hakan ya faru. Akwai hujjoji a yanzu".
Ma'aurata MACED a wurin shakatawa na kare California don rashin sanya takunkumin fuska yayin cin abincin rana (VIDEO) - RT USA News
Akwai takunkumin rufe fuska sannan kuma an cika kai hari.
Wasu ma'aurata a California suna cin abincin rana tare da dambensu a wani wurin shakatawa na kare sun fuskanci na biyu, lokacin da wata mata mai ban dariya ta yi musu ruwan barkono saboda ta ki rufe fuska... yayin cin abinci.
Ash O'Brien da mijinta Jarett Kelley sun ce suna cizo ne don su ci abinci a wurin shakatawa na karnuka na Dusty Rhodes a San Diego a ranar Alhamis, tare da ƙafafunsu na watanni uku a jere.
Ma'auratan suna da takunkumin rufe fuska don su ci abinci, lokacin da wata "tsohuwar mata" ta matso kusa, ta kira su "idiots" don kada su rufe fuska, duk da cewa "ba za ku iya sanya abin rufe fuska ba kuma ku ci a lokaci guda".
O'Brien ya shaida wa matar cewa ta bar wurin shakatawa ta daina yi mata mummunan sakamako, inda a nan ne matar ta fito da karfin tsiya a wajen ma'auratan.
Hoton bidiyo da wani da ke tsaye ya dauka ya fara ne da yadda Kelley ya rika fesawa daga hannun matar, sannan ya rika shigar da kara a fuska saboda matsalolin da ke damunsa.
Ana iya jin O'Brien tana kuka a baya yayin da mai kai hari ke tafiya tare da karnukanta.
O'Brien ta wallafa bidiyon a Facebook kuma ta shaida wa ABC 10 cewa tana son ganin matar "ta je gidan yari."
Takunkumin fuska ya zama tilas a duk fadin jihar California, har ma a cikin iska mai tsabta.
Ana iya cire waɗannan abin rufe fuska ne kawai a wasu lokuta kaɗan, ciki har da lokacin cin abinci ko sha.
Sai dai babu inda ya ke cikin ka'idojin cutar coronavirus a jihar ya na mai cewa masu tsattsauran ra'ayi na iya amfani da makamai marasa karfi wajen aiwatar da wannan manufar.
Hatta a zamanin da ake ciki na "yan kunar-bakin-wake, har yanzu wannan laifi ne da ke dauke da tarar dala 1,000 ko kuma har zuwa shekaru uku a gidan yari na jihar.
Scotland-England Union Chain Bridge ya cika shekara 200 da haihuwa
Wata gada da ta hada Scotland da Ingila ta mayar da shekara 200 gabanin gyaran £10m.
Gadar Union Chain Bridge ta tsallaka kogin Tweed daga Fishwick a cikin iyakokin Scotland zuwa Horncliffe a Northumberland.
Lokacin da aka bude ta a shekarar 1820, ita ce gadar dakatar da baƙin ƙarfe mafi tsawo a duniya da ke da tsawon mita 449 (137m).
Haka kuma ita ce gadar motoci ta farko irin ta a Birtaniya.
Jami'in sojin ruwa na Ingila Capt Samuel Brown ne ya tsara gadar.
Ya jadadda mallaka da kuma samar da sarƙoƙin ƙarfe na ƙarfe bayan asarar jiragen ruwa na Royal Naval wanda ya karye daga igiyoyi.
Abokai na Union Chain Bridge da Cibiyar Injiniyoyi (Ice) Scotland sun nuna alamar tsallakewar.
Robert Hunter, na kungiyar abokai, ya ce: "Wannan hakika daya ne daga cikin gadoji mafi tarihi a duniya kuma wani kayan aikin injiniya mai ban sha'awa.
"Mun shirya bukukuwa da dama don bikin, amma abin takaici dole ne a dakatar da su.
"Duk da haka, cewa ba da daɗewa ba za a fara aiki a kan gyaran £10m shine mafi kyawun ranar haihuwar da za a iya samu kuma zai tabbatar da cewa al'ummomi masu zuwa za su iya jin daɗin gadar cikin dukkanin kyawawan halaye."
Daraktan kamfanin Ice Scotland Hannah Smith ta bayyana gadar a matsayin wani ɓangare na kayan aikin injiniya na Scotland.
Ta ce: "Mun san cewa sananne ne a duniya kuma abin mamaki ne cewa nan ba da jimawa ba za a soma aikin gyare-gyarensa."
Cutar Salmonella ta yi ajalin mutane 212 a jihohi 23
25 ga Yuli (UPI) - Cibiyar Kula da Cututtuka da Rigakafin Cututtuka na binciken barkewar cutar Salmonella wacce ta kamu da cutar mutane 212 a jihohi 23.
A cikin wata sanarwar manema labarai a ranar Juma'a, CDC ta ruwaito cewa mutane 87 sun kamu da rashin lafiya tun bayan sabuntawarta ta karshe game da barkewar cutar a ranar Talata.
Hukumar ta ce mutane sun fara nuna alamun da ke da nasaba da nau'in salmonella, wanda zai iya ɗaukar makonni biyu zuwa hudu kafin bayyanar cututtuka, tsakanin 19 ga Yuni zuwa 11 ga Yuli.
Mutane talatin da daya ne aka kwantar da su a asibiti tun bayan barkewar cutar, amma ba a samu rahoton mutuwar mutane ba.
A cewar CDC, ba a gano takamaiman tushen nau'in kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin kifin
Ba a bayar da wata shawara a kan cin abinci ko cin wasu kayan abinci ba, kuma ba a sanya sunan masu sayar da kayayyakin da za su iya sayar da gurbatattun kayayyaki ba.
Oregon ta sami mafi yawan wadanda suka kamu da cutar Salmonella, tare da kamuwa da cutar 51, inda Utah ta biyo bayan kusan kamuwa da cutar 40 da aka ruwaito.
Salmonella cuta ce ta kwayoyin cuta, abinci da ke haifar da kamuwa da cutar miliyan 1.35, 26,500 a asibiti, da kuma mutuwar mutane 420 a kowace shekara, a cewar CDC.
Alamun kamuwa da cutar Salmonella sune gudawa, zazzabi, da kuma ciwon ciki, wanda zai iya farawa tsakanin awanni shida zuwa kwanaki shida bayan kamuwa da cutar.
Cutar yawanci tana kwana hudu zuwa bakwai, kuma yawancin mutane suna warkewa ba tare da magani ba, amma wasu lokuta suna bukatar a kwantar da su a asibiti.
United, Chelsea cikin CL; Bournemouth, Watford sauka daga EPL
Manchester United da Chelsea sun samu gurbin zuwa gasar zakarun Turai a kan kudi da Leicester ta yi a ranar karshe ta gasar Firimiya a ranar Lahadi, yayin da Bournemouth da Watford suka koma karshen zama na tsawon shekaru biyar a saman gasar.
United ta ci Leicester 2-0 ta hanyar cin kwallaye ta hannun Bruno Fernandes da kuma Jesse Lingard wanda hakan ya baiwa kungiyar ta Ole Gunnar Solskjaer matsayi na uku.
Chelsea ta doke Wolverhampton da ci 2-0 bayan zura kwallo a raga da kuma taimakawa Mason Mount kuma ta kammala a gasar cin kofin zakarun Turai a karo na hudu kuma na karshe a gasar cin kofin zakarun Turai a sama da Leicester wacce ta kasance a cikin manyan hudu a yawancin kakar wasa ta bana.
Leicester, a maimakon haka, za ta buga gasar Europa League tare da Tottenham, wacce ta tashi 1-1 a Crystal Palace don samun matsayi na shida - sama da Wolverhampton a kan bambancin kwallo.
Kungiyar kwallon kafa ta Aston Villa ta ci kwallo a minti na 84, ta yarda bayan minti daya, sannan ta yi kunnen doki da ci 1-1 a hannun West Ham don tsira.
Kyaftin Jack Grealish ya zurawa Villa kwallo a abin da zai iya zama wasansa na karshe ga kulob dinsa na karama.
Bournemouth ta yi abin da ya kamata ta kuma doke Everton da ci 3-1, amma ta kare da maki daya a bayan Villa.
An kuma sallami Watford a matsayin kungiya ta gaba-gaba bayan da ta yi rashin nasara da ci 3-2 a hannun Arsenal.
Manchester City ta ci kwallaye 100 na yakin neman zabe da ci 5-0 a kan matsayi na karshe da kuma riga-kafin Norwich, wasan da ya zama na karshe a gasar Firimiya ga David Silva bayan shekaru 10 tare da City.
Kevin De Bruyne ya samu mataimaki na 20 a kakar wasan bana kuma ya zura kwallo sau biyu.
Liverpool ta kawo karshen kakar wasannin da ta lashe da ci 3-1 a Newcastle sannan ta kare a rikon kwarya da maki 99.
Haka kuma Southampton ta doke Sheffield United da ci 3-1, inda Danny Ings ya zura kwallonsa ta 22 a kakar wasan bana.
Hakan ya sa ya koma bayan Jamie Vardy na Leicester, wanda ya lashe Golden Boot a matsayin dan kwallo mafi girma a gasar.
Tony Blair ya yi alkawari cewa ba za a daina saka baki a siyasar Birtaniya ba duk da tsananin koma baya na Brexit
Tony Blair ya yi alkawarin cewa ba zai daina shiga tsakani a siyasar Birtaniya ba, bayan koma baya mai tsanani ga yadda ya shiga jam'iyyar Labour da kuma yaki da tsatsauran ra'ayi.
Mista Blair, wanda ya kwashe fiye da shekaru goma a mukaminsa, ya shaida wa Sophy Ridge a shafinsa na Sky News cewa, zai "kowane lokaci" daina fadin albarkacin baki a harkokin siyasar Birtaniya.
Sai dai wannan dan siyasa mai ra'ayin rikau ya yarda da cewa "mutane da yawa na kallon hakan na iya tunanin cewa ya kamata in daina magana kan abubuwa."
Sophy Ridge ta fadawa Mista Blair cewa: "A koyaushe ina jin cewa ba za ka iya kawar da kanka daga siyasa ba."
"Kullum kuna wallafa rahotanni kan cutar Koronabirus ko kuma ku fito da hujjoji kan Brexit."
"Ina mamakin ko mutane suna tunani, me ya sa bayan shekaru goma na zama PM, har yanzu kuna kokarin shiga harkokin siyasa?"
"Shin ba lokaci ba ne da za a dauki lokaci ba, a zagaya filin wasan kwallon kafa."
Tsohon Firaministan ya yi watsi da hakan, ya kuma sha alwashin ci gaba da kasancewa a siyasar Birtaniya muddin ya ga dama.
Ya ce: "Ba wani abu ba ne da nake so in yi. Mutane da yawa suna kallo suna iya tunanin cewa shi ne ainihin abin da ya kamata ya yi, ya daina magana kan abubuwa, amma ina damuwa da kasar nan."
"Muna cikin wani babban lokaci na canji a duniya da kuma cibiyar da na gina ayyuka a duniya."
"Na san na yi wani abu da firayim ministoci na baya ba su yi ba amma a nan gaba na yi hasashen cewa wasu da yawa za su yi kokarin yi."
Tun da farko a hirar da aka yi da shi, Mista Blair ya ce har yanzu Birtaniya da EU za su iya kulla yarjejeniya kan Brexit kafin karshen shekarar nan.
Ya ce: "Za su iya sauko da wata yarjejeniya, amma har da yarjejeniyar da muke sauka za ta zama marar kyau."
"A gaskiya zai zama alheri ga Turai saboda hakan zai ba da damar sauƙaƙa kasuwancin kayayyaki amma zai hana mu batun hidimomi sosai."
Tsohon shugaban kwadago ya kuma fadawa gidan talbijin na Sky News cewa Burtaniya za ta zauna da cutar COVID-19 ba tare da kawar da ita ba, nan gaba kadan.
Yayin Girmamawa Ga Jaruman Kargil, PM Narendra Modi Ya Ce Pakistan Ta Yi Kokarin "Backstab" Indiya
Pakistan ta yi kokarin "backstab" Indiya duk da yunkurinta na ci gaba da sada zumunta, Firaminista Narendra Modi ya fada a yau a jawabinsa na jinjina ga sojojin kasar a ranar cika shekaru 21 da yakin Kargil.
A cikin adireshin gidan rediyonsa na wata-wata Mann ki Baat, PM Modi ya ce "Pakistan ta aiwatar da wannan mummunan aiki ne ta hanyar tsare-tsare na kama ƙasar Indiya da kuma karkatar da rikice-rikicen da ke faruwa a ciki."
"Pakistan na da karfin gwiwar kokarin mamaye kasar Indiya da kuma karkatar da hankali daga tashin hankalin da ke faruwa a ciki," in ji shi.
"A lokacin, Indiya na kokarin kyautata dangantaka da Pakistan. Amma kamar yadda ake cewa, dabi'ar mugunta ita ce yaki da kowa da kowa ba tare da dalili ba. Mutane masu wannan dabi'a za su iya tunanin yin mugunta ne kawai har ga wadanda suke kokarin yi musu alheri. Shi ya sa Pakistan ta caccaki Indiya duk da yunkurin Indiya na dangantaka mai kyau," in ji shi.
"Za ka iya tunanin cewa, makiya sun hau kan duwatsu yayin da sojojinmu suke fada da su daga kasa, amma tsananin dabi'a da kuma gaskiyar sojojinmu sun yi nasara a kan duwatsu", ya kara da cewa.
"Dangane da karfin gwiwar sojojinmu, Indiya ta nuna karfi sosai a Kargil," in ji PM Modi, yana mai tunawa da ziyarar da ya kai yankin.
A kowace shekara ana bikin Kargil Diwas, alamar ranar da sojojin Indiya suka karbe dukkanin matsugunan Indiya a Kargil na Ladakh wanda sojojin Pakistan suka mamaye shekaru 21 da suka gabata.
A ranar 26 ga watan Yulin shekarar 1999, rundunar sojin ta sanar da samun nasarar kammala aikin "Operation Vijay".
Yaƙin da aka shafe kusan watanni uku ana gwabzawa a tsaunukan Ladakh ya salwantar da rayukan sojojin Indiya sama da 500.
Tun da farko a yau, ministan tsaro Rajnath Singh, karamin ministansa Shripad Naik, babban hafsan hafsoshin tsaro Janar Bipin Rawat, babban hafsan sojoji M Naravane, babban hafsan sojojin sama R K S Bhadauria da kuma babban hafsan sojojin ruwa Admiral Karambir Singh sun ba da gudummawa a Amar Jawan Jyoti a taron tunawa da yakin kasar.
A cikin shekarun da suka gabata tun daga Kargil, dangantakar Indiya da Pakistan ta yi tsami bayan jerin hare-haren ta'addanci.
Indiya ta nace cewa tattaunawa da ta'addanci ba za su iya shiga hannu ba sannan kuma Pakistan ta bukaci rarraba dukkanin sansanonin ta'addanci da ke gudana daga kasarta.
Gwyneth Paltrow na son yara su sami 'da'a mai kyau'
Gwyneth Paltrow ta ce tana so ta yi renon 'ya'yanta don samun da'a mai kyau yayin da take kokarin 'ba kawai ta ba su abubuwa ba'.
Paltrow tana da 'ya'ya biyu, Apple (16) da Musa (14), tare da tsohon mijinta Chris Martin kuma tana son su kasance da kyakkyawan dabi'u kuma ba su da daraja ga iyayensu.
"Dalilin da ya sa nake ganin yana da muhimmanci sosai... A yi renon yaro wanda ke da da'a ta aiki da kuma wanda dabi'unsa suka dace da naka ko kuma yadda suke ji game da ko su wane ne, da dai sauransu", ta gaya wa Rob Lowe a cikin kwasfansa.
"Gaskiyar lamarin ita ce za a iya bude maka kofofin, amma idan ka yi tunani a kan dukkanin mutanen da suka yi kokari kuma hakan bai faru ba."
Ta ci gaba da cewa, "a matsayina na iyaye da kuke tsammani, duk abin da zan iya yi wa wadannan yara shi ne koya musu abin da ya dace daga kuskure da kuma koya musu abin da aiki yake.
Paltrow ta kuma dauki matakai don bai wa 'ya'yanta damar zama a asirce kamar yadda ya kamata, tare da tabbatar da cewa suna ci gaba da asusun kafofin watsa labarun.
"Ba zan bar su su fito fili a kafofin watsa labarai ko wani abu makamancin haka ba, ina kokarin cire su daga idanun jama'a yadda ya kamata," in ji ta.
"Ka sani, yanzu ya bambanta, 'saboda yara suna kama da, 'Zan iya samun tashar YouTube?' kuma ina kamar, 'A'a, ba za ka iya ba.
Babu shakka babu."
Imam-Ul-Haq Na Kasar Pakistan Ya Yi Allah Wadai Da Harin Kunar Bakin Wake Bayan Ya Ji Rauni
Pakistan da Ingila za su fuskanci juna a gwaje-gwaje guda uku da kuma T20Is masu yawa.
Wani likitan kungiyar dan kasar Pakistan mai suna Imam-ul-Haq ya bayyana cewa ya dace da jemage, bayan da aka buge shi a hannunsa na hagu a lokacin da yake jikinsa a wani wasa na dumi-dumi da aka yi a Derby.
"Batsman na hannun hagu ya shiga zaman dumi-duminsu kafin a soma wasa a rana ta biyu" Hukumar wasan kurket ta Pakistan (PCB) ta sanar da hakan a cikin wata sanarwa.
An buge Imam na PCB Whites a hannunsa na hagu yayin da yake caccakar Naseem Shah na PCB Greens a ranar daya a wasan.
An tilastawa Imam yin ritaya da ciwo a ranar Juma'a da yamma bayan da aka buge shi a hannun hagu da kwallo daga hannun Shah, amma ya samu damar shiga dumi-dumi da safe kuma zai ci gaba da shigar da kara a rana ta uku.
Binciken "Abbasiyawa": Tsohon hoton Aeschylus na shan kashi
Babu wani aiki mai yawa, har ma da wani makirci, a cikin "Abbasiyawa."
Mutane suna niƙa, suna magana (ba shakka da tsanani) game da abubuwan da suka faru (babu shakka na mummunan nau'i) da suka faru da nisa.
Duk da haka wannan gidan wasan kwaikwayo na kasar Girka ya fito da sauti mai karfi da kuma hasala.
A kololuwarsa, wasan kwaikwayon ya yi kama da bugun zuciya na hasken rana, yana kawar da numfashinka - tasirin ya dan ragu ne kawai ta hanyar kallon yanar gizo.
An fara samar da shi a shekara ta 472 kafin haihuwar Yesu, "The Persians" na Aeschylus ana daukarsa a matsayin mafi tsufa da ya tsira daga wasan Girka.
Wannan shiri na Dimitris Lignadis an watsa shi kai tsaye a ranar Asabar daga tsohuwar gidan wasan kwaikwayo na Epidaurus; a ruhin gidan wasan kwaikwayo, babu wani rubutu da aka yi a yanar gizo.
An samo asalin wurin ne a matsayin wani ɓangare na asclepeion na birnin (cibiyar warkarwa) saboda Helenawa sun dauki daidaituwa tsakanin jiki da rai da muhimmanci ga koshin lafiya.
Bari mu yi tunani a kan wannan falsafar.
Shirin ya yi magana ne game da sakamakon Salamis, wani yaki na jirgin ruwa wanda 'yan Girka da suka fi yawa suka kori sojojin Farisa masu girma shekaru 2,500 da suka gabata.
A lokacin da sararin samaniyarmu ke rufewa, abu ne da ke haifar da kusan shiga cikin masu sauraro a kai tsaye wajen kallon 'yan wasan kwaikwayo na raye-raye a Girka yayin da suke yin wasan kwaikwayo na shekaru dubu.
Aeschylus da kansa ya yi gwagwarmaya a Salamis, amma wasan da ya yi yana da ban sha'awa: Wannan tsohon soja na bangaren nasara ya ba da labarinsa a cikin wadanda suka sha kashi, inda ya lura da damuwar abokan gabansa na baya-bayan nan.
Wani mawaƙi na mutanen Farisa, sanye da dogayen tufafi masu launin tan da kuma fararen shirye-shirye masu saukar da maɓalli, ya buɗe aikace-aikacen.
Suna cikin babban birninsu suna cikin damuwa suna jiran labarin sarkinsu Xerxes, wanda ya kashe shi tare da Athens.
Shigar da mahaifiyar gwauruwa ta Xerxes, Sarauniya Atossa (Lydia Koniordou), a cikin wata babbar baƙar fata wacce ta bayyana cewa za ta sa ta, maimakon baya; ita mutum ce a cikin wani nau'i na masana'anta, mai rauni da karfi.
Koniordou, wacce ke cikin manyan 'yan wasan kwaikwayo na kasar Girka, ta san irin rawar da ta taka a waje - ta jagoranci kuma ta yi wasa a wani shirin wasan kwaikwayo na kasar Girka na "The Persians" wanda ya taka leda a cibiyar birnin New York a shekara ta 2006 - kuma tana gabatar da aikace-aikacen ba tare da yin abubuwa da yawa ba.
A mafi yawancin lokuta, tana tsaye a tsakiyar mataki na madauwari, tana nuna fushi mai wuya da kuma baƙin ciki yayin da aka bayyana yanayin bala'in da ya faru da sojojin gida.
Wannan tsoron da kowa ya ji, an tabbatar da shi, a cikin cikakkun bayanai, ta hanyar wani manzo (Argyris Pandazaras) da ya dawo daga gaba.
A wani yanayi mai cike da ban mamaki, ya ba da labarin wannan yaki, inda ya yi bulala da kansa cikin hauka yayin da 'yan mawaƙa ke rawa a kusa da shi kuma Giorgos Poulios mai kama da wasan kwaikwayo na drone ya kumbura zuwa abin da ya zama matakin kururuwa.
Daga baya sai mijin Atossa da ya mutu (Nikos Karathanos), wanda aka kira shi daga karkashin duniya, da kuma Xerxes (Argyris Xafis), wanda ko ta yaya ya tsere da rai daga lalacewar.
Abubuwan da ke tattare da zane-zane a jikinsa na alamar jini (kayan kayan kwalliya na Eva Nathena a koyaushe suna taimakawa wajen ba da labari).
Haruffan suna baƙin ciki da rayukan da aka rasa da kuma ɓarna tare, a wani aiki na makoki na al'umma.
Kadan daga cikin kayan wasan kwaikwayo na gargajiya da muke gani a Amurka na ƙoƙarin samar da shi ta wata hanya.
Sau da yawa ana yin hakan ne tare da karatun layi na dabi'a, a kokarin sa rubutun ya yi kasa a waje, ya fi sauƙin narkewa.
Amma Lignadis da rundunarsa sun rungumi ra'ayi, wanda zai iya zama abin tilastawa ga kunnuwa na zamani amma ya nuna karfin rubutun.
Duk da yake a zahiri ba sa raira waƙa, alal misali, 'yan wasan kwaikwayo guda huɗu suna isar da arias, suna samun karfin motsa jiki wanda ke jin banbancin duniya.
Ba za mu taba mantawa da cewa wasan ya samo asali ne daga motsin zuciyar da dukkanin mutane ne.
Ranar Lahadi tare da Oliver Spencer: "Ba zan yi kwalliya ba, ranar lahadi na yin kwalliya"
Yaya ranar Lahadi ta soma?
Tare da ni ina saukar da matakala da kuma fadowa kan karen a kan hanyata na sa matata ta zama kofin shayi.
Idan na yi sa'a, za mu tsere daga London zuwa gidanmu da ke bakin teku a tsibirin Wight.
Mu biyun za mu zauna tare mu kalli fadin ruwa cikin shiru.
Yana da sauti mai sanyin gwiwa...
Shi ne, har zuwa karfe 8 na safe lokacin da 'ya'yanmu maza biyu ko uku suka yi kara a ƙofar suna neman karin kumallo.
Yana da bacon da kwai a gare su, alayyafo da namomin kaza a gare mu; to idan yanayi ya yi kyau, sai mu fitar da yaran.
Za mu yi iyo, ko filafili ko kuma mu yi tafiya a kusa da kyakkyawan Quarr Abbey, wanda ya yi kama da wani abu a kai tsaye daga Game of Thrones.
Kuma a lokacin kullewa?
A makonni biyu na farko da na yi cikakkiyar musantawa, ban iya yarda da cewa an rufe kasuwanci na ba.
Na shagaltar da kaina ta hanyar damuwa game da rayuwa ko mutuwar sabon lambun da na shuka.
In ba haka ba, na yi gwaji a cikin kicin: Aal mai dandano mai tsanani da shiitake da kuma brioche mai kirim biyu sun kasance abubuwan da nake bukata.
Ta yaya za ka kwantar da hankali?
Ba zan yi ado ba, ranar lahadi ne don kayan kwalliya, rabin kayan kwalliya da kuma farin T-shirt.
Bayan cin abincin rana na kaza mai gasa, zan yi barci da takardun a kan kujerar bene a gonar.
Ina kokarin kada in sha: yana taimakawa wajen share kaina kafin ranar Litinin ta zo kiran.
A ranar Lahadi da ta tsaya?
Bayan tsawon daren Asabar a bikin haihuwar 'yar uwata mai shekara 40 a New York, da tsakar dare matata mai dauke da juna biyu ta yanke shawarar cewa za mu fi dacewa mu tafi.
Ta ƙuduri aniyar jin daɗin kanta, tana gaya wa mutane cewa ita ce ta uku bayan haka.
Mun bar jam'iyyar sai ta shiga aiki kai tsaye.
Da daren Lahadi?
Da karfe 7 na dare mun tattara motar kuma mun shiga jirgin zuwa Portsmouth.
A tuki sama da A3 kuma mun dawo London na mako-mako: yara a gado, ina tafiya da kare kuma ina da kwano na hatsi.
Ina da kyau da barin Isle of Wight don komawa garin, na san idan ba haka ba, ba zan iya samun gida a wurin ba.
Masu ba da bashi na yanar gizo sun yi gargadin tsarin bashi na SME na iya rasa alamar
Ƙananan ɓangarorin kasuwanci, waɗanda galibi manyan bankuna ke ba da su, sun ƙara juyawa ga masu ba da bashi ta yanar gizo don biyan bukatun kudade.
Sai dai Mista Callaghan ya ce masu ba da bashi ta yanar gizo ba su da matsala idan aka kwatanta da manyan bankuna saboda ba su da damar samun kudade masu saukin farashi iri daya kuma ya yi gargadin sakamakon haka tsarin bayar da lamuni na SME ba ya samun karbuwa.
"Ina ganin mai yiwuwa ya rasa alamar inda dukkanin mutanen da suka kira mu, suka yi kira da a yi tsammanin za su iya samun kudade masu arha sosai maimakon gwamnati ta tallafawa kashi 50 cikin 100 na rancen," in ji shi.
"Saboda haka suna kira kuma sun yi matukar baƙin ciki saboda an fitar da tsammanin cewa akwai farashi mai ragi kuma muna duba farashin kuɗin da muke kashewa wanda bai canza ba kwata-kwata."
Mista Callaghan ya kara da cewa idan fintechs za su iya samun damar samun kudade masu rahusa kuma su ba da cewa ga kananan kamfanoni wannan makirci zai zama "babu mai kwakwalwa".
"Ya kasance wani abu mai kamawa na 22 manyan bankuna sun samu damar samun kudade masu tsada amma sun fi fuskantar hadari saboda haka ba za su fita su ba da rance a zahiri ba, ba za su iya samun damar yin amfani da bayanan ba kuma ba za su iya samun kwanciyar hankali ba sai dai idan kana da dukiya," in ji shi. "Har zuwa lokacin da za mu iya samun damar samun wannan kudade mai rahusa ina ganin akwai almara a kasuwa kan yadda za a yi farin jini a tsarin."
Moula mai tushe a Melbourne shima yana shiga cikin wannan tsari kuma babban jami'in zartarwa Aris Allegos ya ce amfanin garanti na kashi 50 cikin dari, wanda ya shafi tsarin gwamnati, ya kamata a ba da shi ga kananan kamfanoni amma masu ba da bashi daban-daban suna magance hakan ta hanyoyi daban-daban.
"Na fahimci cewa mai yiwuwa akwai wasu da ba sa wucewa ta wannan tsari na kudin," in ji shi.
"Wannan na iya zama aiki na yadda aka tsara kudaden su kuma yana iya zama aiki na wane nau'in da suke ba da rance da kuma yadda suke tantance hadarin a cikin waɗannan nau'ikan."
Mista Allegos ba zai ba da cikakken bayani game da yawan kudaden da Moula ya bayar a karkashin tsarin ba, amma ya ce tsarin da aka sake tsara shi ne "babban sanin abin da ake bukata don canzawa" don samar da karin sassauci ga masu ba da bashi da masu bashi.
Duk da haka, ya ce babbar damuwarsa ita ce "tattalin arziki mai sauri guda biyu" da ke aiki da kuma tasirin da hakan zai yi ga kananan kamfanoni.
"Babban batun da Moula ya fuskanta da kuma masu ba da bashi game da kananan kamfanoni shi ne yadda za a iya sarrafawa a cikin wannan dutse," in ji shi.
"Gaskiya magana dangane da bukatar ba mu koma matakan riga-kafin cutar COVID ba duk da cewa ci-rani na ƙaruwa."
Har ila yau, mai ba da lamuni a kan layi na ASX Prospa ba zai bayyana adadin rancen da ya bayar a karkashin tsarin ba yayin da ya ce bayanan suna da matukar damuwa ga kasuwanci amma shugaban zartarwa Greg Moshal ya ce tsawaita tsarin ya yi maraba.
"Muna goyon bayan duk wani ingantaccen tsarin da zai bai wa kananan kamfanoni damar samun dimbin kayayyakin tallafin da suka dace da bukatunsu, ciki har da kayayyakin tsabar kudi masu sassaucin ra'ayi a kan gajerun sharuddan," in ji shi.
Flat, ilimi kyauta ga mai sayar da kwai na Indore mai suna Paras Raykar wanda aka kifar da shi bisa la'akari da cewa ya wuce Rs. 100 Bribe
Jami'an fararen hula a Indore sun yi zargin cewa an kifar da katakon Paras Raykar da ke dauke da kwai a ranar Alhamis.
Kwanaki biyu bayan labarin wani mai sayar da kwai mai shekaru 13 da haihuwa da jami'an fararen hula suka kifar da shi a kafafen sada zumunta, yaron dan kasar Indore ya samu goyon baya mai yawa daga mutane a fadin kasar, wanda hakan ya taimaka musu wajen farfadowa daga asarar da suka yi tare da sake fara kasuwancinsu.
Iyalan yaron sun kuma yi ikirarin cewa 'yan siyasa da suka hada da shugaban majalisa Rahul Gandhi da kuma babban ministan Delhi Arvind Kejriwal sun kai musu dauki tare da bayar da tallafi.
Iyalan yaron sun kuma karbi leburori da tayin kula da kuɗin karatun yaran da ke cikin iyali.
Jami'an fararen hula a Indore sun kifar da katakon Paras Raykar da ke dauke da kwai a ranar Alhamis, inda gwamnati ta aiwatar da dokar "dama ta hagu" don tsagaita bude shaguna a tsakiyar annobar coronavirus.
Bidiyon da yaron ya yi zargin cewa jami'an sun gargadi shi da safe da ya cire kekensa ko kuma ya biya Rs 100 a matsayin cin hanci da rashawa ya yi kamari a kafafen sada zumunta.
A lokacin da ya ki, sai jami'an kwastam suka yi awon gaba da shi, inda suka lalata dukkan kwai, kamar yadda yaron ya yi zargin.
Har ila yau, yaron ya yi ikirarin cewa sayar da shi na yau da kullum ya ragu saboda annobar kuma asarar hannun jari zai sa masa karin nauyin kudi, a cikin bidiyon.
Tun ranar Alhamis, iyalan yaron sun cika da tallafi daga mutane a fadin kasar, da yawa daga cikinsu suna ba da taimako ta tsabar kudi da kuma alheri.
Iyalan sun kuma samu taimako daga 'yan unguwa.
Yayin da tsohon babban minista Digvijaya Singh ya ba da tallafin kudi da taimako don shigar da yaran a wata kwaleji, BJP MLA daga Indore, Ramesh Mendola, ya ba da tabbacin samar da gida a karkashin Pradhan Mantri Awas Yojana ga yaron.
Kungiyar manema labarai ta Indore ta kuma bayar da tallafi da kudi ga yaron.
Shugaban majalisa Rahul Gandhi da kuma babban ministan Delhi Arvind Kejriwal sun ba da taimako.
Muna cike da goyon baya daga mutane a fadin kasar nan.
(BJP MLA) Ramesh Mendola ya tabbatar da wani lebur a karkashin Pradhan Mantri Awas Yojana.
Ya kuma samar da zagon kasa da kuma Rs 2,500.
Digvijaya Singh ya bayar da Rs 10,000 da tabbacin kula da ilimin yaran biyu.
Ofishin Rahul Gandhi ya kuma yi kira da bayar da tallafi.
Wata mata daga babban ministan birnin Delhi Arvind Kejriwal ta yi kira kuma ta ba da taimako.
"Jyothiraditya Scindia ta kuma ba da tallafi," in ji kakan Paras.
Angola: An Sanya Asibitin Pedalé a Ma'aikatar Lafiya
Luanda - Shugaban Jamhuriyar, João Lourenço, ya tabbatar da cewa a wannan Jumma'a za a mayar da kulawar asibitin Pedro Maria Tonha Pedalé, wanda ake ginawa a Luanda, zuwa fannin ma'aikatar kiwon lafiya.
A cikin wata sanarwa, ofishin yada labarai na shugaban kasar ya sanar da cewa matakin na da nufin cika ka'idar gwamnati na gina da kuma fadada cibiyar sadarwar asibitocin jama'a don tabbatar da ingantaccen kula da lafiya da magunguna ga jama'a.
"A wannan takamaiman lamari, ra'ayin shi ne a samar wa Angolans wani asibiti mai mahimmanci, wanda aka bambanta kuma aka san shi da fasahar zamani da kuma ingantaccen bincike da kuma maganin cututtuka masu rikitarwa", in ji takardar.
Ya jaddada cewa, shawarar da shugaban kasar Angola ya yanke ta kuma yi la'akari da bunkasuwar al'ummar kasar, wacce ta haifar da "babban bukata" ga ayyukan kiwon lafiya masu inganci a fannoni daban-daban.
Wannan bukata, bayanin ya ci gaba da cewa, ta tabbatar da cewa an hada shi a asibitin da aka kware don magance cututtuka masu rikitarwa, koyarwa da bincike, ayyukan da suka shafi ilimin likitancin ido da na jarirai, wuraren da dabarunsu da gudanar da su suka cancanci kasancewa a karkashin nauyin ma'aikatar kiwon lafiya.
"Ranar Lahadi" Matinee: Bikin Rodgers &amp; Hart
A shekarar 2020 ne aka gudanar da bikin zagayowar ranar haihuwar 'yan wasan Broadway na farko na haɗin gwiwar kwararru na ɗaya daga cikin shahararrun 'yan wasan kwaikwayo na wasan kwaikwayo, Richard Rodgers da Lorenz Hart.
Don girmama wasansu na rubutun wakoki, taurarin Broadway Jelani Alladin ("Frozen", "Hercules") da Christiani Pitts ("King Kong", "A Bronx Tale"), tare da dan wasan Richard Riaz Yoder ("Hello, Dolly!", "Shuffle Along"), sun gabatar da wani nau'i na zamani a kan Rodgers &amp; Hart misali "The Lady Is a Tramp", wanda aka rubuta musamman ga masu sauraro na "Sunday Morning".
Jagoran kiɗa da kuma shirye-shirye na Drummer Bryan Carter, wanda ya yi tare da mawaki Russell Hall.
Ma'aikata Sama Da 30 Sun Yi Gwajin Cutar Coronavirus Mai Kyau A Bangaren Banki Guda A Tamil Nadu
Akalla ma'aikata 38 na babban reshen bankin kasa a Tiruchirappalli, Tamil Nadu, sun yi gwajin cutar coronavirus, jami'ai daga bankin da kuma hukumar jama'a na yankin sun ce.
A cewar jami'an, an kuma shawarci kwastomomin da suka ziyarci bankin da su fito da son rai domin yin gwajin cutar Koronabirus.
Tun da farko, wani babban jami'in reshen da ke fama da wasu rikice-rikice, ya mutu sakamakon cutar COVID-19.
Kwararrun wadanda suka kamu da cutar sun fito ne bayan da aka gudanar da wani sansanin binciken likitoci a bankin a baya-bayan nan, in ji jami'an.
Manyan jami'an bankin sun ce an kammala aikin kwantar da hankalin kuma bankin na iya ci gaba da aiki daga gobe.
Jami'an kiwon lafiya na kamfanin suna hulda da kwastomomin da suka ziyarci bankin.
Tamil Nadu, wanda ke da mafi yawan wadanda suka kamu da cutar a kasar bayan Maharashtra, ya ba da rahoton adadin mutane 2,06,737 da suka kamu da cutar har zuwa ranar Asabar.
Kanye West ta nemi gafara ga matar Kim Kardashian bayan bayyanar aure
Kanye West ta nemi gafara ga matar Kim Kardashian saboda tafiya jama'a da wani "al'amari mai zaman kansa".
The rapper bayyana a lokacin wani taron a South Carolina cewa ma'aurata sun yi la'akari da zubar da su na farko da yaro.
Bayan wani mako mai cike da cece-kuce da ya yi a kan matarsa da iyalinta, a yanzu West ta aika da sakon neman gafara.
West kuma ya ziyarci asibiti sa'o'i bayan da Justin Bieber ya ziyarce shi a ransa da ke Wyoming.
Ya ce: "Ina so in nemi gafara ga matata Kim saboda tafiya jama'a da wani abu mai zaman kansa.
Ban rufe ta ba kamar ta rufe ni.
"To Kim ina so in ce na san na cutar da kai. Don Allah ka gafarta mini. Na gode da ka kasance a wurina a koyaushe."
Wasu sakonnin da West ta wallafa da suka hada da ikirarin matarsa ta yi kokarin ganin likitoci sun kulle shi sannan ya yi jerin tuhume-tuhume a kan surukarsa Kris Jenner.
Ya kuma ce ya yi kokarin raba auren Kardashian West wacce ya aura a shekarar 2014.
Tsakanin fargabar halin da mijinta ke ciki, Kardashian West, mahaifiyar 'ya'yan West hudu, ta fitar da wata sanarwa mai tsawo da ke cewa ita da iyalinta ba su da karfi don shiga tsakani da kuma tunatar da magoya baya cewa yana da matsalar rashin lafiya.
Ta ce: "Shi mutum ne mai haske amma mai rikitarwa wanda a bisa matsin lamba na kasancewa mai zane-zane kuma baƙar fata, wanda ya fuskanci rashin mahaifiyarsa mai zafi, kuma ya fuskanci matsin lamba da kadaici da ke dada haifar da matsalar rashin lafiyarsa ta bi-ta-da-kulli."
Ta kara da cewa ba ta taba tattaunawa kan yanayin da ya ke ciki ba saboda tana "kyakkyawan kariya ga yaranmu da kuma hakkin Kanye na tsare sirri idan aka yi la'akari da lafiyarsa."
Ta ci gaba da cewa: "Amma a yau, ina jin kamar ya kamata in yi sharhi a kansa saboda cin hanci da rashin fahimta game da lafiyar kwakwalwa."
West ya yi ikirarin zubar da ciki a lokacin wani taron a ranar 19 ga watan Yuli.
Cutar coronavirus ta Isra'ila ta kai 60,000 yayin da kamuwa da cutar ta tsallake
JERUSALEM (Reuters) - Adadin mutanen da za a yi wa gwajin cutar coronavirus a Isra'ila ya kai 60,000 a ranar Asabar yayin da gwamnati ke kokarin dakatar da sake kamuwa da cutar.
Sakamakon baya-bayan nan na yau da kullum ya nuna sabbin kamuwa da cutar 1,770 wanda ya kai adadin wadanda suka kamu da cutar zuwa 60,496, in ji ma'aikatar lafiya ta kasar.
Da yawan jama'a miliyan tara, Isra'ila ta ba da rahoton adadin mutane 455 da suka mutu sakamakon cutar.
Isra'ila ta kasance daya daga cikin kasashe na farko da suka sanya dokar kulle a duk fadin kasar kuma da farko ta yi nasarar dakile barkewar cutar.
Mutane da suka kamu da cutar a yau da kullum a cikin daruruwan sun ragu zuwa ƙananan lambobi biyu.
A cikin damuwa game da yawan tattalin arziki, gwamnati ta sauƙaƙe waɗannan ƙuntatawa - cikin sauri, wasu jami'ai sun yarda da hakan - sannan kuma kamuwa da cutar ta sake faruwa.
Sabunta rufe bangarori daban-daban na tattalin arziki ya zurfafa damuwar jama'a, ya haifar da zanga-zanga a kowace rana.
Dominic Raab: Gwamnati ba za ta iya neman gafara kan shawarar killace kasar Spain ba
Dominic Raab ya kare matakin da gwamnati ta dauka na sake gabatar da matakan killace kan kasar Spain a takaice.
Ministoci sun sanar a ranar Asabar cewa za a tilasta wa masu hutun da ba su dawo daga Spain da tsibirinta ba da tsakar dare su ware kansu na tsawon kwanaki 14.
Kasar ta kasance a cikin jerin kasashe masu "tafiya" da ake ganin ba za su iya ziyartar titin Downing ba, amma karuwar wadanda suka kamu da cutar coronavirus a baya-bayan nan ya haifar da fargabar kamuwa da cutar a karo na biyu.
A ranar Lahadi, Sakataren Harkokin Wajen ya kare sake sanya takunkumi kwatsam a matsayin " martani na ainihi" game da karuwar kamuwa da cutar da aka ruwaito a yankin.
Ya ce a lokacin an tantance lamarin a jiya da rana "kuma mun yanke hukuncin cikin gaggawa yadda za mu iya."
"Ba za mu iya neman gafara kan hakan ba", ya kara da cewa.
"Dole ne mu iya daukar mataki cikin gaggawa, musamman dangane da matsuguni, ko kuma kasa da kasa dangane da kasar Spain ko wata kasa, inda muke ganin dole ne mu dauki mataki.
"In ba haka ba, muna cikin hadarin sake kamuwa da cutar zuwa Birtaniya, mai yiwuwa tashin hankali na biyu a nan sannan kuma a sake kullewa."
Sakataren sufuri a tsakanin 'yan hutun Spain da aka tilastawa killacewa
An yanke hukuncin ne bayan da kasar Spain ta samu sabbin wadanda suka kamu da cutar Covid-19 sama da 900 a kullum na tsawon kwanaki biyu a guje.
Sakataren harkokin wajen ya yarda cewa an bar masu yawon bude ido da yawa ba su da lokacin sokewa ko canza shirin su.
"Na fahimci cewa rikice-rikice ne ga wadanda suke cikin Spain ko kuma suna tunanin tafiya amma dole ne mu iya daukar mataki cikin sauri don kare Burtaniya", in ji shi.
"Mun samu irin wannan ci gaba wajen sauke kwayar cutar da kuma hana sake kama kwayar cutar a Burtaniya."
Fasinjoji sun isa filin jirgin sama na Gatwick a ranar Lahadi da safe bayan sanarwar ranar Asabar (PA)
Sakataren Lafiya na Shadow Jonathan Ashworth ya yi Allah wadai da gwamnatin saboda yadda take gudanar da matakin.
Ya ce shawarar da Downing Street ta yanke ba zato ba tsammani ta sa masu hutun "na cikin damuwa da damuwa."
Kwamitin Kwadago ya fadawa Sophy Ridge cewa: "Na fahimci dalilin da ya sa suka yanke wannan shawarar amma, ba shakka, yadda aka yanke wannan shawarar a cikin sa'o'i 24 da suka gabata, gaskiya ne.
"Akwai masu hutu a Spain a halin yanzu cikin rudani da damuwa, akwai mutanen da ke gab da zuwa hutu zuwa Spain da tsibirai kamar Tenerife wadanda ke cikin rudani, kuma ba su san ko ma'aikatansu za su ba su damar killace kansu na makonni biyu ba.
"Gwamnati na cewa kawai, 'muna fatan ma'aikata su yi aiki tare.'"
"Yadda aka yanke wannan shawarar a cikin sa'o'i 24 da suka gabata, gaskiya abin kunya ne."
Menene kasancewar Spain a cikin jerin sunayen keɓewa ke nufi ga masu hutun?
Ya bukaci ministoci da su yi "kyakkyawan bayani" kan ko wadanda aka nemi su killace za su samu tallafin kudi idan ma'aikatan su suka ki biyan su a lokacin killacewar.
Ya kuma kara da cewa, ana bukatar bayanai a bayyane "ga wadannan 'yan hutun da a halin yanzu suke kasar Spain wadanda suka ajiye su yadda ya kamata a duk shekara don hutun iyalinsu wadanda ke cikin rudani da damuwa."
"Yadda aka sanar da wannan shawarar a bayyane yake haifar da damuwa", ya jaddada.
Mista Raab ya ce babu wani ma'aikacin da ke bin wannan sabuwar shiriya da ya kamata a hukunta ma'aikata, ciki har da biyan albashi mara lafiya.
Ya ce: "Muna sauya dokoki - an sauya dokar ne dangane da masu hutun da matafiya - kuma ba shakka muna sa ran ma'aikata za su nuna wa ma'aikatan da za su killace kansu saboda doka sassaucin da suke bukata."
"Idan wani yana bin doka dangane da killacewa da kuma kebe kansu yadda ya kamata, ba za su iya daukar hukunci a kansu ba."
QB Herbert daga cikin zane-zane 4 da masu caji suka sanya hannu
COSTA MESA, Calif. (AP) - Masu caji na Los Angeles sun sanya hannu kan takardunsu guda hudu, ciki har da Justin Herbert, kuma sun amince da yarjejeniyar da sauran 'yan biyu na ajin su.
Masu cajin sun samu damar yin kwangila da ajin da suka dauka a ranar Asabar a lokacin da suka kai rahoton zuwa sansanin horar da likitoci da kayan aiki.
Tare da Herbert, wanda aka zaba a matsayin na shida a gaba daya, kungiyar ta sanar da sanya hannu kan masu karbar bakuncin Joe Reed (a zagaye na biyar) da kuma KJ Hill (a zagaye na bakwai) tare da mai tsaron gida Alohi Gilman a zagaye na shida.
Sun amince da yarjejeniyar tsayawa takara a zagayen farko na linebacker Kenneth Murray Jr. da kuma tseren baya Joshua Kelley, wanda aka zaba a zagaye na hudu.
Herbert ya fara wasanni 42 a Oregon, inda ya tattara rikodin 29-13 tare da yadudduka 10,541 da kuma 108.
Ya jagoranci Ducks zuwa gasar Pac-12 a kakar da ta gabata, inda ya jefa 32 touchdowns da kuma shida interceptions a wasanni 14.
Ya yi nasara a kan Wisconsin a cikin Rose Bowl, inda ya yi gudu don uku touchdowns kuma aka kira shi MVP mai laifi.
Herbert zai fafata da tsohon soja Tyrod Taylor domin fara aiki.
Masu caji za su sami sabon kwata-kwata bayan da Philip Rivers ya tashi ta hanyar kamfanin dillancin labarai na kyauta bayan kakar wasanni 14 a matsayin farawa.
Murray shi ne na 23 a gaba daya bayan da Los Angeles ta yi ciniki da New England domin komawa zagayen farko.
Ya kasance dan wasa na uku na kungiyar Associated Press All-America a kakar da ta gabata bayan ya jagoranci Sooners tare da buga wasanni 102, ciki har da kashi 69.
Kanye West ya ce zai iya doke Joe Biden "kashe rubutu" - RT USA News
Jarumin fina-finan Hausa Kanye West ya sake shigar da kara a shafinsa na dandalin sada zumunta na dandalin sada zumunta na dandalin sada zumunta na Twitter, inda ya ce zai iya doke Joe Biden a kan kuri'un da ya rubuta shi kadai.
Kwanaki bayan sanar da sabon faifai da kuma bayyanar da cewa yana kokarin saki matar Kim Kardashian na tsawon shekaru biyu, Kanye West ya sake mai da hankalinsa ga yakin neman zaben shugaban kasa na 2020 a ranar Asabar, a cikin wata sanarwa mai dauke da sa hannun "I CAN BEAT BIDEN OFF OF WRITE INS".
Idan har kasashen yamma suna da matukar muhimmanci wajen tsayawa takarar shugabancin kasar, to kuwa kuri'un da aka rubuta za su iya zama tafarkinsa na nasara, ko kuma kowane irin nunawa.
Rapper ya sanar da tsayawarsa takara ne a ranar 4 ga watan Yuli, bayan wa'adin da ya wuce na tsayawa takara a akalla jihohi shida.
Duk da haka, West ya matsa gaba tare da shigar da takardun da suka dace a Hukumar Zabe ta Tarayya (FEC), kuma ya sami nasarar samun sunansa a rumfunan zabe a Oklahoma.
Tun daga wannan lokacin ne ya ke gudanar da gangamin yakin neman zabe, a yayin da ya ke jawabi ga taron jama'a da ke sanye da rigar harsashi, inda ya ke gabatar da jawabinsa ba tare da makirufo ko podium ba.
Kasashen yamma sun fito kan batun zubar da ciki, suna kuka yayin da ya ke gabatar da wani sakon kirista da ya ce zai sa kafofin watsa labarai su "gaya muku cewa ni mahaukaci ne."
Har ila yau a rt.com Kanye West ya yi ikirarin cewa ya yi kokarin kashe Kim Kardashian, ya zargi ita da surukinta "Kris Jong Un" na WHITE SUPREMACY
Hakan ya kasance gaskiya, kuma an kwatanta gangamin da kasashen yamma suka yi a dukkanin shafukan labarai da kuma masu tsegumi a matsayin abin da ya shafi jama'a, tabbacin rashin lafiyar kwakwalwa, ko kuma duka biyun.
Sai dai wani zabe na baya-bayan nan ya sanya kasashen yamma a kashi biyu cikin dari a duk fadin kasar, wuya da wuya tare da Jo Jorgensen na jam'iyyar 'yan sassaucin ra'ayi da kuma maki a gaban Howie Hawkins na jam'iyyar Green.
Duk da cewa ba zai yiwu ya zarce kashi 48 cikin dari na Joe Biden ba, amma a ka'idar zai iya rabuwa da isassun kuri'u daga Biden don ganin Shugaba Donald Trump ya hau karagar mulki a wa'adi na biyu - wani abu da masana a bangarorin biyu ke zargin mai yiwuwa shi ne shirinsa.
Koriya ta Arewa ta kaddamar da dokar ta-baci yayin da aka samu rahoton kamuwa da cutar Covid-19
Shugaban Koriya ta Arewa Kim Jong-un ya gudanar da wani taron siyasa na gaggawa bayan mutumin da ake zargi da cutar Covid-19 ya dawo daga Koriya ta Kudu bayan ya tsallaka kan iyaka ba tare da izini ba a wannan watan, in ji kafofin watsa labarai na jihohi a ranar Lahadi.
Idan aka tabbatar da hakan, zai zama shari'a ta farko da hukumomin Koriya ta Arewa suka amince da ita a hukumance, wadanda ya zuwa yanzu suka ce kasar ba ta da tabbacin kamuwa da cutar coronavirus.
Kim ta kaddamar da dokar ta-baci sannan ta sanya dokar kulle a garin Kaesong da ke kan iyaka, inda ta kira shi a matsayin "matsanancin halin da za a iya cewa mugunyar kwayar cutar ta shigo kasar," in ji kamfanin dillancin labarai na jihar KCNA.
A cewar KCNA, mutumin da ya tsallake rijiya da baya zuwa Koriya ta Kudu shekaru uku da suka wuce ya dawo kan iyaka mai tsawo da ta raba Koriya biyu da alamun cutar Covid-19.
"Wani lamari na gaggawa ya faru a garin Kaesong inda wani rudu da ya je kudancin kasar shekaru uku da suka wuce, mutumin da ake zaton ya kamu da mugunyar kwayar cutar ya dawo a ranar 19 ga watan Yuli bayan ya tsallake layin dogo ba bisa ka'ida ba", a cewar KCNA.
KCNA ba ta fadi takamaiman ko an yi wa mutumin gwaji ba, amma ta ce "an samu wani sakamako da ba a tabbatar da shi ba ne daga binciken likitoci da dama na sirrin sashin numfashi na sama da jinin mutumin", wanda hakan ya sa jami'ai suka killace mutumin tare da bincika duk wanda wataƙila ya yi hulɗa da shi.
Koriya ta Arewa ta karbi dubban kayan gwajin cutar coronavirus daga Rasha da wasu kasashe, ta kuma sanya tsauraran matakan rufe kan iyakoki.
An killace dubban mutane a cikin al'ummar sirri, amma a baya-bayan nan an sassauta dokar hana fita.
A cikin 'yan makonnin nan, Koriya ta Arewa ta kuma kara wani yunkuri na sukar 'yan gudun hijira zuwa Koriya ta Kudu a matsayin "masu cin zarafin dan adam" tare da yin kira ga Koriya ta Kudu da ta yi fatali da kungiyoyin da ke aika sakonnin farfaganda da taimakon abinci zuwa Arewa.
Kim ya ba da umarnin gudanar da bincike kan rukunin sojojin da ke bakin iyakar inda ake zargin mutumin da tsallakawa don "zartar da hukunci mai tsanani da kuma daukar matakan da suka dace."
Paul Pogba ya yi karin haske kan makomarsa bayan da Man Utd ta rufe gasar zakarun Turai
Dan wasan Manchester United Paul Pogba ya ba da shawarar cewa zai ci gaba da zama a kungiyar a wannan bazara bayan da Red Devils ya rufe matsayi a cikin manyan hudu.
Samun nasara a kan Leicester da ci 2-0 ya sa United ta zama ta uku, a gaban Frank Lampard Chelsea.
United ta kasance maki 14 daga Leicester a wasanni 12 da suka gabata, amma wani tsari mai ban mamaki ya sa Red Devils ta kammala a cikin manyan hudu.
An sa ran Pogba zai bar kungiyar a bazarar nan bayan ya nemi ya bar kungiyar sau biyu a cikin shekaru biyu da suka gabata.
Sai dai annobar na nufin kungiyoyi kalilan ne za su kashe kudade masu yawa a wannan bazara kuma babu wani mai saye da zai iya hada kudin canja wurin da kuma albashin Pogba don yaudare shi daga Old Trafford.
Wannan karin haske ya taimakawa Pogba a 'yan makonnin nan yayin da wasannin da ya yi, da kuma yaren jikinsa suka inganta.
Kuma dan Faransa ya yi watsi da sabuwar alamar da ya nuna cewa zai ci gaba da zama a kulob din ta hanyar aikawa a shafinsa na Instagram bayan nasarar da kungiyarsa ta samu da ci 2-0.
Duk da yake mai yiwuwa Pogba ya yi murnar komawar kungiyar zuwa gasar, magoya baya da yawa suna fassara hakan a matsayin wata shawara mai karfi cewa har yanzu zai kasance a kulob din yayin da suke sake fafatawa da zakarun Turai.
Pogba yana da shekara daya a kan yarjejeniyar da ya kulla, duk da cewa kulob din zai iya tsawaita hakan da watanni 12 ma'ana yana da shekaru biyu yadda ya kamata.
United na sha'awar tsawaita yarjejeniyar Pogba kuma suna son karin haske kan halin da yake ciki kafin kakar wasa mai zuwa.
Pogba a nasa bangaren yana jin dadi a kulob din kuma zuwan Bruno Fernandes ya samu karbuwa.
Dan wasan dan kasar Portugal ya kasance abin da ya faru a Old Trafford kuma zuwansa ya ba Pogba damar taka leda a tsakiyar filin wasa mai zurfi, wanda kuma ya inganta yanayinsa.
