PM India zai halarci bikin faretin ban kwana na haikali a wani wuri da ake takaddama akai
New DELHI (AP) - Firayim Ministan Indiya Narendra Modi zai halarci wani gagarumin biki a wata mai zuwa na wani haikalin 'yan Hindu a wani wuri da ake takaddama a kansa a arewacin Indiya inda aka rushe wani masallaci na karni na 16 a hannun 'yan Hindu masu wuyar sha'ani a shekarar 1992, a cewar dogarawan da ke kula da aikin ginin haikalin.
An shirya bikin ne a ranar 5 ga watan Yulin, ranar da masu shirya bikin suka ce abin mamaki ne ga mabiya addinin Hindu, amma kuma hakan na zuwa ne a dai-dai lokacin da majalisar dokokin Indiya ta sake farfado da matsayinta na kasa mai cin gashin kanta na jiha daya tilo da Musulmai suka fi yawa, Jamhuriyyar Dimokradiyyar Congo.
Wannan alamari ba zai yiwu a rasa magoya baya da kuma masu adawa da jam'iyyar Modi ta mabiya addinin Hindu Bharatiya Janata Party, ko kuma BJP ba, wadanda bayyanarsu ta shafe shekaru da dama suna kunshe da alkawarurrukan da suka dauka na tsame mulkin Kashmir da kuma gina haikali ga Hindu allah Ram inda masallacin Mughal-era ya taba tsayawa, wani wuri a birnin Ayodhya da ke jihar Uttar Pradesh da 'yan uwa suka yi imanin cewa nan ne wurin haihuwar Ram.
Saboda har yanzu cutar Koronabirus na ci gaba da yaduwa a fadin Indiya, wacce ta bayar da rahoton bullar cutar a matsayin irinta ta uku a duniya, bikin za a yada shi ne kai tsaye a gidajen talabijin na kasar kuma za a takaita yawan mahalarta da kuma 'yan kallo, a cewar Vishwa Hindu Parishad, ko kuma kungiyar Hindu ta Duniya, wata kungiyar 'yan kishin Hindu da ke kawance da jam'iyyar BJP.
Haikalin zai zama "cibiyar jituwa ta zamantakewa, da hadin kan kasa da hadewa da kuma farkawa daga jin yaren Hindutva", ko kuma hanyar rayuwar Hindu, a cewar mai magana da yawun kungiyar Vinod Bansal a wata sanarwa da ya fitar a ranar Asabar.
An sasanta rikicin da aka kwashe tsawon lokaci ana yi a kan wurin a shekarar da ta wuce bayan nasarar da jam'iyyar BJP ta samu a zaben da aka yi a kasar.
A watan Nuwamba, Kotun Kolin ta yanke hukunci a kan amincewa da dogaro da haikalin, tana mai cewa za a bai wa Musulmai robobin da yawansu ya kai eka biyar a madadin wurin.
Mabiya addinin Hindu masu sassaucin ra'ayi sun dade suna tunanin cewa 'yan mamaya Musulmai 'yan Mughal sun gina masallaci a saman wani haikali da ake da shi a tsohon birnin Ayodya.
Wata tarzoma da aka yi a watan Disamba na shekarar 1992 bayan hallaka limamin masallacin ta janyo tashin hankali a tsakanin al'umma inda aka kashe kimanin mutane 2,000, galibinsu Musulmi.
A halin da ake ciki kuma, ana ci gaba da sauraron shari'ar da ake yi a kotun rushe shari'ar a wata kotu ta musamman.
Wani mai aikin gine-gine daga Ahmedabad, jihar Gujarat, jihar Modi, ya samar da wani tsarin sandstone mai tsawon kafa 161 (mita 49) tare da wasu yankuna biyar.
Ministan birnin Yogi Adityanath, Uwargida Pradesh kuma mai bin addinin Hindu, ta buƙaci Ayodhya da ta gudanar da bikin tsaftacewa da tsarkakewa na musamman da kuma dukkanin haikalin birnin don haskaka fitilun mai gabanin ziyarar Modi, Kamfanin dillancin labarai na Press Trust na Indiya ya ruwaito.
Adityanath ya ce bikin na bana ya kawo karshen "gwagwarmayar da aka kwashe shekara 500-ana yi", a cewar PTI.
Barazana ga dimokuradiyyar Australiya ta fi kusa da gida fiye da kasar Sin
Amma jerin matakan da aka zartar a baya-bayan nan ko kuma aka zartar a zauren majalisar Commonwealth ya ba da damar nuna damuwa game da wannan hukumci namu, na gida-gida da aka yanke.
Sun hada da fitar da fasahar gane fuska, da tilastawa kamfanonin fasaha ragargaza bayanan da aka gudanar kan tsarin komfutar abokan huldarsu, da tilastawa kamfanonin fasaha samar da damar amfani da bayanan abokan huldarsu ba tare da sanarwar mai dauke da bayanan ba da kuma mikawa ASIO ikon tambayarsa ta tilas.
Wadannan matakai sun janyo tambayoyi masu tsanani game da iyaka tsakanin 'yan kasa da gwamnati, amma kudurin ASIO abin damuwa ne ainun.
Ba kamar sauran kasashe Biyar ba - Amurka, Kanada, Ingila da New Zealand - a farko-farkon 11 ga watan Satumba, an baiwa ASIO ikon tilastawa mutane yin tambayoyi har na tsawon kwanaki bakwai dangane da laifukan ta'addanci.
Duk da cewa za a iya yarda da cewa tsananin zaluncin da ke tattare da kashe-kashen ta'addanci ya tabbatar da ikon al'umma - zalunci mai tsanani aƙalla yana ba da iyaka mai haske a kusa da waɗannan manyan ƙasashe.
Wannan hakika ba za a iya fada ba game da ma'anar "dadi da annoba" da aka yi amfani da su a cikin wannan kudurin doka don jawo ikon tambaya na tilas: Magance bayanan da ke nuna wariya ga "dangantakar siyasa, soja ko tattalin arziki na Australia da wata kasa"; ko ayyukan da ke aiki tare da haɗin gwiwar ikon kasashen waje waɗanda suke da akida ko yaudara kuma suna da "ƙyama ga bukatun Australia".
Yana da wuya a yi tunanin cewa dokokin "zaƙi da annoba" na tsaron ƙasa "sun fi wannan.
Za a kyale ASIO ta tilastawa kowa yin tambaya kan wadannan abubuwa - ba wai kawai wadanda ake zargi da laifi ba.
Hakan ya hada da ƴan jarida da ƴan kasuwa da malaman jami'a da kuma ma'aikata da lauyoyi da ƴan kasa da mazauna unguwanni da kuma baki.
ASIO kawai sai ta nuna tambayar za ta "taimaka ainun ga tarin basira" game da katsalandan din kasashen waje, wanda da alama shi ne babban makasudin kudirin.
Sannan za a iya yi wa mutumin tambayoyi har na tsawon awanni 40 (ba ciki har da na karya ba).
Idan kuma mutumin ya ki halarta, to za a kama su.
Kin amsa ko bayar da amsoshin karya ko na yaudara zai dauki hukuncin daurin shekara biyar a gidan kaso.
Ka'idojin da suke da muhimmanci a tsarinmu na shari'a - hakika tsarin mulki a Amurka ya ba mu kariya - wannan kudurin doka ya yi watsi da shi.
Mutanen - ciki har da mutanen da tuni ke fuskantar tuhuma - za a tilastasu bayar da shaidar da watakila sai an yi amfani da ita wajen gurfanar da su a gaban kuliya.
Da za su iya samun lauya a wurin, amma lauyan zai yi daidai da ya bayyana tambayoyin da suke da buri ko kuma ba a sani ba.
Sabon kudirin dokar ya sauya matakin bayar da takardar sammacin tuhumar daga alkali zuwa Atoni Janar.
Kamar yadda Sufeto Janar na Leken Asiri da Tsaro ya nuna, wannan "ya tashi daga yanayin don ƙarin bukatun neman izini na waje a cikin wasu hukunce-hukuncen Biyar na Idanu".
Hakan kuma ya sabawa ka'idar rabuwa da iko da kotuna ke yi wajen yin kwaskwarima ga ayyukan gwamnatin zartaswa.
Sabon kudurin ya kuma tanadi fadada ikon tambayoyin ga yaran da shekarunsu suka kai akalla 14 da haihuwa, amma sai ga wadanda suka tsunduma ko watakila suna ayyukan nuna wariya ga kariyar Australia da kuma mutanen da ke cikin tashin hankalin da ke da nasaba da siyasa.
Duk da cewa hukumominmu na tattara bayanan sirri su ne mafiya kyau a duniya, wadanda suka kunshi ikon tilastawa kowa yin tambaya game da bayanan da ke cewa "nuna wariya ga dangantakar tattalin arzikin Australia da wata kasa", ko ayyukan da suke "dakushe muradun Australia" sun fi gaban a yi su.
Mu kadai muka tsaya takara.
Babu wata kasa ta Biyar da ta je har yanzu, ba ma ga laifukan ta'addanci ba.
'Yan rajin kare demokaradiyya masu sassaucin ra'ayi na hakika na tsare tsaren matakan kariya daga hukuma.
Halin ko in kula da jami'an tsaron mu ke nunawa dangane da bulaliyar majalisar Timor ta Gabas, da shari'ar Witness K da Bernard Collaery, da shari'ar da ake yi a asirce da kuma daure wani tsohon jami'in tattara bayanan sirri a kurkuku, da binciken na baya-bayan nan da aka zartar a kan wasu 'yan jarida biyu, da kuma tsammanin tuhumar da ake yi wa daya daga cikin su dangane da labaran da ake zargin sojojin Australiya da aikatawa a Afghanistan ya nuna dalilin da ya sa ba za mu yi kasa a gwiwa ba wajen kare kan mu.
Coronavirus Travel Update: Wadanne Kasashe Ne Suke Da Karfin Tafiye-tafiye Ga Masu Bulaguro Saboda Shigowa Kasar
Yawan kasashen da ke saka dokar takaita tafiye-tafiye na karuwa.
Ya zuwa wannan makon, Jamhuriyar Czech na so a yi gwajin cutar Koronabirus ga ma'aikatan yanayi na Bulgaria.
Denmark ta ba 'yan Bulgaria da ke yankinta damar ne kawai idan suna da rijistar adireshi a can, kwangilar aiki ko kuma takardar shaidar tafiya kasuwanci.
Ya zuwa yau, mutanen da suka ziyarci Bulgaria da Romania a cikin kwanaki 14 da suka gabata suna ƙarƙashin kulawar da aka yi a Italiya.
A Finland, shigarwa ne kawai don "dalili mai inganci".
Killace gida dole a Austria, duk da gwajin PCR mara kyau da aka yi.
Tuni dai aka bukaci hakan ga wadanda suka shiga Jamus din.
A cikin kwanaki 14 masu zuwa, an hana damar shiga kudancin Romania ba tare da kyakkyawan dalili ba.
Kuma kasar Girka ta tsaurara matakai har illa ma sha Allahu a kan iyakokin kasarta.
Daga ranar Talata, wadanda ke tafiya ta jirgin sama daga Bulgaria zuwa Girka za su gabatar wa hukumomin kan iyakar Girka sakamakon gwajin da aka yi musu na cutar Koronabirus, wanda aka yi har na tsawon awanni 72 kafin shigowarsu makwabciyar kasarmu ta kudu, kamar yadda Ma'aikatar Harkokin Waje ta sanar.
Sun kuma kara da cewa fasinjojin da suke da shaidar yin irin wannan gwajin ne kadai za a bari a kasar nan.
Dole ne a bayar da shi a harshen Ingilishi kuma yana dauke da sunaye da lambobi uku na fasfo din fasinjan ko katin shaidar daukar fasinja.
Hukumomin makwabciyarmu ta kudu ba za su amince da takardun shaidar cewa ba su cika wadannan ka'idoji ba
"Ya kamata a yi wa matafiya gwaji a dakin gwaji na RT-PCR ta hanyar shan aski daga baki ko hanci".
Za a gane gwaje-gwaje na coronavirus idan an yi su a dakunan bincike na kasa, dakunan gwaje-gwaje na kiwon lafiya na kasa ko dakunan gwaje-gwaje masu zaman kansu waɗanda aka girmamasu ta hanyar takardun aiki na kasa da suka dace (ba lallai ba ne musamman ga COVID-19).
Wannan mataki bai shafi 'yan kasar ta Girka da 'yan kasar da ke zaune a Girka da kuma matafiya ba saboda wasu muhimman dalilai na sana'a.
Ma'aikatar harkokin wajen kasar ta Girka ta kuma sanar da cewa a ranakun Talata 28 ga watan Yuli da kuma Laraba 29 ga watan Yuli za a gwada fasinjojin da basu da lokacin yin gwajin kafin tafiyar tasu, hukumomin kasar ta Girka ne za su gwada lafiyar su bayan isowarsu kasar ta Girka.
Bukatar da ake da ita ga 'yan kasar da ke tafiya ta jirgin sama zuwa Girka da su cika akalla awanni 24 a ci gaba da aikin samar da lantarki na'Passenger Location Form (PLF) da ke samar da lambar QR, wacce suke gabatarwa ga hukumomin Girka kan su shiga kasar, ta ci gaba da aiki.
An wallafa karin bayani a shafin matafiyar.gov.gr
A lokacin babu wani sauyi da aka samu a bukatun da ake da su na tsallaka iyakokin kasar tsakanin Bulgaria da Girka.
"Matafiya zuwa Girka a kan iyakar kasar, ko da kuwa 'yan kasarsu ne, dole ne kuma su cike fom din yantar da fasinja na lantarki (PLF) da ke samar da lambar QR akalla awanni 24 kafin isowarsu", Ma'aikatar Harkokin Waje ta bayyana.
Rufe wuraren binciken ababen hawa na Ilinden, Kapitan Petko Voyvoda da Makaza ya kara yawan zirga zirgan ababen hawa a kan iyakar kasar kusa da Petrich.
Babu wata matsala game da sauyin shekar.
Babu wata nakiya da manyan motoci ke yi.
Duk wadanda ke jira su tafi cikin teku a Girka.
Matafiya suna jira kusan awa daya da rabi don su tsallaka Hasumiyar Tsaro.
Uku daga cikin wuraren da ke kan iyakar Bulgeriya da Girka na aiki.
Kawai "Ilinden - Exohi" da kuma wannan ɓangare na Ivaylovgrad an rufe.
Yi gargadi game da kayan lambu masu ban sha'awa da ke da kyau
Yana iya zama wani abin kunya ga wani masanin kimiyyar shuka ya yarda, amma ni duka mai tsotsa ne ga gimmick lambu.
Ina son in yi tunanin cewa saboda ina bude-baki ne ko kuma watakila kawai ina da kyakkyawan fata, musamman ma yadda abubuwa da yawa a duniyar shuka a wasu lokutan suke da matukar takaici.
Amma ba na jin kunyar in ce na fado musu da dama a tsawon rayuwa a harkar wake-wake.
Duk da yake na yi imani da darajar gwada abubuwa da kanka, idan ba ka zato koyon hanya mai wuya, ga wasu daga cikin mafi na kowa lambu gimmicks na zo a fadin.
Da farko dai, kuma watakila mai laifi ne mafi muni, wanda ya yi shuke-shuken tumatir da dankalin turawa.
An bayyana shi a matsayin wata nasara ta juyin juya hali, nika tumatir a kan tushen dankalin turawa shine, tsohuwar ilimin kwalam na makaranta, wanda ya koma aƙalla shekarun 1920s.
Kamar yadda dukkanninsu daga iyali daya suke, suna kuma da wani nau'in "plumbing" na ciki, hakika za ka iya samar da irin wannan abin al'ajabi na inganta tiyata.
Amma ga matsalar: Samar da tsarin hanya mai zurfi kamar 'ya 'yan itatuwa da tushensu na ɗaukar makamashi mai yawa na metabolic, kuma idan tsire-tsire na ƙoƙarin yin duka iyakacin kuzarinsu babu makawa sai sun zama rababbu.
Wannan yana nufin amfanin wadannan tsire-tsire masu ban tsoro ne kuma babu wani abu mai kama da abin da ka ke gani a cikin hotunan tallan.
Sannan akwai gaskiyar cewa amfanin gonar ya manyanta a farashi daban-daban, domin girbin yazawa sai ka kashe shuke-shuken kafin tumatir din ya yi tashin gwaron zabi.
A kan batun tunanin kasuwanci, da akwai dodanni masu yawa da ke tafe a nan, su ma.
Na ga roses Photoshopped sama blue da kuma 'ya 'yan itatuwa da physiologically ba zai yiwu ba adadin 'ya 'yan itace a kan rassansu a cikin wasu manyan kasidu.
Na ma ga hotunan da aka "karbo" daga shafina na sada zumunta na Instagram da kuma amfani da su ta hanyoyin sadarwar zamani a matsayin hotunan filayen jarabawarsu.
Abin baƙin ciki shine aikin ƙananan kamfanoni masu sana'a na nufin cewa dole ne ka duba hotunan talla, musamman a kan layi, tare da idon basira.
Idan ya yi kyau ainun ya zama gaskiya, watakila haka ne.
Da yake magana game da wanann, launin shudi ba shi da wuya a duniyar Botanical, don haka idan ka ga wani sabon fata mai dausayi, ko orchid ko cactus, yana haskakawa a cikin mafi tsananin "cututtuka" inuwar shudi, kusan an fesa shi ko kuma ya mutu.
Wanda hakan zai yi kyau, muddin masu sana'ar suka bayyana hakan, amma da wuya su taba yin hakan.
Blue moth orchids za su sake komawa zuwa ga asali fari, amma fesa cacti da heathers, mai rufi a cikin wani haske-suppressing Layer na fenti, ba za su iya tsira ba har tsawon lokaci.
A karshe dole in daga tutar kayan bonsai ko kuma ma fi muni, bonsai iri, wannan alkawari na kananan itatuwa za su yi ta fitowa daga fakitocinsu.
Bonsai ba nau'in shuka ba ne.
Dabara ce ta horaswa da ake amfani da ita wajen ba da illar tsoffin itatuwa a kan tsaunuka masu nisa.
Kusan a ko da yaushe ana soma su ne daga balagaggun shrubs da ake hacked back da kuma wani sabon ci gaban da aka samu a wurin.
Na san zan ci gaba da fadowa don gimmicks, yana da wani ɓangare na jin dadi na gwaji.
Amma gefe-mataki wadannan kuma za ka iya samun wanda a zahiri ya ke da damar cika alkawarin da ya dauka.
Kotu ta banka wuta a yayin zanga-zanga a California
Oakland, Ca. - Masu zanga-zanga a California sun cinnawa wata kotu wuta, inda suka lalata ofishin 'yan sanda tare da farma jami'an 'yan sanda bayan da zanga-zangar lumana ta tsananta da yammacin ranar Asabar, in ji 'yan sandan Oakland.
Masu zanga zangar sun farfasa tagogi, da fesa fentin gwal, da harba abubuwan tartsatsin wuta da kuma nuna lasifikoki ga jami'ai, a cewar wani ma'aikaci a Oakland a shafinsa na Twitter.
Tweets da dama sun yi kira da a zauna lafiya kuma sun nemi masu tsare-tsare da su "taimaka mana wajen samar da wurare masu hadari da kuma wurare masu hadari ga masu zanga-zanga".
Zanga-zangar ta soma ne da yammacin ranar Asabar tare da kungiyoyi irin su "Wall of Moms", kama daga wata kungiya da ta kafu a Portland da ke Oregon, yayin da masu zanga-zangar suka fusata tare da tura jami'an Amurka zuwa wannan birni domin tsare wata kotun tarayya.
Shugaban Amurka Donald Trump ya aike da jami'an tsaro na tarayya domin matsa kaimi kan zanga-zangar da ta auku ba kakkautawa tun bayan mutuwar George Floyd a Minneapolis a ranar 25 ga watan Mayu.
Zanga-zangar da aka yi a Oakland an fara ta ne cikin lumana, amma ta rikide ta koma tashin hankali daga baya zuwa dare.
'Yan sanda sun sanar da yin "taro ba bisa ka'ida ba" da misalin karfe 11: 30 na dare kuma jami'ai sun nemi jama'a da su watse.
Wutar dajin ta tashi ne a wata babbar kotu da ke Alameda County Superior Courthouse kuma an dauke ta bayan wani dan lokaci, kamar yadda kafafen yada labarai suka ruwaito.
'Yan sanda sun ce masu zanga-zangar a wani lokaci suna "farfasa tagogi suna kuma rera wakokin nuna wariyar launin fata ga mazauna wurin".
Hotunan da sashen ya sa a shafinsa na dandalin sada zumunta na Tuwita sun nuna yadda aka fasa gilashi da kuma fenti a wani ginin 'yan sanda.
An Gabatar Da Tsauraran Matakan Tsaro a Wajen Taron Amurka a Chengdu, China
An dai tsaurara matakan tsaro a kofar ofishin jakadancin Amurka da ke birnin Chengdu na kasar China a yau Lahadi, yayin da ma'aikatan Amurkan ke shirin barin wurin.
An ga wasu manyan motoci masu motsi guda uku sun shiga harabar ginin, yayin da 'yan sanda marasa matsuguni da shinge suka hade bangarorin titin biyu, wadanda aka lullube su da shingayen karfe.
Editan jaridar Global Times ta kasar Sin ya tabattar da cewa, an baiwa ofishin jakadancin Amurka dake birnin Chengdu wa'adin sa'o'i 72 da ya rufe, ko kuma har zuwa karfe 10 na safe (0200GMT) Litinin 27 ga watan Yuli.
Kasar Sin ta yi zargin cewa, wasu ma'aikata da ke shawarwarin Chengdu suna "gudanar da ayyuka ba tare da la'akari da asalinsu ba".
Ba tare da bayar da wani cikakken bayani ba, mai magana da yawun ma'aikatar harkokin wajen kasar Sin, Wang Wenbin ya ce, irin wannan aiki ya yi katsalandan a harkokin kasar Sin, ya kuma cutar da muradun tsaron ta.
A ranar Juma'a ne aka bayar da umarnin kasar Sin na rufe shawarwarin a birnin Chengdu, a wani mataki na ramuwar gayya kan umarnin da Amurka ta bayar na rufe ofishin jakadancin kasar Sin dake birnin Houston na jihar Texas.
Washington ta umarci China da ta rufe ofishin Houston "don kare martabar ilimin Amurka da kuma bayanan sirri na Amurkawa".
Yayin da rufe ofishin jakadancin kasar Sin da ke Houston ya soma aiki a ranar Juma'a, an ga wasu gungun mutane da suka bayyana cewa jami'an Amurka ne sun yi raga-raga da wurin ta kofar baya.
Wang ya ce, a ranar Asabar, hakan ya sabawa yarjejeniyoyin kasa da kasa da na shiyya-shiyya, kuma kasar Sin za ta mayar da martani, ba tare da ta fayyace yadda za a yi ba.
Rufewar titinan ya kara zafafa takaddamar da ke tsakanin kasashen biyu kan batutuwan da suka jibanci cinikayya da masana'antu da kuma kare hakkin bil adama.
Un ta ce dubban masu tsatstsauran ra'ayi ne a Afghanistan
Wani rahoto na Majalisar Dinkin Duniya ya ce sama da 'yan Pakistan 6,000 ne ke boye a Afghanistan, mafi yawansu na hannun kungiyar Taliban ta Pakistan da aka dorawa alhakin kai wa sojin Pakistan da fararen hula hari.
A rahoton da ta fitar a wannan makon ta ce kungiyar da ake kira Tehreek-e-Taliban (TTP), ta na da alaka da kungiyar IS mai da'awar kafa daular musulunci a Afghanistan.
Wasu daga cikin 'ya 'yan kungiyar ta TTP har sun shiga cikin kungiyar ta IS wacce ke da hedikwatarta a gabashin Afghanistan.
Gwamnatin Afganistan ba ta mayar da martani ba a ranar Lahadi kan buƙatun da kamfanin dillancin labaran Associated Press ya yi mata na neman afuwa.
Rahoton ya ce kungiyar IS a Afghanistan wacce aka fi sani da IS a lardin Khorasan, ta sha da kyar daga jami'an tsaron Afganistan da kuma dakarun Amurka da na NATO, har ma a wasu lokutan kungiyar Taliban ta Afganistan.
Tawagar masu sa ido kan harkokin nazari da takunkumi ta Majalisar Dinkin Duniya ce ta shirya rahoton, inda ta ke bin diddigin kungiyoyin ta'addanci a duniya.
Rahoton ya kiyasta cewa membobin kungiyar IS a Afghanistan sun kai 2,200, kuma yayin da aka fatattaki shugabanninta, har yanzu kungiyar IS na kirga shugabanninta wani dan asalin kasar Syria Abu Said Mohammad al-Khorasani.
Rahoton ya kuma ce tawagar masu sa idon ta samu bayanan da ke cewa wasu manyan kwamandojin IS biyu, Abu Qutaibah da Abu Hajar al-Iraqi, sun iso Afghanistan daga Gabas ta Tsakiya a baya-bayan nan.
"Duk da cewa a yankuna koma baya, (gwamnatin Musulunci) ta kasance mai iya kai hare-hare masu yawan gaske a sassa daban-daban na kasar, ciki har da birnin Kabul.
Hakan kuma na nufin janyo hankalin mayakan Taliban da ke adawa da yarjejeniyar da Amurka ", a cewar rahoton, yana nufin yarjejeniyar zaman lafiya da Amurka ta sanya wa hannu da Taliban a watan Fabarairu.
An ƙulla wannan yarjejeniyar ce domin baiwa Amurka damar kawo ƙarshen ta'asar da ta kwashe shekaru 19 ta na yi a Afghanistan, kuma ta na kira ga Taliban da ta ba ta tabbacin cewa ƙungiyoyin ta'addanci ba za su yi amfani da yankinta ba.
Ana kuma sa ran yarjejeniyar za ta ba da tabbacin shigar 'yan Taliban cikin yakin da ake da IS baki daya.
Bangare na biyu kuma watakila mafi mahimmanci a cikin yarjejeniyar ya bukaci tattaunawa tsakanin 'yan Taliban da shugabanin siyasar Kabul.
Da maraicen Asabar, Ma'aikatar Harkokin Wajen Amurka ta bayar da sanarwar cewa, babban jami'inta na wanzar da zaman lafiya Zalmay Khalilzad ya sake kutsawa ta cikin yankin yana mai neman tsallake fara wadannan shawarwari, wadanda aka dade ana dagawa yayin da bangarorin biyu ke matsi kan shirin sakin fursunoni.
Yarjejeniyar da ke samun goyon bayan Amirka ta bukaci gwamnatin Afganistan da ta saki fursunoni 'yan Taliban 5,000 sannan kungiyar Taliban ta 'yantar da ma'aikatan gwamnati da na soji 1,000 a matsayin abinda ta kira kyakkyawar manufa gabanin tattaunawa.
Har ya zuwa yanzu gwamnati ta ki sakin fursunoni 'yan Taliban kusan 600 da ta kira masu aikata manyan laifuka kuma ta yi tayin ba su wasu hanyoyi na kyauta.
'Yan Taliban dai sun ki amincewa.
"Jam'iyyun sun fi kusa da fara tattaunawar shige-da-fice a Afganistan, muhimmin mataki na gaba da zai kawo karshen yakin da Afghanistan ta kwashe shekaru 4 ta na yi", a cewar sanarwar da Ma'aikatar Harkokin Wajen Amurka ta fitar.
"Duk da cewa an samu gagarumin ci gaba a kan mu'amilla da fursunoni, amma batun na bukatar karin kokari wajen ganin an magance matsalar".
Mai magana da yawun 'yan siyasa na kungiyar Taliban a farkon makon nan ya ce a shirye ya ke ya tattauna da shugabannin siyasa na birnin Kabul bayan da aka kammala hutun Sallar Idi al-Adha a karshen watan nan, wanda hakan zai ba da damar sakin fursunonin.
Wani babban abin damuwa ga Pakistan shi ne kasancewar Afghanistan na masu tada kayar baya, musamman wadanda ke da alaka da TTP ko Jamaat-ul-Ahrar ko Lashkar-e-Islam, da kuma wadanda ke tare da rundunar 'yantar da yankin Baluchistan, wadanda suka dauki alhakin kai hare-hare masu martaba a wannan wata a lardin Sindh da ke kudu maso yammacin Lardin Baluchistan.
An kashe dakarun sojin Pakistan da dama a wannan watan a kudu maso yammacin lardin Baluchistan a yakin da suke da masu tayar da kayar baya.
Kungiyar TTP ta dauki alhakin daya daga cikin hare-haren kunar bakin waken da aka kai a Pakistan a shekarar 2014, lokacin da aka kai hari a wata makarantar sojojin Pakistan aka kuma kashe 140.
Yawancinsu dalibai ne, wasu kuma shekarunsu ba su kai 5 ba.
"Adadin mayakan 'yan ta'addan kasashen waje 'yan asalin Pakistan da ke Afghanistan, da ke zama barazana ga kasashen biyu, an kiyasta yawansu a tsakanin 6,000 zuwa 6,500, yawancinsu suna da TTP", a cewar rahoton.
Babban bankin Birtaniya HSBC ya musanta "kafa tarko" ga kamfanin Huawei na China a binciken da Amurka ta ke yi - RT labaran kasuwanci
HSBC mai hedikwata a bankin sana'o'i da ke da hedikwata a birnin London-HSBC ya je shafinsa na sada zumunta ya na mai cewa ba haka ba ne, kamar yadda kafofin yada labaran China su ka yi ikirari, "kirkirar shaidu" a kan Huawei, wanda har ya kai ga kama babban jami'in kula da harkokin kudi na kamfanin a Canada.
A cikin wani sakon ba-zata da ta sa a shafinta na WeChat, mai bayar da lamunin ya ce, abinda ta aikata bai jawo binciken da Amurka ta ke yi kan babban mai samar da na'urorin sadarwa na zamani a duniya ba, yayin da binciken da Huawei ta ke yi na zargin karya takunkumin da Amurka ta kakabawa Iran ya fara aiki gadan-gadan kafin shigar bankin a karshen shekarar 2016.
"HSBC ba ta nuna kiyayya ga Huawei kuma ba ta" firgita "Huawei ba", in ji bankin a ranar Asabar, yana mai karawa da cewa ba zai taba gurbata duk wasu abubuwa game da abokan huldarta ba.
"Dangane da bukatar DOJ na Amurka [Ma'aikatar Shari'a ta Amurka] na neman bayanai, Kungiyar HSBC ce kawai ta gabatar da gaskiyar manufar.
HSBC ba ta "ƙiƙiro" shaida ko "ɓoye" gaskiya ba".
Har ila yau a shafin rt.com Matakin da Burtaniya ta dauka na hana kamfanin Huawei daga hanyar sadarwar 5G ya nuna Amurka ta yi kama-karya kan manufofin harkokin wajen Biritaniya - George Gkyay ga kamfanin Boom Bust
An toshe sakon a dandalin tare da bayanin cewa "ya sabawa ka'idoji" kuma ba a samunsa a yanzu.
Wannan sanarwa na zuwa ne jim kadan bayan da wasu kafofin yada labarai da yawa na China, ciki har da jaridun da ke da nasaba da wannan, suka zargi HSBC da "hada baki" da Washington don kafa wa Huawei tarko.
Kamfanin ya kasance a sahun gaba a wata badakalar diflomasiyya ta sama da shekara daya da rabi tun bayan da aka kama Huawei CFO Meng Wanzhou a watan Disambar shekarar 2018 a Canada a bisa sammacin kama shi daga Amurka.
Meng na fuskantar tuhume-tuhume na zamba kan zargin amfani da wani kamfanin Shell wajen kakabawa Iran takunkumi da kuma zargin yin karya ga bankuna game da alakar da ke tsakanin Huawei da kamfanin Skycom na Iran.
Bisa sabbin shaidun da jaridar Global Times ta bayar, an ce, HSBC yana sane da dangantakar kamfanin kasar Sin da Skycom.
Bankin ya bayar da rahoton cewa, ya gwammace ya yi "tattaki" da gwamnatin Amurka don tserewa hukunci mai tsanani a shekarar 2012, a lokacin da bankin ya shigar da karar halatta kudin haram da kuma takunkumin karya tattalin arziki, ciki har da takurawa Iran.
An umarce ta a lokacin da ta biya kusan dala biliyan 1.9 kudin fensho da kuma hana duk wata barna makamanciyar wannan.
"Shaidun sun nuna cewa HSBC ta fahimci wannan alakar, amma da gangan ta sayar da takardun kasuwancinta na sirri ga bangaren Amurka domin gwamnatin Amurka ta sa ido kan yadda bankin na Birtaniya ya nuna halin ko in kula, kuma ba za ta hukunta shi ba a karkashin yarjejeniyar tabbatar da tsaro ta shekarar 2012", a cewar jaridar a daya daga cikin labaran da ta bayar kan batun.
A cikin wani kashedi da ta yi, jaridar Beijing-controlled ta kara da cewa mai bayar da bashin, idan aka tabbatar da cewa yana da laifi a cikin wannan "tattaki", zai iya fuskantar "hukunci mai tsanani" a China, daya daga cikin manyan kasuwanni na HSBC.
Wannan dai ba shi ne karon farko da mashahurin bankin ke cin wuta ba a 'yan makonnin da suka gabata.
A watan da ya gabata, an ragargaji HSBC saboda goyon bayan sabuwar dokar tsaron kasa ga Hong Kong, birnin da aka fara kasuwancinsa kuma wanda ya kai sama da rabin ribarsa.
Bankin ya fuskanci kakkausar suka daga bangarorin biyu - daga kasashen Yamma, a inda Sakataren Harkokin Wajen Amurka Mike Pompeo ya kira jimillar "kamfanoni kowtow", da kuma Gabas ta Tsakiya, tare da bayar da rahoton cewa bangaren China na cewa, tallafinta "na hakika ne".
Ma'aikatan kashe gobara sun samu sukunin kashe gobara a makociyar gundumar Lassen
Ma'aikatan kashe gobara na samun galaba a kan wasu gobarar daji biyu da ta kone fiye da eka 30,000 a karamar hukumar Lassen, arewa maso gabashin Sakkwato.
Wutar dajin ta Zinariya wacce ta soma kudu da Adin, tana dauke da kashi 40% yayin da ta ke ci gaba da yin barazana ga gidaje da matsugunai da kuma ayyukan noma da dabbobi da katako, a cewar jami'an kashe gobara na Cal a wata sabuwa ranar Asabar da safe.
Bayan kone-kone na tsawon kwanaki hudu, wutar ta yi taho-mu-gama ta hanyar hekta 21,000, ta kuma lalata gidaje bakwai tare da aika jami'an kashe gobara biyu zuwa asibiti.
Ba dare ba rana, ma'aikatan kashe gobara sun yi amfani da yanayi mai wuya wajen ginawa da kuma karfafa layukan kula da su.
Amma ana sa ran samun iska mai karfi da kuma zafi mai zafi a ranar Asabar.
Yammacin Susanville, wata karamar gobara da aka fi sani da wutar Hog ta hallaka gine-gine biyu tare da cinye kimanin eka 10,000.
Wutar ta lafa cikin dare a yayin da ma'aikatan kashe gobara ke aikin kashe gobara tare da karfafa layukan kula da su, a cewar ma'aikatar kula da gandun dazuka da kare gobara ta California.
Da sanyin safiyar Asabar ne aka samu kashi 45% kuma an kona su tsawon kwanaki shida.
A lokacin zafi na rana, da yanayin zafi da ke sama da digiri 90 a yankin Susanville, hayaki mai sa hawaye na cikin hadarin tashi.
Yayin da ake barin wasu mazauna unguwanninsu su koma gidajensu, wasu wuraren a duka wuraren da ke ci da wuta na ci gaba da kasancewa a karkashin umarnin da aka bayar na tantancewa.
An sallami ma'aikatan kashe gobara biyu da suka samu raunuka a gobarar Zinare daga asibiti.
Aljeriya: Mutuwar Mahmoud Guemama - Aljeriya Ta Rasa Marasa Galihu, In Ji Shugaba Tebboune.
Shugaban kasar Jamhuriyar Algiers, Abdelmadjid Tebboune, ya aike da sakon ta'aziyya ga 'yan majalisar dokokin kasar (APN), Mujahed Mahmoud Guemama, wanda ya mutu a ranar Juma'a, inda ya ce Aljeriya "ta yi rashin uban kasa, kuma madugun da ya aikata abubuwan da suka shafi al'ummarsa da kuma al'ummarsa".
Aljeriya ta yi rashi a yau, sakamakon mutuwar Mujahed Mahmoud Guemama, dan kishin kasa kuma madugun da ya aikata abubuwan da suka shafi al'ummarsa da kuma al'ummarsa, mutumin da bai taba yin kasa a gwiwa ba, wanda kuma niyyarsa ta ci gaba da wanzuwa tun daga lokacin da ya dauki makamai, tare da 'yan uwansa Mujahedeen masu inganci, har zuwa numfashinsa na karshe a wannan rana ta bakin ciki da sai mun yi murabus da kanmu da nufin Allah kawai ", Shugaba Tebboune ya rubuta a sakonsa na ta'aziyya.
"Marigayi Mahmoud Guemama, tsira da amincin Allah su tabbata a gare shi, na daga cikin tsare-tsare na musamman na amintattun masu kishin kasa da suka sadaukar da kansu domin kasarsu", a cewar shugaban kasar ta Jamhuriyar.
"Marigayin ya sadaukar da rayuwarsa wajen 'yantar da Aljeriya daga azabtarwar mulkin mallaka na babu gaira babu dalili, ta hanyar shiga cikin sahun juyin juya hali a Firayi Ministan rayuwa a shekarar 1960 a sansanin horar da Tahart na tarihi wilaya VI".
Shugaba Tebboune ya ce, "Marigayi Shugaban kasa sananne ne ga kowa saboda tabbatar da madafun iko da kuma sadaukarwar da ya yi wajen ankarar da jama'a irin kyakkyawar alkiblar da ke tattare da hadin kan kasar Aljeriya".
"A kudu mai nisa, marigayi Mahmoud Guemama yana jin dadin zama mashahuri a matsayinsa na mai shiga tsakani, yana mai shiga tsakani domin sulhunta 'yan uwa a kasa guda a duk lokacin da aka kintsa wutar sabani", a cewar shugaban kasar a sakon nasa.
"Duk wadannan halaye da dabi'u sun sa marigayi Mahmoud Guemama ya samu girmamawa da amincewar mutanen Tamanrasset wadanda suka zabe shi ya wakilce su a majalisar wakilan jama'ar kasar (APN) har na tsawon wa'adi da dama, a lokacin yana jakada kuma mai kare damarmakin yankin da muradun al'ummarta, har ma da wakili kuma kakakin dukkan 'yan Aljeriya", a cewar shugaban kasar ta Jamhuriyar.
"Duk wasu kalamai na ta'aziyya ba za su isa su jinjina ga mujahed Mahmoud Guemama ba, tsira da amincin Allah su tabbata a gare shi.
Yana barin mu a yau a daidai lokacin da Aljeriya ta bukace shi ", in ji shugaban kasar.
"Ina addu'ar Allah Madaukakin Sarki da ya kewaye marigayin da rahamarSa Mai Tsarki, ya tarbe shi a cikin aljanna mai girman gaske tare da shuhadaa da kuma budurwa.
Haka kuma ina addu'ar Allah ya karawa iyalansa da masoyansa hakuri da ta'aziyya... babu wani karfi ko iko sai na Allah ", Shugaban Jamhuriyar ya kammala.
Zanga-zangar Seattle: Gobara Da Pepper Sun Fadi Yayin Tsawon Watan Maris A Cikin Birnin
Seattle - Bayan shafe makonni ana kazamin rikici tsakanin masu zanga-zanga da hukumomin tarayya a Portland, Ore., jama'a kimanin 2,000 ne suka yi dandazo a Seattle a ranar Asabar, suna bi ta kan tituna suna arangama da 'yan sanda.
'Yan sanda uku sun ji raunuka, ciki har da wanda aka kwantar a asibiti sakamakon raunin da ya samu a kafa sakamakon fashewar wani abu, an kuma kama masu zanga-zanga 16 tun da sanyin yamma, in ji 'yan sanda.
Dauke da alamu kamar su "Feds Go Home" da kuma ihu na cewa "Babu adalci, babu zaman lafiya", masu zanga-zangar sun tsaya a wurin wata cibiyar tsare matasa da za a tsare nan gaba, sun kuma cinnawa gine-ginen da ke wurin wuta.
Wasu sun farfasa tagogin kasuwannin da ke kusa da wurin.
'Yan sandan sun yi taho mu gama da jama'ar ne a unguwar Capitol Hill, inda suka yi ta jifansu da kulake da kuma barkonon tsohuwa kafin su soma kai mutane gidan yari.
Bipasha Mukherjee 'yar shekara 52 'yar asalin Kirkland, Wash. Ta ce ta soma zanga-zanga a kan tituna ne tun a watan Mayu kuma ta ce abin damuwa ne a gare ta ganin irin wadannan dabaru na zalunci da 'yan sanda ke yi.
"Wannan ba ita ce kasar da na yi gudun hijira ba", a cewar Misisi Mukherjee, wacce ta zo daga Indiya fiye da shekara 30 da suka wuce.
"Ji mu ke yi kamar mu na saurin zama jiha mai saurin fushi da kuma jihar ƴan sanda"
Michaud Savage na Seattle ya ce zanga-zangar ta samo asali ne daga hukumomin yankin da kuma tura jami'an tsaro na tarayya wadanda suka yi wata zanga-zangar adawa da wata zanga-zanga da aka dade ana yi a Portland.
Mista Savage ya ce dokar ta bacin da aka kafa a Portland, wacce ta kunshi amfani da hayaki mai sa hawaye da kuma taron jama'a, na da hatsari kuma bai dace ba.
Mista Savage ya ce yayin da ya ke wanke idanunsa daga barkonon tsohuwa da kuma reno wani rauni a hannunsa daga wata 'yar hayaki mai sa hawaye.
Mutuwar George Floyd a hannun 'yan sanda a Minneapolis a watan Mayu ya jahilci zanga-zangar da ta jawo miliyoyin jama'a fitowa kan tituna a birane da dama, amma waɗannan zanga-zangar sun wanzu a yawancin birane.
Seattle da Portland dai, sun ga yadda zanga-zangar ta tsawaita.
Masu zanga-zanga a Seattle a wani lokaci sun auka wa wasu unguwanni da dama na Capitol Hill tare da ayyana wani yanki mai cin gashin kansa.
Bayan wasu jerin harbe-harbe da aka yi a wajen ne ya sa 'yan sanda suka killace yankin, zanga-zangar ta kau.
Portland kuma, ta cigaba da zanga-zanga, tare da yin wasu jerin zanga-zanga a kusa da gine-ginen gwamanatin tarayya da ke birnin.
Bayan da shugaba Trump ya bayar da umarnin kare mutum-mutumi da dukiyoyin gwamnatin tarayya, ma'aikatar tsaron cikin gida ta tura tawagogin 'yan dabara zuwa birnin, inda suka fara wasu jerin arangama da suka yi sanadiyyar raunata masu zanga-zanga, da binciken kwakwaf da kuma kiraye-kiraye daga shugabannin yankin na jami'an tsaro na tarayya da su bar wurin.
Jama'ar da ke zanga-zanga a wannan birni sun kutsa cikin dubban jama'a, kuma ana ci gaba da zanga-zanga a wajen.
A wannan makon, jami'an tsaro na tarayya sun tura wata tawaga ta dabara zuwa Seattle, kuma masu zanga-zangar sun ambaci wannan ci gaban a matsayin dalilin daya sa aka gudanar da zanga-zangar ta ranar Asabar.
Yayin da zanga-zangar ta Portland ta kasance a cikin gari, zanga-zangar da aka yi a ranar Asabar ta zagaya yankunan da ke gabas da tsakiyar garin, inda nan ne babbar kotun tarayya ta birnin.
Virginia Beach ta sauka daga muƙamin Confederate
Virginia BEACH, Va. - Birnin Virginia Beach ta cire wani gidan kallo na Confederate dan shekara 115 daga filayen taron jama'a a ranar Asabar, kasa da kwana biyu bayan da Majalisar Birnin ta kada kuri'ar rashin amincewa da yin hakan.
Ma'aikata sun sauka daga mujami'ar mai tsawon kafa 2 (mita 8.2) a safiyar Asabar, kamar yadda kafafen yada labarai suka ruwaito.
An shigar da shi a shekarar 1905, ya kuma tsaya a kofar tsohuwar kotun gundumar Princess Anne, a wannan wuri ne aka taba gudanar da gwanjon bayi.
Majalisar ta kada kuri'ar raba-gardamar ne a daren Alhamis don fara aikin cire shin.
Majalisar ta saurari jawabai da yawa kuma ta yanke shawarar cewa mutane da yawa na kallon wannan maudu'i a matsayin mai cike da rarrabuwa da kuma tunatarwa mai zafi kan abubuwan da suka faru a baya.
A baya-bayan nan an rufe mutum-mutumin baki daya, tare da kulle kofar shiga cikinsa biyo bayan zanga-zangar da aka yi a baya-bayan nan da kuma yin garkuwa da mutane a wasu mujami'u na Confederate.
Za a adana kusufin ne a yanzu.
Birnin yanzu dole ne ya jira duk wani tayi daga kungiyoyin tarihi ko wasu abubuwa da za su so su dauki kayan tarihin.
Wata Kotu a Masar na nufin mutumin da ya kashe yara uku don nazarin halayyar dan adam
Babban Lauyan da ke shigar da kara a Minya ta Kudu Tamer Motea a ranar Lahadi ya yankewa wani manomi hukuncin zaman gidan yari na kwanaki hudu sakamakon binciken dalilin da ya sa ya kashe 'ya 'yansa uku a yayin da kuma ya kira shi kwamitin kula da masu tabin hankali.
A ranar 24 ga watan Yuli, Mohamed Ali dan shekara 56 ya jefi 'ya 'yansa Khadiga da hudu da Mena da takwas da kuma Omar dan shekara shida a gaban jirgin kasa mai tafiya a tashar jirgin kasa ta Mallawi.
An gano cewa Ali yana babbaka gadan-gadan a lokacin da ake bincike, har ta kai ga ana zargin cewa yana fama da tabin hankali.
Matarsa ta musanta cewa ta yi fama da wata matsala da shi, ta kuma danganta halayyarsa da batutuwa da suka shafi tunani.
Mazauna kauyen Massart Mallawi sun nesanta kansu daga yin magana kan lamarin, suna masu mika ta'aziyyarsu ga iyalan yaran kawai.
Wajen kashi 93 cikin 100 na yaran Masar masu shekara daya zuwa 14 na fama da tashin hankali, in ji Khalid Darwish, mashawarci ga hukumar kula da kananan yara da iyaye mata ta Majalisar Dinkin Duniya a watan Oktoba.
Tsigewa na daya daga cikin muhimman ginshikai wajen kawar da cin zarafin kananan yara, ya kara da jaddada muhimmancin hadin gwiwa tsakanin majalisa da kuma kare hakkin jama'a a wannan fanni.
A cewar wani nazari da hukumar kula da kananan yara ta kasa da kuma Motherhood ta shirya, ya nuna cewa ana samun tashin hankali a wuraren da ya kamata su kasance cikin hadari, kamar gida, makaranta ko kulake, da kuma fuskantar tashin hankali daga mutanen da ya kamata su kula da su, kamar iyaye ko kuma malamai.
Masu rajin yaki da tsattsauran ra'ayi a Laberiya sun bukaci a kori Corbyn ko kuma su fuskanci shari'a
Laberiya za ta iya biyan diyyar da ta kai tsakanin fam miliyan 3 zuwa fam miliyan 8,000, a cewar rahotanni.
Yanzu haka dai shugaba Keir Starmer na fuskantar matsin lamba kan ya kori Mr Corbyn.
A daren jiya tsaffin ma'aikatan jam'iyyar sun ce za su sauke wannan mataki na shari'a idan har aka kori Mista Corbyn daga jam'iyyar.
Sai dai ya zuwa yanzu jam'iyyar Labour ta ki ta ce komai kan wannan bukata.
Sai dai duk da haka dan jam'iyyar Labour MP Jon Trickett ya ce: "Wannan bukata ce da ba'a so".
Magoya bayan Mista Corbyn sun ce Mista Starmer na bukatar ya mayar da hankali wajen zakulo labaran da ke magance cutar Koronabirus a maimakon ya koma cikin rarrabuwar kawunan 'yan jam'iyyar Labour a ciki.
Wata fitacciyar majiya ta jam'iyyar Labour ta shaida wa Daily Mail cewa za su dauki matakin shari'a ko da Mista Starmer ya kori Mista Corbyn.
"Ina nufin da gaske ya ke, ya sake sanya jam'iyyar Labour ta zama mai fafatawa".
"Har yanzu da akwai sauran rina a kaba dangane da manufofinsa amma ya soma burgewa kwarai da gaske kuma ya shiga wani yanayi inda ga mutane da yawa da suka karaya da gaske a jam'iyyar Labour, masu kada kuri'a yadda suke, ina ganin yanzu suna sake kallonsa ne cikin tausayi kuma suna daukarsa a matsayin wani gagarabadau".
Mista Blair ya nuna damuwarsa kan yadda har yanzu ake ganin jam'iyyar Labour a matsayin jam'iyyar da ke kin biyan haraji.
Ya ce: "Kwarewata game da haraji a lokacin da ka ke jam'iyyar Labour ka yi taka tsan-tsan kwarai da gaske saboda jama'ar da ke wurin ba sa zaune cikin damuwa saboda ko za ka biya haraji ko a'a, kila suna cikin damuwa cewa za ka biya haraji don kawai ka tuna da wannan damuwar".
COVID-19 za ta sauya tattalin arzikin duniya na dindindin (ra'ayi)
Gwajin kwayar cutar na iya zama wani ɓangare na rayuwarmu, kamar dai yadda matakan tsaro suka zama ubiquitous bayan 9/11.
Yana da muhimmanci a zuba jarurruka a cikin kayayyakin da suka wajaba don gano barkewar kwayar cutar nan gaba.
Wannan zuba jarin ya kare tattalin arziki idan rigakafi ga Covid-19 ya zama na wucin gadi.
Kasashe da yawa masu karfin tattalin arziki sun karbi nau'ukan tallafin da Jamus ke bai wa Kurzarbeit (gajeren aiki) a lokacin annobar.
Wannan manufar na ci gaba da rike ma'aikata da ke aiki a rage sa'o'i da biya, tare da tilastawa gwamnati biyan wasu daga cikin mafi karancin albashi.
Ta hanyar sa wasa tsakanin kamfanoni da ma'aikata a tsanake, tattalin arziki ya fi shiri domin farfadowa cikin sauri.
Yana da muhimmanci a inganta aiwatar da wadannan manufofi a kuma mai da su wani bangare na din-din-din na kayan aikin farfadowa da tattalin arzikinmu.
Aiki na nesa yana iya zama ruwan dare gama gari.
Muna da wasu hujjoji da ke nuna cewa yin aiki daga gida aƙalla yana da amfani kamar aiki a ofis.
Duk da haka, kamfanoni da yawa sun yi jinkirin rungumar aiki mai nisa.
Yanzu da mutane da yawa sun gwada shi da sakamako mai kyau, aikin nesa na iya zama a nan don ci gaba da zama.
Matsalar annobar ta zarta alkaluman sauye-sauyen dijital, tare da kara fadada a kasuwancin e-commerce da kuma karuwar alkaluman soma amfani da wayar tarho, da na'urar daukar hoto, da koyar da yanar gizo da kuma fasahar fintech.
Kamfanoni da ke samar da kayayyaki na kasa da kasa na fama da karanci da kwalbati.
Mai yiwuwa mu ga yawancin wadannan kamfanoni sun sake dawo da wasu daga cikin abubuwan da suke samarwa.
Sai dai abin takaici, wannan dabi'a ba za ta samar da ayyukan yi da yawa ba saboda yawancin abubuwan da ake samarwa suna iya sarrafa kansu.
Gwamnatoci za su fi girma bayan sun taka rawar gani na marasa sukuni da kuma masu zuba jari na karshe a lokacin rikicin.
Bashin da jama'a za su ci zai balle, wanda hakan zai samar da kalubalen kudi a duniya.
Darasi mafi muhimmanci daga annobar Covid-19 shi ne muhimmancin aiki tare kan matsalolin da suka shafi dukkanin ƴan-adam.
Mun fi kowa samun hadin kai da hadin kai fiye da rabuwa.
Sarauniya da Adam Lambert: Brian May na murnar zagayowar ranar haihuwar Roger Taylor
Jarumin fina finan Sarauniya na murnar zagayowar ranar haihuwarsa a yau tare da fitaccen jarumin fina finan Rolling Stones Mick Jagger, wanda yanzu ya ke da shekaru 77 da haihuwa.
Brian May ya yi bikin murnar zagayowar ranar haihuwarsa karo na 73 a karshen mako a ranar 19 ga watan Yuli, ya kuma gode wa masoyansa saboda murnar zagayowar ranar haihuwar.
Tauraron mawakin Rock ya rubuta a kusa da wani kato shi da matarsa Anita Dobson: "Liyafar cin abincin dare na murnar zagayowar ranar haihuwata a gare ni - wacce Anita ta kirkira - mun yi ado don mu zauna a gida!"
Sakatariyar Harkokin Cikin Gida Priti Patel ta bukaci bayani daga Twitter da Instagram kan 'zagin' Wiley tweets
Priti Patel ta bukaci bayani daga Twitter da Instagram kan tsawon lokacin da aka dauka ana cire wasu sakonni na "cin zarafi" da Wiley ya yi.
A halin yanzu 'yan sanda na bincike kan wasu jerin kalamai na batanci da aka sa a shafin sada zumunta na Grime artist.
Sakatariyar harkokin cikin gida ta aika da wani sako a shafinta na dandalin sada zumunta na Tuwita a ranar Lahadi tana mai cewa: "Sakonnin tsatstsauran ra'ayi daga Wiley abune na Allah wadai".
"Bai kamata su rika ci gaba da zama a shafukan sada zumunta na Twitter da Instagram ba har zuwa wannan lokaci kuma na nemesu da cikakken bayani".
"Dole ne kamfanonin sadarwar zamani su yi aiki da sauri don cire irin wannan kiyayya da ke bayyana daga dandamalinsu".
An zargi Twitter da "yin watsi da tsattsauran ra'ayi" kamar yadda Wiley ya wallafa a shafinsa na tweets har yanzu ana iya ganinsu awanni 12 bayan da aka fara wallafa su.
Tun da fari an cire wasu sakonnin tweets kuma an bayar da sammacin kame matashin dan shekara 46 da haihuwa a wani samame na kwanaki ukku da shafin ya kai.
A baya dai Twitter ya ce an kulle asusun Wiley na wani dan lokaci "saboda ya sabawa manufofinmu na nuna kiyayya", yayin da Facebook ya ce "babu wani wuri na kin jinin baki a Instagram".
Rundunar 'yan sandan birnin Alkahiran ta ce a ranar Asabar: "Rundunar 'yan sandan na daukan duk wasu rahotanni na tsatstsauran ra'ayi da matukar muhimmanci. Ana kan tantance abubuwan da suka dace".
A daya bangaren kuma, kamfanin gudanarwa na Wiley, mai suna A-List Management, "ya yanke duk wata alaka" da tauraron.
Tsohon manajan mai zane-zane a yanzu, John Woolf, wanda Bayahude ne, ya rubuta a shafinsa na dandalin sada zumunta na Tuwita cewa: "Wadannan sakonnin Wiley na tsatstsauran ra'ayi a yau mu a @ A _ ListMGMT mun yanke duk wata alaka da shi. Babu wani wuri a cikin al'umma na tsatsauran ra'ayi".
Tun da farko ya ce ba ya goyon baya ko kuma ya amince da abin da Wiley ya wallafa amma zai yi magana da shi cikin sirri kuma "zai taimaka wajen ilmantar da shi".
Sai dai a wani bidiyo da ya saka a shafinsa na sada zumunta na Instagram, Wiley ya bayyana yana mai cewa shi ne ya yanke alaka da yadda yake gudanar da ayyukansa.
Sauran ƴan majalisa sun yi ta sukar Twitter saboda barin tweets din su kasance a bayyane.
'Yar jam'iyyar Labour MP Jess Phillips ta ce a ranar Asabar:
"Kawai ka ga duk abubuwan da Wiley ya yi. Me ya sa a duniya @ Twitter ya bar irin wannan barna da kiyayya? Ya haddasa duk wata barna mai hatsari, Yahudawa suna samun abubuwan da ba ka samu ba, suna da iko, suna ganin sun fi kyau... Wannan kaya ne mai hatsari. Lallai ya kamata a sauko da shi".
Dan uwansa MP Neil Coyle ya kara da cewa: "Yadda yake gudanar da ayyukansa ya bayyana karara fiye da yadda @ Twitter ya jaddada, har ila yau, wannan doka (ciki har da Online Harms Bill) ya kamata ta tabbatar da cewa ba a yi amfani da dandalin sada zumunta ba wajen yada labaran bogi".
John Mann, mai baiwa gwamnati shawara mai zaman kansa kan yaki da tsattsauran ra'ayi, ya ce sakonnin na tweets "sun nuna ainihin dalilin da ya sa dokar ke bukatar sauyi domin rike su a matsayin masu sanin yakamata".
A kuma halin da ake ciki, kungiyar yaki da nuna wariyar launin fata ta Campaign Against Antisemitism ta nemi 'yan sanda da su binciki abubuwan da Wiley ya yi, ta kuma yi kira a rufe shafukansa na sada zumunta "don hana ci gaba da fitar da dafin kin jinin Yahudawa".
Wiley, wanda aka fi sani da Godfather of Grime kuma sunansa na ainihi shine Richard Cowie, ya karbi kyautar MBE don ayyuka zuwa kiɗa a shekarar 2018.
"Gazawar" Amurka na ci gaba da neman magungunan cutar Korona
Kokarin da kasashen duniya ke yi na samar da magunguna masu anfani na yaki da cutar Kansa da Amurka ke yi ya ci tura saboda masu bincike na gwada magungunan ta "hanya mai armashi, da son rai", Kwararren da ke jagorantar shirin na Burtaniya ya yi gargadi.
Shirin yaki da cutar farfadiya na Biritaniya wanda ya shafi marasa lafiya 12,000 a asibitoci da dama na Biritaniya, tuni ya nuna alamar wani sabon magani na magance cutar da kuma karin haske kan wasu guda biyu - wadanda a baya ake tunanin za su iya samar da ababen more rayuwa - a matsayin marasa amfani.
Amma gazawar tsarin likitocin Amurka na daidaita wannan fitarwa na nufin cewa har yanzu ana ci gaba da kimanta sauran wasu magunguna masu alamar da za a iya kamawa don amfani da su a wurare da yawa.
Musamman ma, plasma na convalescent (plasma na jini wanda ake dauka daga marasa lafiyar Covid-19 kuma wanda ke dauke da garkuwar jiki wanda zai iya kare wasu daga cutar) har yanzu ana gwada shi yadda ya kamata a kan gwaji mafi girma da aka yi na gwaji.
Farfesa Martin Landray, daya daga cikin wadanda suka assasa shirin farfadowa da cutar ya ce, "dubun dubatar mutane an riga an basu plasma mai dauke da cutar a Amurka, amma ba a bazuwar wadannan magunguna".
Landray, wani kwararre a fannin kafa manya-manya gwaje-gwajen magunguna ya kara da cewa, "Suna dai baiwa mutane masu dauke da kwayar cutar plasma da fatan za ta yi aiki. An ba su abubuwa masu yawa kuma har yanzu ba su da masaniyar ko tana taimakawa ko cutarwa ko kuma ba ta da wani tasiri".
Amurka ta gaza yin manyan gwaje-gwaje da suka zama ruwan dare gama gari kuma hakan ya kawo karshen samar da mummunan magani.
Gwajin magungunan da aka yi da bazuwar su ne ma'aunin zinare na zuba magunguna masu anfani.
Suna kawar da nuna rashin sanin yakamata da ka iya girgiza hukuncim malaman asibiti.
Dubban mutane ne ake ba su wani magani yayin da wasu dubbai ake ba su wani gurbin karatu.
Babu wanda ya san ko su wanene aka basu.
Sannan ana kwatanta sakamako da kuma ingancin maganin da aka bayyana.
Ta wannan hanyar, farfadowa da na'ura ya iya nuna cewa steroid dexamethasone ya rage mutuwar da kashi uku a cikin marasa lafiyar Covid-19 akan na'urar ventilators.
Ya kuma nuna cewa maganin kashe kwayoyin cuta na hydroxychloroquine - da kuma maganin da aka hada na lopinavir da ritonavir - ba su da wani tasiri wajen ceto rayukan marasa lafiya.
Musamman wadannan gwaje-gwaje na bukatar marasa lafiya masu yawan gaske kuma babu asibiti ko guda daya da ke da isasshen irin wannan bincike.
Biritaniya ta samu wani muhimmin amfani - wata cibiya ta ma'aikatar lafiya ta kasa.
Sabanin haka, ma'aikatar kiwon lafiya ta Amurka ta yi karanci kuma nasararta daya tilo wajen nuna yiwuwar samun magani an nuna amfani da magani mai matukar tsada na remdesivir don saurin warkewar wasu marasa lafiyar Covid-19.
Landray ya kara da cewa, "Akwai kuri'a da kuma gwajin kananan kwayoyi da suka shafi marasa lafiya 'yan kalilan ko kuma 'yan kalilan da ke tafe a Amurka amma babu komai a cikinsu".
"Sun gaza yin manyan gwaje-gwaje da suka banbanta kuma hakan ya kawo karshen samar da mummunan magani. Hakan ya sa aikin mai fama da talauci da kuma sakamakon da ake samu ga marasa lafiya da ke fama da talauci".
Landray ya ce wannan gazawa ta yi matukar tabarbarewa musamman idan aka yi la'akari da amfani da plasma mai dauke da sinadarin convalescent, wanda likitoci da yawa suka yi imanin cewa zai iya taka muhimmiyar rawa wajen kula da marasa lafiyar da ke fama da cutar Covid-19.
Ya kara da cewa, "idan ka lura da Amurka, an yi amfani da abubuwa masu yawa na wannan magani a bisa son rai. Burtaniya ta wuce gona da iri idan aka kwatanta da abin da ke faruwa a can".
Farfesa Peter Horby, wani kwararre kan cututtuka masu yaduwa kuma daya daga cikin wanda ya kirkiro shirin farfadowa da cutar, ya ce: "An samu rahoton marasa lafiya 20,000 suna samun plasma mai dauke da cutar a kowani wuri, amma babu daya daga cikin wadannan marasa lafiya da ya yi bazuwar.
Da a ce sun saka wadannan marasa lafiya cikin gwajin da aka yi musu, da yanzu za mu samu cikakkiyar amsa game da tasirin plasma mai dauke da cutar".
Horby ya kara da cewa yanzu haka kamfanin UK Recovery ya kaddamar da gwajin bazuwar cutar amosanin jini, amma ba ya sa ran sakamakon zai kasance a shirye sai nan gaba a wannan shekarar.
Masar ta fara rijistar bayanan masu kada kuri'a a kasashen waje don zaben 'yan majalisar dattawa
Hukumar Zaben Kasar (NEA) a ranar Asabar ta fara yin rijistar bayanan masu kada kuri'a da ke cikinsa don fara kada kuri'arsu a zaben sanatocin da za a gudanar a ranakun 9 da 10 ga watan Agusta, a cewar shafin hukumar NEA na yanar gizo.
Dole ne masu kada kuri'a su yi rijistar bayanansu da kuma aikin diflomasiyyar da ke da alaka da mazauninsu a kasashen waje a shafin hukumar NEA na yanar gizo daga ranar 25 ga watan Yuli har zuwa ranar 31 ga watan Yuli.
Hukumar ta NEA ta kuma wallafa wani faifan bidiyo da ke bayanin irin matakan da masu kada kuri'a za su iya dauka wajen kada kuri'arsu daga nesa ta hanyar email, a matsayin wani bangare na matakan kariya daga annobar coronavirus.
Lokacin shari'ar dan takarar sanata farfagandar zabe na gudana daga ranar 26 ga watan Yuli har zuwa ranar 8 ga watan Agusta, in ji NEA.
Minista mai kula da harkokin shige da fice a Masar Nabila Makram ta yi kira ga masu kada kuri'a a kasashen waje na Masar da su shiga zaben kamar yadda tsarin mulki ya tanada.
A ranar 17 ga watan Yuni ne Majalisar Dokokin Masar ta amince da dokar da ta kafa majalisar dattawa, wacce za ta yi aiki a matsayin majalisar dokoki ta sama.
An zartar da dokar ne da rinjaye da kashi biyu bisa uku, tare da kin amincewar 'yan majalisa hudu
Majalisar dattijai za ta kunshi mambobi 300, 100 daga cikinsu an zabe su ne ta hanyar tsarin jerin sunayen da aka rufe, 100 da tsarin mutum daya ya zaba, da kuma mambobi 100 da shugaban kasar Jamhuriyar ya nada
Wa'adin zaman membobinta a majalisar dattawa zai cika shekaru biyar, wanda zai fara daga ranar da za ta yi taronta na farko.
Sabuwar majalisar ita ce za a zaba a kwanaki sittin da suka gabaci karshen wa'adin aikinta.
'Yan sanda sun gwada sabbin kayan aiki masu dan karen gudu a yayin da ake ci gaba da zanga-zanga
Yayin da ake ci gaba da mummunar arangama tsakanin jami'an tsaro da masu zanga-zanga a Portland da kuma duk fadin kasar, ana ta tafka muhawara kan yadda 'yan sanda za su iya yanke kauna da karfin tuwo.
Wasu kamfanoni na fatar bayar da sabbin kayayyakin fasaha na zamani kamar wayoyin hannu na nesa da 'yan sanda za su yi amfani da su a maimakon zabin da ya fi hadari kamar barkonon tsohuwa, da harsasan roba da kuma abubuwan fashewa masu fashewa.
Kungiyar kare hakkin bil adama ta Amnesty International ta yi nazarin faifan bidiyo 500 daga zanga-zangar da aka yi daga ranar 26 ga watan Mayu zuwa 5 ga watan Yuni ta kuma gano abubuwa 125 da suka faru na karfin da ya wuce kima a fadin jihohi 40 da kuma gundumar Columbia.
"Mun ga rashin amfani da hayaki mai sa hawaye, da barkonon tsohuwa, da barkonon tsohuwa, da kudi mai tasirin millimita 40, hasali ma duk wata hadaka ta dan karamin makami da ake amfani da ita ta hanyoyin da ba su dace ba", a cewar wani mai bincike kan makamai na kungiyar Amnesty International Brian Castner.
Duk da haka, wasu sun nace cewa samun zaɓuɓɓuka na da muhimmanci don kauce wa buƙatar bindiga.
"Dukkanin wadannan na'urori su kasance a hannunka ga 'yan kato da gora su yi amfani da wanin karfi na zahiri da bindiga ke amfani da shi saboda ita kadai ce sana'a a Amurka inda 'yan kasar ke ba ka dama ka dauki ranka", a cewar Corey Pegues, tsohon Mataimakin Sufeton 'yan sanda na New York.
Daya daga cikin sabbin kayayyakin aikin da ake kira Bola Wrap, wata na'urar hannu ce da ke harba igiyar Kevlar mai kafa 8 wacce ta ke makalawa a kusa da wani wanda ake zargi.
Akwai na'urorin'Long Range Acoustic Devices'wadanda aka fi sani da sound canons, wadanda aka yi amfani da su wajen samar da makamashi da ke amfani da lasers wajen zafin fatar jikin mutum, da sabbin karafunan da aka yi su daga abubuwa kamar kumfa da chalk, da bama-bamai masu ruwan hoda, da kuma Taser.
Hannayen jarin Axon, kamfanin da ke yin Taser, sun yi sama da kashi 18%, wanda hakan ya kai kololuwa a lokacin da zanga-zangar ta rikide ta koma tashin hankali kwanaki kadan bayan kisan George Floyd da 'yan sanda suka yi.
Ana sa ran kasuwar sayen kananan makamai za ta kai dala biliyan 11.85 nan da shekarar 2023.
Ku kalli bidiyon don ku dubi sabbin kayayyakin fasaha da 'yan sanda ke amfani da su wajen kanikanci da karfi, da yadda aka tsara su, da kuma abin da ke kan gaba a siyasar da kuma al'ummun da suke bauta wa.
Magajin garin birnin Kansas ya yi maraba da taimakon da gwamnatin tarayya ke bayarwa wajen magance kisan kai, amma ya damu da manufar Trump
An yiwa Magajin garin birnin Kansas Quinton Lucas tambaya a ranar Lahadi kan manufar shugaba Trump na aikewa da jami'an tsaro na tarayya zuwa biranen Amurka - yana mai cewa yayin da zai yi maraba da taimakon da ake bayarwa wajen warware hannun riga da kisan kiyashi a birnin gabas ta tsakiya, yana mai tunanin cewa wannan yunkuri zai fi zama silar sayawa Trump fam din takara.
"Na yi matukar takaici a wannan makon [cewa] Shugaban kasa ya ambaci zanga-zangar George Floyd, ya ambaci kungiyar Black Lives Matter movement", Lucas dan jam'iyyar Democrat ya na mai cewa a shirin "Fox News Sunday" na zanga-zangar da aka yi a baya-bayan nan kan nuna wariyar launin fata da kuma zaluncin 'yan sanda.
"Ba haka abin yake ba a birnin Kansas. Mun samu ƙaruwa ta shekara da shekaru [amma] abin da muke buƙatar taimako a kai shi ne a zahiri share wasu daga cikin kisan da ba a warware ba".
Lucas ya kara da cewa: "Bari mu yi kokarin ganin mun mayar da hankali kan yadda za a magance kisan kai... Ina ganin idan kun saurari maganganun da aka yi a baya-bayan nan... muna farin cikin yin aiki tare da jami'an tsaro na tarayya a cikin wani dan karamin lokaci".
Duk da cewa a shirye ya ke da jami'an tsaro na tarayya su yi aiki da dokar kananan hukumomi, Lucas ya ce wannan gangami na Trump - musamman dangane da rigimar da ke tattare da dabarbarun da ke aiki a Portland, Ore., ta jami'an tsaro na tarayya - ya sa da yawa daga cikin ma'aikatansa sun daga murya su na nuna damuwarsu da kasancewar wakilai a kan titinan birnin.
"Abin da ba ma bukata shi ne karin kudin wuta daga jami'an tsaro na tarayya da za su yi, ina ganin, wani lamari ne na siyasa mai ban sha'awa", in ji shi.
A ranar Laraba Trump ya sanar da cewa ya tura jami'an tsaro na tarayya 100 zuwa Chicago domin su taimaka wajen magance yawan afkuwar wasu laifuka - matakin da ke nuna fadada sa hannun Fadar White House a dokar cikin gida yayin da Trump ke ci gaba da sanya kansa a matsayin "shugaban kasa mai bin doka da oda".
"Karuwar" jami'an da aka sanar a ranar Laraba zuwa Chicago da sauran wasu biranen Amurka wani bangare ne na shirin Operation Legend - mai suna LeGend Taliferro dan shekara 4, wanda aka harbe shi a ka a lokacin da ya ke barci a wani gida na birnin Kansas a karshen watan da ya wuce.
Duk da cewa aika jami'an tsaro na tarayya don taimakon kananan hukumomi ba abu ne da ba a taba ganin irinsa ba - Atoni Janar Bill Barr ya sanar da irin wannan yunkuri na karuwa a watan Disamba ga wasu birane bakwai da suka ga tashin hankali mai yaduwa - irin wakili na tarayya da ake aikawa, da kuma wasu dabarunsu, sun tayar da hankali a tsakanin 'yan majalisar jihohi da na kananan hukumomi.
Da yawan ƴan majalisar daga New York zuwa Portland sun yi magana kan yadda gwamnatin Trump ta aika da wakilan zuwa garuruwansu, musamman biyo bayan rahotannin da ke cewa wasu jami'an tsaro na tarayya da ba a gano ko su wanene ba sun tsare masu zanga-zanga a Portland kuma sun tafi da su a cikin motocin da ba a tantance ba.
Portland ta yi fama da zanga-zangar da aka kusa yi a kowacce rana kan cin zarafin ƴan sanda da wariyar launin fata tun bayan mutuwar George Floyd yayin da yake tsare a hannun ƴan sanda a Minneapolis a ranar 25 ga watan Mayu.
Hukumomin yankin sun kuma koka da cewa hauhawar alkaluman ta'addanci ne kawai, kuma masana harkokin shari'a masu aikata laifuka sun ce kokarin kare bayani saboda lokacin da Amurka ba ta taba fuskantar irinsa ba - da annoba, da rashin aikin yi a tarihi da kuma cece-ku-ce kan wariyar launin fata da kuma yadda 'yan sanda ke gallazawa mutane masu launin fata.
AP ta caccaki sakatariyar yada labarai ta Fadar White House Kayleigh McEnany kan "takaddamar siyasa" - amma masu aiko da rahotanni na ci gaba da yin tambayoyin siyasa - RT USA News
Kamfanin dillancin labarai na Associated Press ya zargi sakatariyar yada labarai ta Fadar White House Kayleigh McEnany da damawa da kafofin yada labarai ta hanyar yin takatsantsan da ita a siyasance maimakon a yi mata garanbawul -- a bayyane ya ke mantawa da cewa masu aiko da rahotanni sun zabi tambayoyin.
Wani labarin da kamfanin dillancin labarai na AP, wanda shi ne mafi girma a Amurka ya bayar a ranar Asabar, ya ce takaitattun labaran Fadar White House na iya zama "wata al'ada da ta karye", kamar yadda McEnany ya yi musu "wata shimfida, mai cike da talla ga shugaban kasa da ke fuskantar sake tsayawa takara, wurin da za a kai hare-hare a kan kafofin yada labarai da kuma wani dandalin da ke bayar da haske kan bayanai" kan abin da gwamnati ke yi.
Na karshe daga cikin abin da aka tabbatar ba shi da makama, kamar yadda da kyar ake iya bayyana wani sabon bayani a takaice.
Abin da AP ta kasa ambatawa shi ne, da kyar ake neman wani sabon bayani a zahiri a takaice.
Masu aiko da rahotanni na yawan amfani da 'yan damfara na Fadar White House domin jawo hankali kansu, wani nau'in fasaha da Jim Acosta na gidan talbijin na CNN ya kamala.
Wadannan sun wuce irin dangantakar da ke tsakani mai sarkakiya ta gwamnati, suna maimaita juna wajen yi wa gotcha tambayoyi da nufin kawai su yi tasiri a kan Shugaba Donald Trump.
A wasu lokuta, su kan yada kansu a labarai, kamar a lokacin da wani dan jarida na gidan talbijin na CBS Weijia Jiang ya mayar da martani kan "tambayar da China ta yi" na yin ritaya daga Trump ta hanyar ambaton wariyar launin fata na ba-zata: "Sir, me ya sa ka ke ce min dalla-dalla?"
A wata hira da aka yi da shi a ranar 6 ga watan Yuli, ya bayar da misali na sabanin da aka samu kan yadda takaddamar ta daina zama wata hanyar samar da bayanai masu ma'ana ga Amurkawa.
A wani sako da Trump ya aika ta shafinsa na dandalin sada zumunta na Tuwita a safiyar yau, ya ce ratsin da gidan talabijin na NASCAR ya yiwa direban Bubba Wallace ya bata masa rai sakamakon zarginsa da ake yi na kin jinin direban Bubba Wallace da kuma matakin da ta dauka na hana nuna tutar Confederate a tarukan da ta ke yi.
A hasashen da aka yi, yawancin tambayoyin na tattare ne da sakon na Tuwita a matsayin 'yar jarida bayan da 'yar jarida ta yiwa McEnany wasu tambayoyi da aka tsara domin su sa ta fadi cewa Trump na goyon bayan tutar Confederate.
McEnany ba ta bayar da amsar da 'yan jarida ke so ba - wani sautin barkwanci da zai cutar da Trump - sai dai ta mayar da martani a kai-a kai tana mai cewa shugaban bai dauki matsayi a kan tutar Confederate ba kuma dunkulallen sakon nasa shi ne magoya bayan NASCAR sun yi laifi ana nuna su a matsayin masu nuna wariyar launin fata.
Kamfanin dillancin labaran AP ya ce ta yi "kaduwa" a lokacin da ta ke gabatar da jawabinta.
Wannan labari na AP ya fito ne daga wani shafi da jaridar Washington Post ta bude-baki a farkon watan nan, na wani dan jarida na gidan talbijin na ABC Jonathan Karl, wanda kuma shi ne shugaban kungiyar 'yan jarida ta Fadar White House.
Karl ya yi gargadin cewa, "yin musun gaskiya da kuma amfani da gidan talbijin na White House saboda dalilai na siyasa, keta haddin amincewar jama'a ne".
Amma duk da haka irin saurin fushi da salon kamun ludayin McEnany ya sanya ta zama gwarzuwar wasu magoya bayan Trump, tun lokacin da ta ba da takardarta ta farko a ranar 1 ga watan Mayu bayan da ta hau mukamin sakatariyar yada labarai a watan Afrilu.
Masu matsin lambar sun shafe fiye da shekara guda kafin nadin nata.
Kamar sauran fannoni na rayuwar siyasa a birnin Washington, dangantakar sakataren yada labarai na fadar White House da kafofin yada labarai ta sauya sosai a zamanin mulkin Trump.
Wannan canji ya fito ne daga garesu kuma ya fi dacewa da zuwan McEnany.
Rufin asiri na tsohuwar sakatariyar yada labarai Sarah Huckabee Sanders wacce mawakiya Michelle Wolf ta yi a fadar White House "liyafar cin abincin dare a watan Afrilun 2018 ya yi matukar tashin hankali, har ma MSNBC mai masaukin baki Mika Brzezinski ta kira shi" abin Allah wadai".
'Yar Majalisar Wakilai ta Fadar White House Jill Colvin ta gaida McEnany a zantawarta ta farko da tambayarta, "shin ko za ka dage cewa ba za ka taba yi mana karya ba daga wannan talbijin din?"
Mai nazari kan harkokin siyasa na gidan talbijin na Fox Brit Hume, wani tsohon soja da ya kwashe sama da shekaru 50 yana aikin jarida wanda ya kwashe shekaru 1989-1996 a matsayin babban jami'in gidan talbijin na ABC a Fadar White House, ya ce a yau 'yan jarida na nuna "halayya mai tsanani" a dakin taron na 'yan jaridu saboda tunanin da suke yi na cewa Trump ba zai yi nasara ba.
Saboda mayar da hankalinsu kan kin jinin Trump ne, ya ce a wannan makon kan shirin Tucker Carlson Tonight na Fox, 'yan jarida na sakaci wajen tattara labaran manufofi.
"Ba kawai wasan gotcha ba ne", Hume ya ce game da manufar masu matsin lambar da ake so.
"Ba wai kawai wani yunkuri ne na kunyata wani jami'in jama'a ba. Don cire bayanai ne".
An ga jariran wurin shakatawa na safara dauke da wukake, da direbobin tasi da kuma CHAINSAW a matsayin'masu fasa-kwaurin mutane suna ba su makamai don su yi karuwanci'
Wurin shakatawa na safara na Knowsley, Merseyside, an dade da sanin cewa duk wanda ya dakata a cikin korama sai ya ciji wani mai goge baki ko madubi.
Jarirai sun kasance dauke da wukake, da kururuwa har ma da kujeru a wurin shakatawa na Knowsley safari, da Merseyside.
Ma'aikata na fargabar masu fasa-kwaurin mutane na yin garkuwa da pesky primates, wadanda aka san su da yin fasa-kwaurin duk wani wanda ya dakata ya kuma kwace windscreen wipers da madannai.
A yanzu ma'aikata na fargabar cewa suna dauke da makamai masu linzami "don dariya" ta yadda masu ziyara za su kubuta daga hare-haren da suke kai wa, har ma an ga aparoman na jita-jita a kusa da akwatunan kayan wasan kwaikwayo da kansu.
Wani ma'aikacin wurin shakatawa ya fadawa jaridar Sunday Times cewa: "Ba mu da tabbacin ko wasu daga cikin bakin da ke son ganinsu ne ke ba su makamai suna kai hari kan motoci, ko kuma idan suna kamun kifi ne daga cikin motoci masu sulke da kuma riguna masu sulke".
"A zahiri za su shiga cikin akwatunan kayan wasan mutane su dauke su. An ga daya daga cikin jariran yana luggude a kusa da wata kujera".
Wani ma'aikaci kuma cewa ya yi: "An samu jariran da wukake da kuma direbobin tasi, ina mamaki ko wasu ne daga cikin bakin da ke ba su hannu".
Kuma wannan harin na baboon babu makawa sai dai makanikai a fadin arewa maso yammacin Ingila sun san makamar aiki da kyau.
Daya daga cikin makanikai a Sale, Greater Manchester ya ce mutane sun san abin da za su yi tsammani a wurin shakatawa kuma ya samu abokan cinikinsa biyu sun fada hannun jariran a wannan shekarar.
Sun kuma kara da cewa minti daya yara ke son kubuta a mota, na gaba kuma ba shi da farantin rajista - amma batun ya samar da "kudi mai kyau" ga garejin.
Knowsley ya sake budewa a ranar 15 ga watan Yuni da matakan tsaron Covid-19 bayan da ya dage cewa yana da hadari kamar tafiye-tafiyen McDonald ta yadda masu ziyara ba za su bar motarsu ba a tafiyar mil biyar ta safara.
Wurin shakatawa mai fadin eka 5, da gida ga zakuna, da damisa, da rhinos, da wildebeest da kuma rakuma, sun yi watsi da rahotannin nada makamai a matsayin tatsuniya ta birane.
Mai magana da yawun 'yan sandan ya ce: "Mun yi imanin cewa ire-iren wadannan labaran sun karu cikin tashin hankali kamar yadda aka sake fada musu, tare da jajircewa wajen yin abubuwan da a wasu lokutan a kan same su a cikin korama kamar dai yadda ya fi ban sha'awa da rashin imani".
A shekarar 2012 kamfanin kera motoci na Hyundai ya bari kuda 40 daga wurin shakatawa ya yi sako-sako da samfurin New Generation i30 har na tsawon awanni 10 domin tabbatar da cewa yana da karfin iyalai da kananan yara.
Kudlow ya ce kudirin dokar kariyar cutar Koronabirus na gaba zai hada da karin bincike, da tsawaita tarzoma kan tantancewa
Mai baiwa fadar White House shawara kan harkokin tattalin arziki Larry Kudlow ya yi alkawari a ranar Lahadi cewa gwamnatin tarayya za ta tsawaita dokar hana fita da kuma sake aikawa da wani zagayen binciken a matsayin wani bangare na kudirin yaki da cutar Koronabirus na gaba.
Wadannan kalamai na Kudlow na zuwa ne bayan mako guda da fadar White House ta yi fatali da bukatar karin kudin haraji da 'yan majalisa suka yi ta harbawa.
"Da akwai rajistan $1,200 da ke zuwa. Wannan zai kasance cikin sabon kunshin. Da na fi so a biya ni haraji, a saman wannan rajistan", in ji Kudlow a shirin "State of the Union" na gidan talabijin na CNN.
"Amma, ka zama cewa kamar yadda zai iya, a siyasance, ba ya aiki".
Duk da cewa babu wata yarjejeniyar da aka sanar a hukumance, Sakataren Baitulmali Steve Mnuchin da kuma shugaban ma'aikata na fadar White House Mark Meadows sun kasance a Capitol Hill kwanan nan don tattauna bayanan wani sabon kayan agaji tare da shugabannin majalisa.
A kan kawo karshen karin dala 600 na rashin aikin yi da gwamnatin tarayya ke kawowa, Kudlow ya yi jayayyar cewa karin kudin na cutar da kananan kamfanoni daga ma'aikatan haya.
"Mun samu ambaliyar tambayoyi da kiraye-kiraye ta waya da korafe-korafe cewa kananan shaguna da kasuwanni, gidajen abinci ba za su iya daukar hayar mutane su dawo ba", in ji shi.
"Sun yi nisa. Watakila a watan Maris da ya wuce, ya zama dole a yi hakan, amma, da gaske ne, akwai sakamakon da mutane ba su koma bakin aiki ba".
Mnuchin a ranar laraba a shirin "Fox News Sunday" ya na mai cewa sam ba haka ba ne: "Ina ganin ma'aikata da Amurkawa sun fahimci manufar cewa ba za a biya ku albashi mai tsoka ba don ku zauna gida fiye da yin aiki".
Mnuchin ya ce, sabon kudurin zai samar da karin guraben aikin yi, amma ya lura cewa, ba zai wuce biyan kudaden da aka bayar a karkashin dokar kwadagon ba.
Ya ce, wasu ma'aikata suna tattara fiye da yadda suke samu a kan aikin.
Sakamakon haka, a lokacin da aka bude kasuwanni wasu ma'aikata ba su samu daman komawa bakin aikinsu ba.
Sakataren ya ce gwamnatin Trump da 'yan majalisar wakilai na kan shafi guda da kunshin dala triliyan 1, amma ya lura cewa a sha'anin zartar da kudurin cikin sauri, batutuwan da suka fi wahalar tattaunawa da 'yan Democrat za a iya kawar da su daga wani kudirin doka.
An Kama Mutumin Da Ake Zargi Da Kashe Ɗan'uwa Mai Alfarma A Noida Mai Girma:'Yan Sanda
An kama wani mutum dan shekara 37a ranar Lahadi saboda zarginsa da kashe dan uwansa, wanda aka tsinci gawarsa a wani wuri da aka ware mako guda da ya wuce, a Uttar Pradesh's Greater Noida, in ji 'yan sanda.
Wanda ake zargi ya fadawa 'yan sanda cewa barawon dan uwansa ne ya kwaso shi da kuma rashin da'a ga mata 'yan uwansu na hadin gwiwa, wanda hakan ya kai shi ga aikata laifin, a cewar jami'ai.
An gano gawar Bhisham Singh, wani mazaunin kauyen Bisrakh da ke Greater Noida, a kusa da bukkoki a wani wuri da aka killace shi kusan mako guda da ya wuce.
Alamomin ciwon jikin da kuma FIR an ajiye su ne a ofishin 'yan sanda na Bisrakh kuma an soma bincike, in ji wani mai magana da yawun 'yan sanda.
"A yayin samamen, shaidu sun kai 'yan sanda ga mutumin da ya mutu, da dan uwansa Deepak kuma aka yi masa tambayoyi. Da aka yi masa tambayoyi, Deepak ya furta cewa zai dabawa dan uwansa wuka har ya mutu. Ya fadawa 'yan sanda cewa Bhisham zai rika yawan cinye barasa, ya kirkiri ruckus a gida ya kuma bata ran mata 'yan uwa saboda haka ya yanke shawarar kashe dan uwansa", a cewar kakakin.
An kuma kama wadanda ake zargi da laifin kisan kai da kuma wasu tuhume-tuhume masu alaka da hakan, in ji 'yan sanda.
Rock daga duniyar Mars ya koma gida bayan shafe shekaru 600,000 a duniya
Za a jefi wani dan karamin dutse a sararin samaniya a wannan makon a daya daga cikin wasu muryoyi mafiya hadari da aka taba yunkurowa a sararin samaniya.
Wani dan karamin yanki na Martian basalt mai girman tsabar kudi 10p za a kaddamar da shi a cikin jirgin bincike na robot na Amurka a ranar Alhamis kuma an yada shi zuwa ga duniyar ja a cikin tafiya na watanni goma zuwa ga duniyar gida.
Wannan wari mai ban al'ajabi, wanda ya yi daidai da aikawa da garwashin wuta zuwa Newcastle, zai samar da wani muhimmin bangare na balaguron da Nasa za ta yi a duniyar Mars 2020 mai zuwa.
Injiniyoyin binciken sararin samaniya sun ce dutsen - wanda gidan adana kayan tarihi na Halitta da ke London ya bayar da shi - za a yi amfani da shi ne wajen kalato abubuwan da aka gano a cikin jirgin na robot rover Perseverance bayan da ya sauka ya kuma fara bincikensa kan alamun rayuwar da ta gabata a doron kasa.
Wasu daga cikin 'yan mitsi-mitsin Martian da muke da su suna da matukar ban tsoro, amma mun zabi wannan ne musamman saboda yana da tauri kamar tsohon takalmi
"Idan ka kunna kida sai ka fara tuntubarsu kafin ka yi amfani da su wajen bincike, sai ka kalle su a kan kayan da za su zama kamar abubuwan da ba a san ko su wanene ba da ka ke gab da yin nazarinsu. To, me ya fi kyau ka yi nazarin duwatsu a duniyar Mars fiye da wani tsalle da ya samo asali a can?" In ji Farfesa Caroline Smith, mai nazarin tarihin dabi'ar Halitta na meteorites.
Masana kimiyya sun hakikance cewa dutsen da suke komawa duniyar Mars ya samo asali ne daga doron kasa, in ji Smith, wanda shi ma memba ne a kungiyar kimiyya ta duniyar Mars 2020.
"Wani dan karamin kumbo na iskar gas da aka makala a cikin wannan karfen yana da matsayi iri daya da yanayin duniyar Mars, saboda haka mun san cewa dutsen da muke ciki ya fito ne daga can"
Ana tunanin cewa an kirkiri karfen Martian ne a lokacin da wani nau'in asteroid ko comet ya dulmuya a doron kasa kimanin shekaru 600,000 zuwa 700,000 da suka wuce, inda ya fesa tarkace a sararin samaniya.
Daya daga cikin irin wadannan rubuce-rubuce ya zube a tsarin amfani da hasken rana, daga bisani kuma ya rikide ya koma doron kasa.
Wannan karfen - wanda a yanzu ake kira SAU 008 - an gano shi ne a Oman a shekarar 1999 kuma ana kula da shi a gidan adana kayan tarihi na Halitta tun daga wannan lokacin.
Daga cikin kayan da suka dace da robar Perseverance akwai laser mai daidai-wa-daida da ake kira Sherloc, wacce za a yi amfani da ita wajen ragargaza sinadaran da duwatsu ke dauke da su da kuma sanin ko za su iya dauke kwayoyin halittar da ke nuna rayuwa ta taba wanzuwa - ko kuma har yanzu akwai - a duniyar Mars.
Hada wani yanki na SAU 008 an yi shi ne don tabbatar da cewa an yi hakan tare da daidaito cikakke.
Smith ya kara da cewa, "wannan dutse da muke aikawa an zaba shi ne musamman saboda abu ne da ya dace dangane da sinadarai, amma kuma dutse ne mai wuyar sha'ani".
"Wasu daga cikin 'yan mitsi-mitsin Martian da muke da su suna da matukar firgitarwa. Wannan karfen yana da tsauri kamar tsohon takalmi".
Da zarar Perseverance ya zabi duwatsu mafiya alamar da zai iya samu, zai tsallake su a cikin rairayin bakin teku a farfajiyar Martian.
Bayan haka za a dawo da wadannan ta hanyar yin amfani da robot da ya biyo baya a kuma makalesu a sararin samaniya zuwa doron duniya don bincike.
Barcelona 'na da duk wata kungiyar da za ta sayar da ita'a bazarar nan kamar yadda Coutinho da Dembele da Rakitic da kuma Vidal duk suka lissafa domin sauya sheka
Barcelona za a san ta a matsayin kungiyar da ke sayar da 'yan wasa a wannan bazara, a cewar rahotanni.
Babu wasu taurarin 'yan wasa 12 na farko da mahukuntan gasar ta La Liga suka sauya wa suna, in ji Marca.
An yi ta rade-radin cewa Philippe Coutinho ya sauya sheka daga Barcelona
Kuma wadanda suka hada da masu buga gasar Premier Philippe Coutinho da Ousmane Dembele da Ivan Rakitic da kuma Samuel Umtiti.
Ana alakanta Coutinho da Umtiti da koma wa Arsenal, yayin da ita ma kungiyar kwallon kafa ta Brazil, Chelsea ta ke ci mata mutunci.
Yayin da Manchester United da Tottenham suka ce suna cikin yakin neman ayyukan da Rakitic ke yi.
Dembele dan kasar Faransa da ya yi fama da jinya a lokacin wasa a Camp Nou, a baya-bayan nan an alakanta shi da komawa PSG a wata yarjejeniya ta musammam da Neymar.
Sauran 'yan wasan da ake ganin sun zarce bukatun sun hada da Neto da Nelson Semedo da Junior Firpo da Arturo Vidal da Martin Braithwaite da Carles Alena da Rafinha Alcantara da kuma Jean-Clair Todibo.
Barcelona na fatan fitar da ita a bayyane ba wai kawai zai kara mata kudi ba ne, har da taimakon kasuwancin musayar 'yan wasa da za su yi a nan gaba.
An kuma ce Ousmane Dembele zai yi kasa da bukatun da ake bukata
A cewar jaridar ta Sipaniya, tuni Barcelona ta gano sauye-sauyen da ta ke son yi a kakar wasa mai zuwa - inda dan wasan gaba na Argentina Lautaro Martinez ke kan gaba a jerin 'yan wasan da ta ke bugawa.
Sai dai Inter Milan na ci gaba da neman a biya shi diyyar fam miliyan 101m kafin su tattauna da 'yan Catalan.
Barcelona za ta sayar da ita kafin ta iya sayenta, amma ta na da kwarin gwiwar cewa za ta iya kulla yarjejeniya da kungiyar da ke buga gasar Serie A.
Barcelona "ta yiwa Arsenal Philippe Coutinho tayin sayen dan wasan bad-boy Guendouzi" yayin da Gunners ke kokarin korar dan wasan tsakiya
'Yan Fashi Da Makami 200-Sun Sake Kashe Karen Wuta Da Aka Kona A Kwarin Jurupa - Muryar Arewa
Jurupa VALLEY (CBSLA) - Wata wutar daji ta tashi a ranar Asabar da rana a kwarin Jurupa, lamarin da ya kai ga mayar da martani ga ma'aikatan kashe gobara sama da 200.
An bayar da rahoton tashin gobarar ta Karen ne bayan karfe 3 na yamma a kan titin Sierra Avenue da kuma Karen Lane.
Wutar dajin ta karu daga kimanin eka 5-10 zuwa wajen eka 250 ya zuwa karfe 8 na dare.
A karshe binciken da aka yi ya nuna cewa kashi 50% ne da kuma ma'aikatan kashe gobara 225 daga ma'aikatar kashe gobara ta Cal, da ma'aikatar kashe gobara ta gundumar Riverside, da ma'aikatar kashe gobara ta birnin Corona, da kuma hukumar kashe gobara ta gundumar San Bernardino suna kan aikin kashe gobarar.
An dakatar da ci gaba da barin wuta, amma ana sa ran albarkatu za su kasance ba dare ba rana domin sa ido kan yanayi.
Ba a bayar da rahoton jin rauni ko barnar da gine-gine suka yi ba, kuma ba a bayar da umarnin a kwashe su ba.
An rufe wurin shakatawa na Sierra Avenue tsakanin Armstrong da kuma layin dogo na San Bernardino.
Wani babban jami'in Majalisar Dinkin Duniya ya tsallake rijiya da baya a ziyarar da ya ke yi a Pakistan, kan batun jirgin
Shugaban Majalisar Dinkin Duniya mai shigowa Islamabad (AP) ya sanar a ranar Lahadi cewa ya dage ziyarar da ya shirya zai kai Pakistan "saboda wasu matsaloli na jirgen fasaha".
An zabi jami'in diflomasiyyar Turkiyya Volkan Bozkir a matsayin shugaban zaman babban zauren Majalisar Dinkin Duniya karo na 7 a watan da ya gabata, an kuma shirya zai isa birnin Islamabad a ranar Lahadi.
Amma a wani sako da ya sa a shafinsa na dandalin sada zumunta na Tuwita, ya ce ziyarar da zai kai babban birnin na Pakistan sai ya jira.
Ministan harkokin wajen Pakistan Shah Mahmood Qureshi ya mayar da martani ga Bozkir yana mai cewa "Ina sa ran yi maka maraba da zuwa Pakistan nan ba da jimawa ba don ziyarar mai cike da sarkakiya da 'ya 'ya".
A ranar laraba da ta gabata, wani jamai'i Qureshi, a lokacin da ya ke sanar da wannan ziyara, ya yi fatan cewa zai tattauna batutuwa masu yawa da Bozkir, ciki har da Kashmir, wacce ta rabu tsakanin Pakistan da Indiya mai makwabtaka, ta kuma yi ikirarin cewa dukkanninsu a cikin ta suke.
Pakistan da Indiya sun gwabza yaki biyu daga cikin ukun da suka gwabza a kan yankin da ake takaddama a kansa tun bayan samun 'yancin kai daga Turawan Ingila a shekarar 1947.
A wasu lokutan bangarorin biyu na musayar wuta a Kashmir, lamarin da ya haddasa jikkatar dakaru da fararen hula a bangarorin biyu.
Pakistan na son Majalisar Ɗinkin Duniya ta taka rawar gani wajen warware batun Kashmir a ƙarƙashin ƙudurorinta ta hanyar barin mutanen da ke zaune a yankin Himalayan su yanke shawarar ko suna so su ci gajiyar Indiya, da Pakistan ko kuma sun fi son 'yancin cin gashin kansu.
'Me ya faru a wurin?!'
'Yar damben UFC Correia ta samu kubuta bayan da ta juya baya ga abokiyar hamayyarta da ta yi kuskuren tunanin zagaye na biyu (VIDEO) - RT Sport News
Bethe Correia 'yar kasar Brazil mai rike da kambin bantamweight 'yar asalin kasar UFC ce, amma ta yi kuskuren mayar da ita abokiyar karawarta Pannie Kianzad, ta kuma yi kuskuren tunanin cewa zagayen ya kare a fafatawar da suka yi a tsibirin Fight Island, kuma ta samu tagomashi sakamakon hakan.
Zuwa karshen stanza na farko na karawarsu a katin karkashin kasa a Abu Dhabi, Correia 'yar shekara 37n ta bayyana cewa ta yi kuskuren gargadi na 10 na ainihin karshen zagaye, inda ta kai gaisuwar ban girma kafin ta juya baya ga Kianzad ta kuma kama hanyarta ta komawa kusurwa.
'Yar damben 'yar kasar Sweden da aka kamo ba tare da jinkiri ba, ta dagawa abokiyar adawarta hannu da dama kafin ta bi diddigin jerin gwanon da aka yi don mayar da Correia keji.
A lokacinda ya bayyana cikin hadari, dan Brazil sai ya sake samun iko ya tunkari barazanar ya kuma mara wa Kianzad baya kafin a kira ainihin karshen zagayen.
"Me ya faru a wurin? Toh maganata", an ji kungiyar sharhin a ESPN + tana furuci.
Wannan dai wani bangare ne na wani dare mai cike da takaici ga tsohuwar mai kalubalantar kambin bantamweight Correia, wacce ta sauka daga karagar mulki sakamakon rashin nasarar da ta yi wanda shi ne rashin nasararta ta uku a wasanninta hudu na octagon da suka wuce, ta kuma bar tarihin da ta kafa gaba daya a 11-5, da canjaras daya.
Ga Kianzad haifaffiyar kasar Iran, 'yar shekara 28, nasara ce ta biyu a juya bayan nasarar da ta samu a kan Jessica-Rose Clark a gasar damben UFC da aka yi a Moscow a cikin watan Nuwamba.
Yanzu Kianzad ita ce ta 13-5 gaba daya da kuma 2-1 a gasar damben UFC, kamar yadda matar da aka fi sani da 'Banzai' ta ke da niyyar daga martabar 135lbs.
A wani wuri kuma a daren, Robert Whittaker dan kasar Australia ya fitar da Darren Till na Ingila a gasar matsakaita ajin matsakaita, yayin da dan asalin kasar Russia, Khamzat Chimaev ya kafa tarihi na lashe fadan na biyu a cikin kwanaki 10 a tsibirin Fight Island, wanda shi ne mafi gajeren lokaci da aka taba yi tsakanin nasarorin da aka samu a gasar damben zamani na UFC.
Watford ta fice daga gasar firimiya yayin da Aubameyang ya godewa Arsenal
Wasu daga cikin 'yan wasan Watford sun yi ta rera waka a gwiwarsu; wasu kuma sun yi ta rami ba tare da wani bata lokaci ba.
Karrama su da aka yi a tsawon shekaru biyar da suka yi a gasar ta firimiya kuma babu wanda zai iya cewa uffan, a lokacin da bikin ya bukace su da su jefi mai dafa abinci a ragar Arsenal, sai suka sauka ba tare da wani fada ba.
Wannan aiki ne da ke cike da rikice-rikice, gaggawa da kuma zalunci da suka dakushe kyakkyawan aikinsu a tsawon shekaru goma da rabi da suka gabata, amma abin ya zo a makare, kamar yadda damben da kusan ya kanannade gibin makin kwallaye uku a ranar.
Da Emiliano Martínez bai yi kasa a gwiwa ba ya ceci dan bayan Danny Welbeck mintuna 16 da dawowa daga hutun rabin lokaci, jim kadan bayan da tsohon abokin wasansa ya yi kunnen uwar shegu da saka Watford cikin kwallaye biyu na kare lafiya, da akwai duk wata dama da za su iya samu ta kammala haduwa da su tsawon shekaru.
A karshen sun fadi kasa warwas kuma mai kula da su, Hayden Mullins, na iya nuna cewa ba za a taba mika masa wannan ayyuka marasa godiya ba idan da a ce kungiyarsa ta nuna irin aikace-aikacen da aka yi kwatankwacinsu a baya.
A duk tsawon kakar wasa ba su isa ba, amma kuma kungiyar da ke aiki da su ba ta isa ba.
Wani yakin da talakawa ke yi ba zai wofintar da daula ba, amma kuma harsashen da iyalan Pozzo suka sa a gaba ba su bayar da tabbacin cewa za su mike tsaye su dawo daga rakiyar ta biyu ba.
Da wuya a iya tserewa ganin cewa dabi'ar manajojin tasi na Watford ta fita daga kangin fatara.
Wa'adinsu na dindindin na gaba - watakila ma'ana mafi girma - alƙawari zai zama na 12 a cikin shekaru takwas kuma iska mai ƙarfi ne kaɗai sabon faifai zai iya zub da jini.
Troy Deeney na fuskantar koma baya duk da cewa ya samu takardar zura kwallo a ragar Emirates.
'Yan wasa za su tashi, Isma'il la Sarr ya sake nunawa a nan cewa ba za a iya ganewa ba zai buga wasan kwallon kafa na Championship a watan Satumba, kuma hannunka mai kwari ya zama abu mai muhimmanci.
Babu wani abin a zo a gani da aka yi game da damben boksin din a wata arangama da aka yi da Mikel Arteta wanda aka kwatanta da "wani dan wasan kwallon kwando", duk da cewa lallai an yi shi ne don nishadi mai kyau.
Arteta ya ce bayan haka kungiyar Watford ta yi "raha", ko da yake cikin sauri ya bayyana cewa a matsayin lokacin wasan kwallon kafa na "yin caca, zama a gaba".
Babu shakka suna da bukatar: Duk wata shawara da za a bayar ta fadakarwa daga baya ta ishe su cikin sauri kuma suna iya mamakin yadda abubuwa za su kasance idan da a ce ba a wajabta musu yin wasan kasa-da-kasa ba.
A maimakon haka sai suka zartar da hukunci kusan nan take.
Craig Dawson ya daure karsashin Alexandre Lacazette cikin dakika 40 amma sai da ya dauki VAR kusan mintuna uku kafin ya samu tabbacin bayar da bugun tazara, wanda Pierre-Emerick Aubameyang ya aika ba tare da bata lokaci ba.
Watford sun tattara kansu don su latsa ba tare da bata lokaci ba, tare da Sarr a nau'in lantarki a dama, kuma sun zo kusa ta hannun Roberto Pereyra da Troy Deeney.
Amma sai ga shi Aubameyang ya hakura da Kieran Tierney a bugun daga kai sai mai tsaron gida, a hutun shan giya na farko, wasan ya yi kunnen uwar shegu, har Arteta ya zama manaja yana gab da tube 'yan wasansa duk da cewa Arsenal ta yi amfani da su.
Daga nan ne Aubameyang ya sarrafa doguwar rigar da Tierney ya jefa ya kuma maida murtani sama wanda hakan ya sa ya zura kwallo daya a ragar takalmin zinare, lambar yabon da zai raba wa Jamie Vardy idan da Ben Foster bai toshe wata dama ta karshe ba a karshenta.
Watford ta bayyana cewa ta yi hakan ne amma sai suka nace, bayan da David Luiz ya sake samar da wani kalubale mai cike da rudani ga album din Welbeck, Deeney ya yi ramuwar gayya a fafatawar da ya yi kafin tafiya hutu.
Deeney da ke tafiya ya samu raunuka a yawancin lokutan, ya jinjinawa kansa a kusa da faretin kuma yana cikin yanayi na farin ciki a ko ina.
Da watakila ya godewa damar da Adamu Masina ya barar da ita da wuri a karo na biyu da kuma kara budewa da aka yi, shi ma ya yi nasara.
Welbeck ya yi amai ya lashe a karon farko da kyakkyawan Martínez, wanda Arteta ya tabbatar da cewa zai fara wasansu na karshe na cin kofin FA a ranar Asabar, sannan kuma ya sa dukkanin tulun wasan na Watford na gama-gari a kafafunsu a lokacin da ya ke mayar da fizgar ketar daga Sarr.
Sai dai kuma karbuwar da Watford ta samu ta ragu a lokacin da aka gyara kokarinsa na gaba da kuma binciken kwakwaf da ake yi na kud-da-kud, daga sama har kasa, zai bukaci a yi masa zurfi.
An tsinci gawawwakin uwa, an tsinci jarirai 2 a cikin mota makare da kandami
Augusta, Ga. - Hukumomi sun ja wata mota mai sarafa kanta daga wani kandami na Georgia kuma sun gano gawawwakin wata mata da 'ya 'yanta tagwaye 'yan watanni 10 a ciki.
Ofishin Sheriff na gundumar Richmond ya ce kiristoci sun gano motar ne a kandun Magajin gari a watan Augusta a ranar Juma'a da rana, jaridar The Augusta Chronicle ta ruwaito.
Shugaban Karamar Hukumar Richmond Mark Bowen ya ce dukkannin wadanda abin ya rutsa da su guda uku, an tabbatar da cewa sun mutu a wurin.
Hukumomi sun bayyana gawawwakin a matsayin Shaquia Philpot 'yar shekara 25 da kuma 'ya 'yanta jarirai Caysen da kuma Cassius Williams.
Jami'ai ba su yi cikakken bayani ba game da yadda iyalin suka ƙarƙare a cikin kandami.
Wani wanda ya ke kamun kifi a yankin, ya tarar da motar, a cewar Bowen.
Za a aika da gawawwakin ne zuwa ofishin binciken manyan laifuka na Georgia domin yin kwas.
Har yanzu dai ana kan bincike kan lamarin.
An gano wani mutum da raunukan harbin bindiga a Mambourin kusa da Werribee
An garzaya da wani mutum asibiti bayan harbin da aka yi masa a yammacin Melbourne cikin dare.
An kira 'yan sanda zuwa Mambourin da ke kusa da Werribee da misalin karfe 8 na dare inda suka tarar da wani mutum dan shekara 20 da haihuwa da wasu raunuka da ake zaton na harbin bindiga ne a jikin karamar hukumar da ke Yard St.
An garzaya da mutumin asibiti sakamakon raunin da ya samu na rashin rai da rai.
'Yan sanda sun ce ana ci gaba da bincike.
Hukumar kwastam ta tura rangwame daga filayen jirage, da majalisu
Ooh! Kafofin yada labarai sun tayar da babban birnin kasar a farkon wannan shekarar don samar da karin tabbaci na kudi yayin da annobar ta fara yaɗuwa ga masu talla.
Kafofin yada labarai na cewa, kamfanonin na tattauna hanyoyin da za su bi wajen ragewa manyan raguwa ta hanyar rage kudin haya ga shafukan da suke aiki ko kuma ta hanyar cirewa ko rage garantin samun kudaden shiga mafi karanci, wanda ake gabatarwa a dai dai lokacin da aka fara sanya hannu kan yarjejeniyar.
Wata majiya na nuni da cewa watakila manyan kamfanonin da suka mallaki bilyoyin kudade sun tabbatar da cewa sun kai kashi 85 cikin 100 na kudaden shigar da suke samu a matsayin kudin haya.
Wasu kwangilolin na da daki-daki da ke ba su damar rage garanti mafi karanci idan adadin mutanen da ke wani yanki ya ragu da wani kaso, amma ba a sani ba ko wannan yanayin na cikin wasu kwangilolin da ake da su a yanzu tsakanin kamfanonin biliyoyin da kuma ƴan kasuwarsu.
A sa'i daya kuma, kamfanonin suna bayar da rangwame mai yawa ga masu talla domin cike guraben da ake da su a kan biliyoyin kudi, su kuma ba su kudi mafi daraja.
Billboards a Sydney CBD da kuma m unguwannin da cewa yawanci dauki bakuncin shida talla suna fafitikar cika duk na samuwa ramummuka.
Amma wasu shafuka - irin su oOh! An kyautatawa kafofin yada labarai naira bilyan 40 x 10 a filin jirgin saman Sydney.
Ooh! Kafofin yada labarai sun ki su ce uffan, amma a wani taro da aka yi a Macquarie Australia a watan Mayu, an fitar da kudi fiye da dala miliyan 20 na kudin haya da aka ajiyesu.
Sai dai JC Decaux ya ki ya ce komai.
Filayen Jiragen Sama da jigilar jama'a kwangilolin talla ne masu tsoka ga kamfanoni bilyoyin kudade.
A cewar Rahoton kungiyar 'yan jarida na waje na shekarar 2019, kudaden da ake samu daga sufuri - ciki har da filayen jirage - sun kai dala miliyan 169.4 yayin da kudaden shiga daga kayan tituna da wajen shaguna da taragai ya kai dala miliyan 266.5.
JC Decaux kasuwanci yana da kwangila tare da Sydney Airport, Yarra Trams, Perth Airport da kuma Sydney buses. oh! Kafofin watsa labarai yana da billboards a yankunan kamar Qantas lounges, a waje da filin jirgin sama na Sydney, Adelaide Airport, Darwin Airport da kuma cikin tashoshin jirgin kasa a Sydney da Melbourne.
Masu bayar da tazara a filin jirgin saman Melbourne da kuma jiragen kasa na Sydney na cikin shirin ko-ta-kwana kuma kawo yanzu ba a yanke hukunci a hukumance ba.
Melbourne ita ce kwangilar filin jirgin sama ta biyu mafi girma a Australia kuma riga-kafin cutar Koronabirus ya kai dubban miliyoyi a kowace shekara.
A sakamakon cikar shekara a watan Fabarairu, oh! Kafofin yada labarai sun ce ta samar da dala miliyan 65.9 daga rukunin 'fly' dinta, wanda aka fi samunsa da kudaden shiga daga filin jirgin saman Sydney.
Kudaden shiga daga 'hada-hada', wadanda suka kunshi kwangilar shimfida layin dogo da kayan titina da Adshel ya mallaka a baya kafin Oh ya saye shi!, sun kai dala miliyan 234.8.
JC Decaux Australia ta samu dala miliyan 37.7 na kudaden shiga daga sufuri a shekarar 2018, a cewar sakamakon hada-hadar kudi na shekarar 2018 da ta shigar ga hukumar kula da ingancin kayayyaki da zuba jari ta Australiya.
Amma duka alkaluman biyu suna iya zama masu matukar kankanta a wannan shekarar.
Alkaluman Standard Media Index, wadanda suka bayar da rahoton kashe hudu daga cikin manyan rukunonin hukumar ad biyar, sun ce kasuwar sayar da kayayyaki a waje ta yi tashin gwauron zabi da kashi 68 a watan Yuni.
Idan aka kwatanta, sakamakon tsakani na watan Yuni ya nuna cewa yawan kudin da ake kashewa a fannin dijital ya ragu da kashi 37 cikin 100, yayin da rediyon metropolitan ya fadi da kashi 48 cikin 100.
Gidan talabijin na Metropolitan ya fadi da kashi 34 cikin 100 a watan Yuni, yawan kudin da jarida ke kashewa ya ragu da kashi 49 cikin 100 kuma kashe kudi a mujallu ya karu da kashi 66 cikin 100.
Leicester na farin ciki da buga tamaula a gasar kwallon kafa ta Turai in ji Jamie Vardy wanda ya lashe kyautar Golden Boot
Jamie Vardy ya amince da bacin ransa kan rashin fitar da shi daga gasar cin kofin zakarun Turai ta Champions League, amma ya ce Leicester City ta cimma manufarta ta samun gurbi a wasannin share fage na neman tikitin zuwa Turai.
Foxes su ne na biyu a watan Disamba da kuma na uku a lokacin da aka soma wasan kwallon kafa bayan da aka kulle su, amma sun samu maki hudu ne kacal daga wasanni biyar da suka buga na karshe da suka kammala a mataki na biyar a gasar ta Premier.
Da a ce Manchester United ta yi nasara a wasanta na kusa da na karshe, da hakan ya sa ta kai bantenta da ci hudu da nema, amma kuma Brendan Rodgers ya yi rashin nasara da ci 2-0, wanda Vardy ya ce shi ne fanni mafi ban haushi.
"Wannan abin kunya ne, fiye da yadda muka kawo karshen rashin nasara a wasan", yana mai cewa a shirin talbijin na SKY Sports a cikakken lokaci.
"Amma mun fada a cikin kayan miya, mun yi niyya a bayan kofofin da aka rufe na neman cancantar shiga Turai kuma mun yi hakan".
"Mun samu damar zuwa gasar zakarun Turai kuma hakan ya ma fi kyau, amma za mu yi tunani a kan hakan kuma mu dawo da karfi a shekara mai zuwa".
"Yana da wuyar dauka, amma babban burinmu shi ne Turai kuma mun yi nasarar yin hakan".
A yayin da kungiyarsa ta fadi kasa warwas, shi kansa Vardy ya kawo karshen kakar wasa ta bana a matsayin wanda ya fi cin kwallo a gasar ta Premier yana dan shekara 33 da haihuwa, a inda ya zura kwallo sau 23.
Ya jinjina wa abokan wasansa wajen samun lambar yabon, ya kuma ce har yanzu da akwai sauran milyoyi masu yawa da aka bari a wurinsa a matakin dan sama jannati, duk da cewa shekarunsa na haihuwa sun ja baya.
"Na yi murna matuka, duk game da kungiyar. Da ba zan kai matsayin da na ke ba na zura kwallaye ba tare da su ba, kuma na kawar da kai sosai".
"Zan dan samu hutu yanzu kuma in dawo don kakar wasa mai zuwa a shirye nike in tafi, abin farin ciki shine bana jin shekaruna sun kai, kafafuna har yanzu suna da kyau kuma taba itace ban dauko raunuka da yawa ba, don haka ina gab da ajiye wannan a saman wannan kuma in dawo da karfi kamar yadda zan iya a shekara mai zuwa".
Coronavirus: An umarci matafiya daga Spain su killace kan su
Matafiya da suka iso Burtaniya daga Spain yanzu dole ne su killace kansu na tsawon kwanaki 14, a karkashin sabbin ka'idojin tafiye-tafiye na coronavirus.
An sanar da hakan ne a ranar Asabar bayan samun karuwar wadanda suka kamu da cutar Koronabirus a kasar Spain, inda aka samu karin mutum sama da 900 da suka kamu da cutar a ranar Juma'a.
Jami'an kasar Spain sun kuma yi gargadin cewa za a iya samun barkewar cutar a karo na biyu a yayin da manyan birane suka ga karuwar wadanda suka kamu da cutar.
Kamfanonin sufurin jiragen sama ciki har da British Airways sun soki sabbin matakan da cewa "duk da haka wani babban nakasu ne" ga masu rike da mukamai a Birtaniya.
Ma'aikatar sufuri ta kasar Spain ta shawarci mutanen da ke hutu a halin yanzu da su bi dokokin cikin gida, su koma gida kamar yadda aka saba, sannan su duba shafin yanar gizo na shawarar tafiye-tafiye na ofishin kula da harkokin waje domin samun karin bayani.
Ofishin kula da harkokin waje na shawartar duk wasu tafiye-tafiye masu muhimmanci zuwa yankin Spain, duk da haka matakan tsuke bakin aljihun sun shafi wadanda suka dawo daga yankin Spain, da tsibirin Canary da kuma tsibirin Balearic, kamar Majorca da Ibiza.
Shawarar Ofishin Jakadancin Kasashen Waje na da ramuwar gayya kan inshorar tafiya.
Cikin wadanda sabbin ka'idojin suka shafa har da Sakataren Sufuri Grant Shapps, wanda ya fara hutunsa a kasar ta Spain a ranar Asabar.
Ana sa ran zai ci gaba da tafiyarsa kamar yadda aka tsara kuma ya killace kan sa a daidai lokacin da ake shirin komawarsa.
An fara gabatar da matakan tsuke bakin aljihu ga matafiya 'yan Burtaniya a farkon watan Yuni.
Amma bayan matsin lamba daga masana'antun sufurin jiragen sama da na tafiye-tafiye, gwamnati da kuma masu kishin al'umma sun wallafa jerin sunayen kasashen da suka fice daga dokokin.
Kamfanin sufurin jiragen sama na British Airways ya ce "abin kunya ne" game da sabbin sauye-sauyen da aka samu na shawarar tafiye-tafiye da dokokin da gwamnati ta gindaya, duk da cewa kamfanin jirgin ya ce jiragensa na ci gaba da aiki.
Yana mai cewa wannan mataki "ya jefa dubban 'yan Burtaniya da ke shirin tafiye-tafiye cikin rudani".
Kungiyar masu kula da filayen jiragen saman ta ce sabbin matakan za su "kara lalata abin da ya riga ya zama karfen kafa ga fannin sufurin jiragen sama wanda ke ci gaba da fuskantar babban kalubale a tarihinsa".
Babbar mai kula da yawon bude ido a Burtaniya, Tui, ta soke tashin jiragenta saboda tashi zuwa tsibirin Spain da kuma tsibirin Canary a ranar Lahadi.
Abokan huldarsu da ke hutu a halin yanzu za su iya komawa a jirginsu da suka nufo gida.
Duk da haka, kamfanin jirgin sama na EasyJet ya ce "abin kunya ne" kuma zai yi aiki da cikakken jadawali a cikin kwanaki masu zuwa.
"Abokan huldar da ba sa son yin tafiya za su iya sauya jiragensu ba tare da kudin canji ba ko kuma su karbi takardar neman izinin yin amfani da ita", in ji kamfanin a wata sanarwa da ya fitar.
Wani mai magana da yawun kungiyar masu kula da tafiye-tafiye ta Birtaniya (Abta) ya ce sauyin da gwamnatin kasar ta kebe na mulki "abin kunya ne".
"Muna bayar da shawarar cewa gwamnati ta yi la'akari da dage ka'idojin da aka kebe na zirga-zirgar jirage zuwa da wasu yankuna da ke da karancin wadanda suka kamu da cutar, ko kuma zuwa wasu wurare kamar tsibirin Balearic ko tsibirin Canaries - wadanda suke da banbancin kasa da tsibirin Spain - don kauce wa sake lalacewar masana'antun shigowa Burtaniya da fita yawon bude ido", in ji shi.
Kawo yanzu kasar Spain ta ga mutane sama da 28,000 da suka kamu da cutar ta Koronabirus.
A ranar Alhamis, an ga karuwar wadanda suka kamu a kowacce rana tun bayan da aka kawo karshen killacewar da aka yi mata.
Yankin Catalonia ya zama yanki na baya-bayan nan da ya yi kaurin suna wajen fasa kwaurin jama'a.
Yankin arewa maso gabas mai arzikin man fetur, wanda gida ne ga Barcelona, ya umarci dukkan kulob-kulob na dare da su rufe tsawon makonni biyu sannan su sa dokar hana fita da tsakar dare a wuraren da ke da matukar muhimmanci a Barcelona.
Wakilin BBC Guy Hedgecoe a Madrid ya ce cece-ku-ce tsakanin matasa wani abin damuwa ne musamman yadda suke taruwa a manyan birane da dare.
Kasar Faransa ta gargadi 'yan kasarta da kada su kuskura su je Catalonia yayin da kasar Norway ta ce za ta fara killace mutanen da suka zo daga Spain.
Gwamnati na kira ga ma'aikata da su zama "masu fahimtar wadanda suka dawo daga Spain wadanda yanzu za su bukaci su killace kansu".
Sai dai sakataren harkokin cikin gida na jam'iyyar Labour Nick Thomas-Symonds ya bukaci gwamnati da ta yi bayani dalla-dalla kan yadda za ta tallafawa wadanda abin ya shafa, yana mai karawa da cewa labarin zai yi "matukar illa ga iyalan da suka kama a Spain ko kuma suke shirin yin tafiye-tafiye"
Tun farko Ministar Scotland Nicola Sturgeon ta aika da sakon twitter cewa ta yanke wannan shawarar ce bayan ta yi bitar sabbin bayanan da aka samu a ranar Asabar da ta gabata.
"Wannan ya karfafa batun cewa wadannan al'amura na dada sauyawa a takaice, don haka shawarata ita ce in yi taka tsantsan da tafiye-tafiyen da ba su da muhimmanci a kasashen waje", a cewar ta.
John Blackmore, daga Hampshire, ya tashi ne tare da iyalinsa a Spain tare da matarsa da kuma 'ya 'yansa kanana guda biyu.
Sai dai kuma sabbin ka'idojin na nufin sai ya soke, saboda fargabar cewa ma'aikacin matarsa ba zai iya saukar mata da wani karin makonni biyu ba da zai sa a killace shi a lokacin da za su dawo.
Yana mai cewa yana ganin da kyar ne su samu sukunin maida jirgin, domin ba a soke shi ba.
"Na yi bakin ciki matuka", yana mai shaida wa BBC.
"Ina da iyali a Spain wadanda ba su ga jikokinsu kadai ba tun bayan bikin Kirsimeti".
Lois Stothard, daga kudancin Yorkshire, ta shaida wa BBC cewa ta kama hanyar zuwa Seville hutu ne saboda mamakin bikin cikar saurayinta shekara 30 da haihuwa - saboda tashi da ta yi a ranar Lahadi da safe - amma yanzu tana jin cewa ba za ta iya tafiya ba.
"Ni ma'aikaciya ce - Ni malama ce - kuma saurayina yana da sharadin aiki saboda haka ba za mu iya killace kanmu tsawon kwana 14 ba idan mun dawo", a cewarta.
"Ba za mu iya samun wasu makudan kudi ba kuma sauya kamfanin na son ninka abin da na riga na biya a kudade.
Na yi matukar kaduwa da kaduwa yayin da muke cunkushe kuma a shirye muke mu tafi".
Ted Cruz ya ce manufofin Pelosi na "harzuka tsabar kudi kan matsalar da kuma rufe Amurka"
Washington - Dan majalisar dattawa Ted Cruz na jam'iyyar Republican daga Texas ya zargi 'yan majalisar wakilai Nancy Pelosi da kuma 'yan jam'iyyar Democrat da tursasawa 'yan kwamitin bayar da agajin gaggawa da ke mayar da hankali kan "tsabar harbin kan mai uwa da wabi kan wannan matsala da kuma rufe Amurka" yayin da ake ci gaba da tattaunawa kan mataki na gaba.
A wata hira da ya yi da jaridar "Face the Nation" a ranar Lahadi, Cruz ya ce kasar na fuskantar rikice-rikice guda biyu a lokaci guda: Annobar da ta lakume rayukan mutane sama da 600,000 a duniya da kuma "cikkaken bala'in tattalin arziki" a Amirka.
Amma Cruz ya ce Pelosi, wacce ta fito a shirin "Face the Nation" a gaban sanata "," ta mayar da hankali ne a kan ko wanne daga cikinsu".
"Manufofinta suna harzuka tsabar kudi a kan matsalar da kuma rufe Amurka", in ji Texas Republican.
"Kuma musamman idan ka dubi takardar kudi ta dala triliyan 3 da ta ke kokarin turawa, kudin haram ne kawai ga abokanta ba wai magance matsalar a zahiri ba. Manufarmu ita ce Amurkawa su na so su dawo bakin aikinsu. Su na so ne su iya samarwa da iyalinsu abin yi".
'Yan Majalisar Wakilai da kuma Fadar White House sun shafe makon da ya gabata suna tattaunawa kan sharuddan da aka gindaya musu na mayar da martani kan cutar Koronabirus a karo na hudu, wanda suke sa ran za su kashe dala triliyan 1.
A karshen mako, shugaban ma'aikata na fadar White House Mark Meadows da Sakataren Baitulmali Steven Mnuchin sun koma Capitol Hill don karin tattaunawa da ma'aikatan Majalisar Dattawa, Mnuchin kuma ya fadawa gidan talbijin na Fox a wata hira da aka yi da shi a ranar Lahadi cewa ana saran bayanan za su fito ne daga bakin Shugaban Majalisar Dattawa Mitch McConnell a ranar Litinin.
Batun da ya fi jan hankulan 'yan majalisar - kuma wani batu na takaddama tsakanin 'yan Republicans da Democrats - shi ne karewar wa'adin da aka diba na inganta samar da ayyukan yi, wanda ya fara tafiya a karshen makon nan.
Yayin da ƴan Democrat ke son "kashi hudu" na kunshin coronavirus don ci gaba da bunkasa $600 don amfanin jama'a, 'yan Republicans na kira da a yi la'akari da shi kuma suna jayayya da cewa wasu Amurkawa suna samun karin albashi daga rashin aikin yi fiye da yadda suke yi a albashi.
Cruz ya ce fiye da rabin Amurkawa da ke samun karin kudin shiga ana biyan su albashi mai tsoka a yanzu fiye da lokacin da suke aiki, ya kuma ce yana magana ne da masu kananan sana'oi a Texas wadanda ke fama da matsala wajen daukar hayar ma'aikata.
"Tabbas, ba za su dawo ba saboda gwamnatin tarayya na biyan su, a wasu lokutan, sau biyu kudi su na zaune a gida", in ji shi.
Cruz ya ce kamata ya yi majalisa ta mayar da hankali wajen zartar da kudirin farfadowa da zai saukaka wa Amurkawa komawa bakin aiki ta hanyar saukaka haraji da ka'idoji kan kananan kamfanoni: "Maimakon kawai a rika harba makudan kudade a kofa, kudirin dawo da kudaden zai dakatar da harajin da ake biya, wanda hakan zai ba da dama a biya kowa a Amurka da ke aiki. Hakan zai sa mutane su koma bakin aiki", in ji shi.
Shugaba Trump ya bukaci a makon da ya gabata kayan agajin da za a biya na gaba sun hada da tsarin biyan haraji, amma Mnuchin ya ce ba zai kasance cikin dokokin ba, kamar yadda aka samu rashin jituwa a tsakanin 'yan jam'iyyar Republicans.
Mista Trump ya amince da cewa biyan harajin ba zai kauce daga kudiri na gaba ba, amma ya nemi dora laifin a kan 'yan jam'iyyar Democrats.
Cruz, wanda a makon da ya wuce ya yi watsi da kudin kunshin na gaba, ya ce a ranar Lahadi ba ya cikin jirgin tare da ma'auni daga 'yan uwansa 'yan majalisar wakilai.
Amma kuma ya soki kudirin dokar dala triliyan 3 da Majalisar Dattijai mai rinjayen 'yan Democrat ta zartar a watan Mayu, ya kuma zargi abokan hamayyarsa na siyasa da yin fatali da matakin da ya bata sunan shugaban kasa gabanin zaben watan Nuwamba da gangan.
"Manufa daya tilo da ƴan Democrat ke da ita, ita ce su kayar da Donald Trump, kuma sun yanke shawarar yadda za su kayar da Donald Trump, an rufe duk wata sana'a a Amurka, an kuma rufe kowace makaranta a Amurka", in ji shi.
"Ka sani, Nancy Pelosi ta yi magana a kan aiki maza da mata. Abin da ta ke samarwa shi ne ajiye aiki maza da mata daga aiki".
Rahul Gandhi Ya Godewa Mutanen Da Suke Rajistar Isara'ila
Rahul Gandhi na majalisa ya yada wani faifan bidiyo a yau yana kokarin dankwafar da mutanen da ke adawa da jam'iyyar BJP kan abubuwan da suka faru a Rajasthan.
Ta hanyar amfani da hashtag # SpeakUpForDemocracy, sakonsa na Hindia ya bukaci jama'a da su "hada kai su daga muryarmu don dimokuradiyya".
Majalisar na shirin gudanar da wata zanga-zangar kiristoci a ranar Litinin kan halin da ake ciki a Rajasthan, inda gwamnatin Ashok Gehlot ke fama da tserewa.
Yayin da jam'iyyar ta ce za a gudanar da zanga-zanga a kofar gidan Rashtrapati Bhavan, wato gidan shugaban kasa Ram Nath Kovind.
A cikin faifan bidiyon, majalisar ta zargi jam'iyyar BJP da "Rushe kundin tsarin mulki da rushe dimokradiyya" yayin da kasar baki daya ke yaki da cutar Koronabirus.
Haka ta yi a Madhya Pradesh, in ji 'yan majalisa.
"Mun bukaci da a gaggauta yin zaman majalisa wanda ya ke cikin hakkokin mu na yau da kullum", a cewar jam'iyyar a cikin bidiyon.
Gwamnan Rajasthan Kalraj Mishra ya juya baya ga batun daya gabatar na fara zaman majalisa.
An gabatar da na biyu a yau wanda ya ce yana nazari a kai.
Gwamnatin Mista Gehlot ta shiga cikin mawuyacin hali bayan da mataimakinsa Sachin Pilot ya juyawa 'yan tawaye baya tare da kawancen 'yan MLAs da ke goyon bayansa.
Jam'iyyar ba ta yi kasa a gwiwa ba wajen kawar da 'yan tawayen domin su kawad da alamar rinjaye a zauren majalisar.
Mista Pilot -- wanda aka tsame shi daga mukaminsa a jam'iyyar da kuma gwamnati -- wata babbar kotu a Rajasthan ta ba shi agaji na wucin gadi daga rashin cancanta, wacce ta ke rike da mukamin kakakin majalisar ba za ta iya daukar wani mataki ba har sai an yanke hukunci kan babbar tambayar da kundin tsarin mulki ya yi kan ikonsa.
A gobe ne dai kotun kolin za ta yi wannan tambaya, wacce kuma za ta yanke hukunci kan ko kotu za ta iya yi wa hukuncin da kakakin majalisar ya yanke katsalandan.
Majalisa ce kadai ta ke kan gaba a yawan kuri'u a zauren majalisar mai mambobi 200.
Team Pilot ta yi ikirarin goyon bayan 'yan majalisa 30, amma ya zuwa yanzu, shaidun na nuni da cewa 19 ne kawai.
Jam'iyyar ta BJP tana da 72 kuma ciki har da kawaye da kuma Inyamurai, tana tsaye a 97.
Idan har kotu ta yanke hukunci kan karar da Mista Pilot ya shigar, majalisa za ta iya rasa gwamnati ta biyu daga cikin gwamnatoci uku da ta kafa a dazuzzukan da suka biyo bayan zaben 'yan majalisu na shekarar 2018.
A watan Maris, ta rasa gwamnatin Kamal Nath-led a Madhya Pradesh bayan da Jyotiraditya Scindia ta shiga cikin jam'iyyarsa ta BJP tare da 22 daga cikin 'yan majalisarsa.
An kama jami'an 'yan sandan Kenyan bayan harbin mai kan uwa da wabi a Garissa
An kama 'yan sanda biyu a Kenya dangane da wani harbi da aka yi wanda ya yi sanadiyyar mutuwar mutane biyu.
Harbe-harben sun faru ne a kasuwar Soko Ng'ombe da ke gabashin karamar hukumar Garissa a ranar Asabar, yayin zanga-zangar adawa da kama wani mutum da ake zargi da kisan kai.
Mutane biyun da aka bayyana sunayensu da Aden Abdi Madobe da kuma Muhiyadin Adow Shibin.
Rundunar 'yan sandan Kenya ta kaddamar da bincike kan harbe-harben.
Hakan zai hada da "binciken kwakwaf" kan bindigogin jami'an.
Garissa MP Aden Duale ya kira mutuwar "mai tsanani" ya kuma yi Allah wadai da "cin zarafin ƴan sanda" a wata sanarwa da ya wallafa a shafinsa na sada zumunta na Facebook.
Masu yakin neman zabe sun nuna damuwarsu game da siyasa a lokacin wannan annoba.
A cewar kungiyar kare hakkin bil adama ta Amnesty International, jami'an kasar Kenyan sun kashe mutane 21 tun a watan Maris saboda rashin bin matakan kariya daga cutar coronavirus kamar dokar hana fita da kuma saka takunkumi.
A farkon watan nan 'yan sanda a babban birnin kasar Nairobi sun harba hayaki mai sa hawaye tare da kama masu zanga-zanga da dama da ke gudanar da zanga-zangar Saba Saba ta shekara-shekara - zanga-zangar da aka fara shekaru 30 da suka gabata kan kiki-kakar mulkin shugaban kasa Daniel arap Moi.
Masu aiko da rahotanni sun ce taron na wannan shekarar an yi shi ne ba tare da nuna fushi ba kan yadda ƴan sanda suka fatattake su a lokacin da ake tsaka da dokar Covid-19.
Shivraj Singh Chouhan Kan Gwajin Kwayar Cutar Kansa
Babban Ministan Madhya Pradesh Shivraj Singh Chouhan, wanda a ranar Asabar ya tabbatar da cewa ya kamu da cutar COVID-19, ya aika da sako a safiyar Lahadi yana mai cewa yana "cikin koshin lafiya" kuma ya yabawa ma'aikatan da ke gaba-gaba a yakin da ake yi da cutar coronavirus.
Babban Ministan ya kuma maimaita gargadin da ya yi daga jiya, a lokacin da ya bukaci mutane da su bi ka'idoji, kamar bayar da tazara da kuma amfani da takunkumin fuska.
"Ina cikin koshin lafiya, abokaina. Kwazon mayaƙan cutar Koronabirus, waɗanda zaburar da su ya kassara rayuwarsu, abin a yaba ne. Ina yi wa dukkan mayaƙan cutar Koronabirus na jihar albishir", a cewar Mista Chouhan daga Asibitin Chirayu na Bhopal, inda aka shigar da shi jiya.
"Ka nisanci mita biyu, ka rika wanke hannunka akai-akai ka kuma sa takunkumi - wadannan su ne manyan makaman da ya kamata mu kauce wa kamuwa da cutar Koronabirus. Ina kira ga dukkan mutane - ku yi amfani da wadannan makamai domin kanku da kuma masoyanku", in ji shi.
Mista Chouhan ya kara da cewa, "dukkanninku ku yi taka tsan-tsan, ku zauna lafiya, ku kuma samu lafiya, wannan shi ne abin da na ke addu'a ga Allah".
A ranar Asabar Mista Chouhan ya aika da sakon twitter cewa ya kamu da cutar duk da kokarin da ya ke yi na kauce wa kamuwa da ita, ya kuma yi gargadin cewa "karsashi kadan ne kawai ke gayyatar cutar ta Koronabirus".
A sakon tes da ya aike da safiyar yau Mista Chouhan ya ce duk da barazanar kamuwa da cutar "babu bukatar tsoro" sannan ya bukaci wadanda ke nuna alamun kamuwa da cutar da su yiwa kansu gwaji.
"Idan ka kamu da cutar, babu bukatar ka ji tsoro. Kar ka boye alamomin cutar amma ka fadawa likitoci nan da nan, don haka za a iya fara karbar magani. Shan magani a kan kari zai sa ka samu lafiya", in ji shi.
Madhya Pradesh na da kusan mutane 27,000 da suka kamu da cutar COVID-19, inda daga ciki sama da 7,600 ke dauke da cutar kuma 799 ne suka mutu sakamakon kamuwa da cutar.
Indiya ta samu karuwar wadanda suka kamu da cutar COVID-19 a cikin makonnin da suka gabata, inda aka gano sabbin wadanda suka kamu da cutar sama da 45,000 a kowacce rana tun daga ranar 23 ga watan Yuli.
Adadin wadanda aka tabbatar sun kamu da kwayar cutar Koronabirus ya kai dubu 14 cikin hanzari; daga cikin wadannan sama da dubu 4.67 masu dauke da cutar ne kuma sama da 32,000 ne suka mutu sakamakon kamuwa da cutar.
Yawaitar wadanda lamarin ya shafa, wanda ya yi daidai da dagewa da sassauta ka'idojin kulle a wuraren da ba a killace ba na kasar, ya yada Indiya zuwa ta uku a jerin kasashen da lamarin ya fi shafa.
Amurka ce kadai (mutane dubu 41.78) sai kuma Brazil (mutane dubu 23.94 ne suka fi kamuwa da cutar).
Ministan cikin gida na Tunisia ya kira sabon PM kasar, domin kafa gwamnati a cikin wata guda
An nada ministan cikin gida na Tunisia Hichem Mechichi domin kafa gwamnati ta gaba, a cewar ofishin shugaban kasar, a daidai lokacin da ake tsaka da rigingimun siyasa a tsakanin manyan jam'iyyun kasar da ke yankin Arewacin Afrika.
Lauyan dan shekara 46 da haihuwa ya yi nasara a kan Elyes Fakhfakh, wanda ya yi murabus daga mukamin firayi minista a farkon watan nan.
Sai dai Mechichi ba ya daga cikin sunayen da jam'iyyun siyasar da ke mulki suka gabatar wa shugaba Kais Saied.
A sanarwar da ya fitar bayan sanarwar ta ranar Asabar, Mechichi ya ce "zai yi aiki domin kafa gwamnatin da za ta biya bukatun dukkan 'yan Tunisia".
An yabawa kasar Tunisia a matsayin wani labari na gagarumar nasara ga sauyin dimokradiyya bayan boren da kasashen Larabawa suka yi a yankin sakamakon juyin juya halin da ya faru a shekarar 2011.
Sai dai shugabanninta sun kokarta wajen biyan bukatun al'ummar Tunisiya da tuni tattalin arzikin kasar ya yi karanci sakamakon rufe iyakokin kasar da aka yi saboda annobar COVID-19.
Cutar ta hallaka kusan mutane 50 ta kuma kama sama da 1,400 a Tunisia.
Kazalika shi ne ministan cikin gida a gwamnatin da ta shude, Mechichi ya kasance mai baiwa shugaba Saied shawara, kan al'amuran da suka shafi shari'a.
A baya ya taba zama shugaban ma'aikata a ma'aikatar sufuri, ya kuma yi aiki a ma'aikatar kula da harkokin jama'a.
Yanzu yana da wata guda da zai kafa gwamnati, wacce sai ta fuskanci kuri'ar raba-gardamar amincewa da ita sannan zai bukaci cikakken rinjaye domin samun nasara.
Gaza cewa, za a rushe majalisar dokoki kuma za a gudanar da sabon zabe cikin watanni uku.
A zabukan da suka gabata da aka gudanar a watan Oktoba, jam'iyyar Ennahdha ce ke kan gaba, amma ta fadi kasa warwas, daga bisani kuma ta amince ta shiga gwamnatin hadaka.
Murabus din Fakhfakh a ranar 15 ga watan Yuli, bayan kasa da watanni biyar a karagar mulki, ya yi barazanar fadawa cikin wani sabon rudanin siyasa a kasar yayin da take fama da koma bayan tattalin arziki sakamakon barkewar annobar Koronabirus.
Murabus din ya zurfafa rikicin siyasa da Ennahdha kan zargin da ake yi wa Fakhfakh na rikice-rikice na nuna son zuciya.
Dangantaka tsakanin shugaba mai jiran gado dan shekara 43 da Ennahdha ta yi tsami tun bayan zaben 'yan majalisun dokokin da aka yi a watan Oktoba.
Fakhfakh ya sauka daga mukamin sa ne a ranar da jam'iyyar ta shigar da karar rashin amincewa da ita a kansa.
Da farko Ennahdha ta zamo Firayi Minista mai cin gashin kanta, amma ya kasa samun goyon bayan majalisar dokoki, lamarin da ya kai shugaban kasa ga bayyana sunan tsohon Ministan Kudi Fakhfakh a matsayin wanda zai gaje shi.
Da aka fuskanci sa ran gudanar da sabon zabe, daga bisani Ennahdha ta amince ta shiga cikin gwamnatin hadin gwiwa.
Mota ta bi ta kan jama'a, an yi harbi kan mai zanga-zanga a Colorado
Aurora, Colo. (AP) - Wata mota ta bi ta kan taron jama'a kuma an harbi wani mai zanga-zanga a makabartar Denver da ke Aurora a lokacin zanga-zangar adawa da rashin adalaci na launin fata.
Ma'aikatar 'yan sanda ta Aurora ta fada a shafinta na dandalin sada zumunta na Tuwita cewa masu zanga-zangar na tafiya ne a ranar Asabar 225 ga watan Fabarairu a lokacin da wata mota ta bi ta.
'Yan sanda sun ce wani mai zanga-zanga ya harba makami mai linzami, inda ya budewa akalla mutum guda da aka kai shi asibiti cikin halin rai kwakwai-mutu kwakwai.
Hukumomi sun ce an hasko motar kuma suna gudanar da bincike.
Masu zanga-zangar sun kuma fasa tagoginsu a kofar shiga kotun, an kuma soma barin wuta a wani ofishi, a cewar 'yan sanda.
An ayyana gudanar da wani taro ba bisa ka'ida ba, kuma 'yan sanda sun umarci masu zanga-zangar da su bar yankin, in ji hukumomi.
An dade ana zaman dar-dar a zanga-zangar da ake yi a baya-bayan nan kan rashin adalcin launin fata tun lokacin da aka aika jami'an tsaro na tarayya domin su dakile zanga-zanga a Portland da ke Oregon.
'Yan sanda sun ayyana dokar-ta-baci a Seattle a ranar Asabar.
Zanga-zangar da aka yi a ranar 25 ga watan Mayu ta yi sanadiyyar mutuwar George Floyd, wani bakar fata a Minnesota wanda ya mutu bayan da wani jami'i farar fata ya rike shi a kasa tare da dankwafar da shi a wuyansa, ta kuma yi karin haske kan wasu shari'o'i na zaluncin 'yan sanda masu tsanani.
A Colorado, masu zanga-zanga na ta jawo hankali kan mutuwar Iliya McClain, wanda 'yan sanda suka hana shi tafiya kan titin Aurora a watan Agusta na 2019 bayan da wani mai kira 911 ya kai masa rahoton abin da ake zarginsa da aikatawa.
'Yan sanda sun sanya shi a cikin cakuleti, kuma shanun sata sun sarrafa milligram 500 na ketamine, wani abu mai tayar da zaune tsaye, don kwantar masa da hankali.
Ya shiga bugun zuciya, daga baya aka ayyana shi a matsayin wanda ya mutu a kwakwalwa aka kuma tafi da shi neman taimakon rayuwa.
Faman share tafkin Tahoe ya gurgunta sauyin yanayi
Tabkin Tahoe na Kudancin California - Duk da bullar annobar, ko a ranar daya ga watan Fabarairu, har yanzu mutane na ci gaba da taruwa a bakin tekun Paparoma da ke Tahoe.
"Ina son yin zango da kuma tuka keke da kuma yin iyo a tafkin Chadi", a cewar wata yarinya mai suna Dakota.
"Wannan wani abu ne mai kyau da kowa ke son ziyarta", a cewar Emerica Benitas.
Abin da ya sa kasuwancin Matt Meunier da ke raye har yanzu yana ci gaba da karfi, har ma a cikin annoba.
Ya ce yana ganin "tsabta ta kwarai. Tafkin Tahoe shi ne tafki mafi tsabta, mafi ban al'ajabi, ina ganin cewa, a kasar".
Yanzu mummunan labari: Tafkin Tahoe ba shi da tsabta, ba kamar yadda ya bayyana ba, kamar yadda ya yi amfani da shi a lokacin da ya koma nan sama da shekaru biyu da suka gabata.
"Abin da muke lura da shi da yawa ya ragu a kan duwatsun", in ji Meunier.
"Kana samun wannan baƙon algaitar ne a kan duwatsu".
Sauyin yanayi, masana kimiyya sun yi imanin cewa, ya shafi zafin jikin ruwa kuma ta haka ne, za a samu karin haske.
Kuma mutane miliyan 15 ne ke ziyartar tafkin a duk shekara - tare da garejin da suke bari.
Meunier ya ce tafiye-tafiye masu rai da ake yi don tsaftace kasan tafkin an gano tsohuwar shara.
"Kuma idan na fadi tsohuwar shara, ina nufin '60s,'70s", in ji Meunier.
"Gwangwanin giya, gwangwanin soda, mabudin coci daga tsoffin kwanuka".
Masana kimiyya na sa ido kan tsabtar tafkin Tahoe a kowacce shekara ta hanyar sauke farin faifai, sannan suna auna yadda za su iya ganinsa.
UC Davis farfesa Geoff Schladow ya ce "muhimmin abu ne da ke nuni da yadda tafkin ke da koshin lafiya".
A lokacin da aka auna shi a shekarar da ta wuce, tsabtar tafkin ya kai kimanin kafa 80.
Hakan na nufin za ka ga wannan faifan ya kai kafa 80.
Amma, ka yi la'akari da wannan, kimanin shekaru 20 da suka wuce, tsabtar tafkin ya kai kafa 100.
Wannan shine yanayin da masana kimiyya ke ƙoƙarin komawa baya.
Amma suna yaki da tasirin sauyin yanayi, da ci gaba a kewayen tafkin da kuma wani abu da aka kara wa tafkin a shekarun 1960: Wani dan karamin dawa mai mamaya da aka kawo domin ciyar da kifayen.
Abin bai yi aiki ba.
"Da zarar wurin ibadar ya shigo, ba zato ba tsammani babu masu tsabta na halitta a cikin tafkin", in ji Schladow.
Irin wannan kalubale na fuskantar tabkuna da kuma jikin ruwa a duniya.
"Darasin a nan shi ne, idan ba za ka iya yin sa a Tahoe ba, to, wane fata ke nan ga dukkan koguna da tsaunuka, da rafi da tafkunan kasar da ba za su taba samun irin wannan kulawa ba, da irin albarkatun da ake da su?" In ji Schladow.
Meunier ya ce, yana da "fatan alheri" saboda "idan aka samu bullar wannan annobarmu ta azurfa, ina ganin hakan ya nuna cewa yanayi zai dawo ya warkar da kansa idan dai har mun samu sauki daga wannan matsin lamba, wannan matsin lamba na dan adam, daga shi sai ya kyale hakan ta faru, akwai abubuwan da ke faruwa a can yanzu".
Wasu ma'aurata MACED a wurin shakatawa na karen California saboda rashin sanya takunkumi yayin cin abincin rana (VIDEO) - RT USA News
Akwai masifar harbe-harbe sannan kuma akwai cikakkiyar kan mai uwa da wabi.
Wasu ma'aurata a California da ke cin abincin rana tare da ƴaƴansu a wani wurin shakatawa na kare sun fuskanci na biyu, a lokacin da wata mata mai ban haushi ta yi musu feshin barkonon tsohuwa saboda kin sa takunkumi... yayin da suke cin abinci.
Ash O'Brien da maigidansu Jarett Kelley sun ce sun ciro wani abin da za su ci ne a wurin shakatawa na karen Dusty Rhodes da ke San Diego a ranar Alhamis, tare da kwasarsu 'yar wata uku da haihuwa a kafada.
Masoyan biyu sun daga takunkuminsu don su ci abinci, a lokacin da wata "bazawara tsohuwar mata" ta tunkare su, tana kiransu "masu bautar gumaka" don kada su yi masabaha, duk da cewa "ba za ku iya sa takunkumi ku ci abinci ba a lokaci guda".
O'Brien ta fadawa matar cewa ta bar wurin shakatawa ta daina yi mata sharri, a wannan lokacin ne matar ba ta yi wata-wata ba wajen iya mace a al'aurar.
Wani hoton bidiyo da wani bafaranshe ya dauka ya soma ne da kokawar da Kelley ya ke yi na iya kokarinsa daga matar, da kuma samun kashi na mace a fuskarsa saboda matsalolin da yake fuskanta.
Ana jin O'Brien na kuka a bayan kasa yayin da wanda ya kai harin ke tafiya tare da karnukanta.
O'Brien ta yada bidiyon a Facebook ta kuma fadawa ABC 10 cewa tana son ta ga matar "ta tafi gidan yari".
Takunkumin rufe fuska ya zama tilas a duk fadin jihar California, har ma a iska mai kyau.
Wadannan takunkumi za a iya cire su ne kawai a wasu lokutan da aka zaba, ciki har da lokacin cin abinci ko abin sha.
Sai dai babu inda jagororin cutar Koronabirus na jihar suka ce masu bore na iya amfani da makamai marasa matuka wajen tabbatar da wannan manufa tasu.
Hatta a wannan zamani da ake ciki na "masu-abin kunya", wannan har yanzu laifi ne da ke dauke da hukuncin biyan tarar dala 1,000 ko kuma daurin shekara uku a gidan yari a jihar.
Gadar Sarkar Tarayyar Scotland-Ingila ta cika shekara 200 da haihuwa
Wata gada da ta hade Scotland da Ingila ta juya shekara 200 gabanin a yi mata gyaran fuska na £10m.
Gadar Union Chain Bridge ta tsallaka Kogin Tweed daga Fishwick da ke kan iyakokin Scotland zuwa Horncliffe a Northumberland.
A lokacin da aka bude ta a shekarar 1820, ita ce gada mafi tsawo da aka taba yi na dakatar da baƙin ƙarfe a duniya da tsawon kafa 449ft (137m).
Kuma ita ce gadar farko ta ababen hawa irinta a Burtaniya.
Wani jami'in sojin ruwa na Ingilishi Capt Samuel Brown ne ya tsara wannan gada.
Ya yi facaka da kuma samar da kujerun ƙarfe da aka aikata bayan rashin jiragen ruwa na Royal Naval wanda ya karye daga igiyoyi ya shafe shi.
Abokan gadar Union Chain Bridge da kuma Institution of Civil Engineers (Ice) na kasar Scotland sun yi ta nuna alamar tsallakawa ta keke-da-keke.
Robert Hunter, na daga cikin abokan kungiyar, ya na mai cewa: "Hakika wannan daya ne daga cikin gadoji masu tarihi a duniya, kuma abin sha'awa a fannin injiniya.
"Mun shirya bukukuwa da dama domin murnar zagayowar wannan rana, amma abin takaici sai aka dage.
"Duk da haka, gaskiyar cewa ba da daɗewa ba za a fara aiki a kan gyaran £10m shine mafi kyawun ranar haihuwar da za a iya samu kuma zai tabbatar da cewa tsararraki masu zuwa za su iya jin daɗin gadar a duk tsawon lokacin da aka raba ta".
Daraktar kankara a Scotland Hannatu Smith ta bayyana gadar a matsayin "wani bangare na gadon aikin injiniya a yankin Scotland".
Ta ce: "Mun san cewa duniya sananniya ce kuma dama aiki ne da ba da dadewa ba za a fara gyaransa".
Bullar cutar salmonella ta yi ajalin mutane 212 a jihohi 23
Ranar 25 ga watan Yuli (UPI) - Cibiyar kula da yaduwar cututtuka da dakile su na binciken barkewar annobar cutar salmonella da ta yi ajalin mutane 212 a jihohi 23.
A wata sanarwar manema labarai da hukumar ta CDC ta fitar a ranar Juma'a ta ruwaito cewa mutum 87 ne suka kamu da rashin lafiya tun bayan sabuntawarta ta karshe kan bullar cutar ranar Talata.
Hukumar ta ce mutane sun fara nuna alamun kamuwa da cutar da ke da nasaba da nau'in salmonella, wanda zai iya daukar makonni biyu zuwa hudu kafin ya bayyana alamomin cutar, tsakanin 19 ga watan Yuni zuwa 11 ga watan Yuli.
Mutane talatin da daya ne aka kwantar a asibiti tun lokacin da aka soma samun bullar cutar, sai dai ba a samu rahoton wadanda suka jikkata ba.
A cewar hukumar ta CDC, kawo yanzu ba a gano takamaiman tushen nau'in salmonella ba.
Ba ta bayar da wata shawara kan cin abinci ko shan wasu kayan marmari ba, ko kuma masu sayar da kayan marmari da ka iya sayar da gurbataccen kayan marmari.
Oregon ce ta fi yawan wadanda suka kamu da cutar salmonella, inda take da mutum 51 da suka kamu, yayin da Utah ke biye mata baya da mutum 40 da aka bayar da rahoton sun kamu da cutar.
Salmonella wani ciwo ne na kwayoyin cuta, wada ke haddasa cututtuka miliyan 1.35, da asibitoci 26,500, da kuma mutuwar mutane 420 a kowacce shekara, a cewar hukumar ta CDC.
Mafi yawan alamomin kamuwa da cutar salmonella sune gudawa, zazzabi, da kumburin ciki, wanda za a iya farawa tsakanin awanni shida zuwa kwanaki shida bayan bayyanar cutar.
Rashin lafiyar yakan kai kwana hudu zuwa bakwai, kuma yawancin mutane suna warkewa ba tare da an basu magani ba, amma wasu lokuta suna bukatar a basu magani a asibiti.
United, Chelsea a cikin CL; Bournemouth, Watford sun sauka daga EPL
Manchester United da Chelsea sun samu gurbi a gasar zakarun Turai a karawar da suka yi da Leicester a ranar karshe ta gasar firimiya a ranar Lahadi, yayin da Bournemouth da Watford suka yi kunnen doki don kawo karshen zaman dirshan na shekara biyar a saman jirgin.
United ta samu nasara a kan Leicester da ci 2-0 ta hanyar kwallayen da Bruno Fernandes da Jesse Lingard suka zura mata wanda hakan ya baiwa kungiyar Ole Gunnar Solskjaer gurbi na uku a gasar.
Kungiyar Kwallon kafa ta Chelsea ta doke Wolverhampton da ci 2-0 bayan zura kwallo a raga da kuma taimakawa Mason Mount da ya yi, ya kuma kai ga gurbi na hudu kuma na karshe a gasar cin kofin zakarun turai a sama da kungiyar Leicester, wacce ta kasance a mataki na hudu a yawancin kakar wasanni.
Leicester, a maimakon haka, za ta buga gasar Europa tare da Tottenham, wacce ta tashi 1-1 a Crystal Palace don samun gurbi na shida - sama da Wolverhampton a banbancin kwallaye.
Yakin da ake yi na kaucewa gurabe biyu da suka rage na fanareti ya je waya yayin da Aston Villa ta zura kwallo a minti na 84, ana saura minti daya a tashi daga wasan, sannan aka yi kunnen doki 1-1 a West Ham don tsira da rai.
Kyaftin Jack Grealish ne ya ciwa Villa kwallonta abin da ka iya zama wasansa na karshe ga kungiyarsa ta boyhood.
Bournemouth ta yi abin da ya kamata ta yi, ta kuma doke Everton da ci 3-1, amma ta ƙarƙare da maki ɗaya a bayan Villa.
Ita ma Watford ta sake komawa a matsayin kungiya ta gaba-da-karshe bayan da ta yi rashin nasara da ci 3-2 a hannun Arsenal.
Kungiyar Kwallon kafa ta Manchester City ta zartar da kwallaye 100 a fafatawar da ta yi da kungiyar Norwich da ci 5-0, wasan da ke zama na karshe a gasar firimiya ga David Silva bayan shafe shekaru 10 tare da City.
Kevin De Bruyne ya samu kyautar gwarzon dan wasa na 20 da ya taimaka a kakar wasa ta bana, ya kuma zura kwallo har sau biyu.
Liverpool ta kawo karshen kakar wasanninta da ta lashe da ci 3-1 a Newcastle, ta kuma kammala gasar a inda ta ke da maki 99.
Har ila yau, Southampton ta doke Sheffield United da ci 3-1, a inda Danny Ings ya zura kwallonsa ta 2 a kakar wasan bana.
Hakan ya sa ya zama na daya a bayan dan wasan Leicester Jamie Vardy, wanda ya lashe kyautar takalmin zinare a matsayin wanda ya fi cin kwallo a kungiyar.
Tony Blair ya yi alkawarin cewa ba zai taba daina shishigi a siyasar Birtaniya ba duk da matsanancin koma baya da Brexit ke fuskanta
Tony Blair ya sha alwashin cewa ba zai daina sa baki a harkokin siyasar Burtaniya ba, biyo bayan mummunan koma baya da ya shiga a dama da shi a cikin jam'iyyar Labour da kuma yakin neman zaben Brexit.
Mista Blair, wanda ya kwashe sama da shekara goma a ofis, ya fadawa shirin Sophy Ridge na gidan talbijin na Sky News cewa, "ba zai taba" daina fadin albarkacin bakinsa ba a siyasar Birtaniya.
Sai dai wani mai fashin baki kan al'amuran siyasa ya amince da cewa "mutane da yawa da ke kallon wannan na iya tunanin cewa ya kamata in daina magana kan abubuwa".
Sophy Ridge ta fadawa Mista Blair cewa: "A ko da yaushe ina jin cewa ba za ka iya kawar da kanka daga siyasa ba".
"A ko da yaushe kana wallafa rahotanni kan coronavirus ko kuma ka rika tafka muhawara kan Brexit".
"Ni dai ina mamaki idan mutane suna tunanin cewa me ya sa bayan shekara goma da zama PM, har yanzu kana kokarin ka shiga siyasa?"
"Ba lokacin da za a dauki lokaci kafin a fita, ka zagaya filin wasan golf".
Tsohon Firayi Ministan ya yi watsi da hakan, ya kuma yi alkawarin ci gaba da zama a kusa da shi a siyasar Burtaniya muddin zai iya.
Ya ce: "Ba abu ne da nake so in yi ba. Mutane da yawa da ke kallo za su iya tunanin cewa wannan shi ne ainihin abin da ya kamata ya yi, ya kuma daina magana kan abubuwa, amma ni na damu da kasar".
"Muna cikin wani babban lokaci na sauyi a duniya da kuma cibiyar da na gina ayyuka a duniya".
"Na san na yi wani abin da Firayi ministocin da suka gabata ba su yi ba, amma a nan gaba ina hasashen wasu da yawa za su yi kokarin yi".
Tun da fari a hirar da aka yi da shi, Mista Blair ya ce har yanzu Birtaniya da EU za su iya kasa cimma matsaya kan Brexit kafin karshen shekarar nan.
Ya na mai cewa: "Za su iya kasa cimma matsaya. Amma duk da yarjejeniyar da mu ka kulla da kasar za ta munana".
"Ainahin abin da zai zama alheri ga Turai saboda zai ba da damar samun saukin cinikin hauren giwa amma hakan zai matukar hana mu batun ayyuka"
Tsohon shugaban na jam'iyyar Labour ya kuma fadawa gidan talbijin na SKY cewa Burtaniya za ta cigaba da zama tare da COVID-19, ba kawar da ita za a yi ba, nan gaba kadan.
A Lokacin Da Yake Jawabi Kan Kargil Heroes, PM Narendra Modi Ya Ce Pakistan Tana Kaiwa "Backstab" Indiya Hari
Pakistan ta yi kokarin "mara baya" ga Indiya duk da yunkurinta na ci gaba da dangantakar abokantaka, Firayim Minista Narendra Modi ya fada a yau a cikin jinjina ga sojojin da suka yi juyin mulki a ranar 21 ga watan Fabarairu a lokacin yakin Kargil.
A cikin jawabinsa na wata-wata ta radiyo Mann ki Baat, PM Modi ya ce "Pakistan ta gudanar da wannan rashin kasada ne da shirin sinitiri na kama kasar Indiya da kuma karkatar da akalar rikice-rikicen da ta ke fama da su a ciki".
"Pakistan na da audugar kokarin mamaye kasar Indiya da kuma karkatar da hankalinta daga rudanin da ta ke ciki", in ji shi.
"A lokacin, Indiya na kokarin kyautata dangantaka da Pakistan. Amma kamar yadda aka fada, sharri shine yaki da kowa ba tare da dalili ba. Mutane masu irin wannan dabi'a na iya tunanin aikata sharri ne kawai har ga wadanda ke kokarin yi musu kyakkyawan zato. Shi ya sa Pakistan ta mara wa Indiya baya duk da kokarin da Indiya ke yi na kulla dangantaka ta kut da kut", a cewarsa..
Ya kara da cewa, "ka yi tunanin cewa, abokan gaba sun yi yawa a kan duwatsu yayin da dakarunmu suke yaki da su daga kasa. Amma babbar moriya da gaskiyar dakarunmu sun samu nasara a kan duwatsu".
"Ina godiya da karfin gwiwar dakarunmu, Indiya ta nuna matukar karfinta a Kargil", PM Modi ya na mai cewa, yana mai tuna ziyarar da ya kai yankin.
Ana bikin Kargil Diwas ne a kowacce shekara, wanda ke zama ranar da Sojojin Indiya suka sake maimaita duk wasu sakonnin Indiya a Kargil na Ladakh wanda sojojin Pakistan suka mamaye shekaru 21 da suka gabata.
A ranar 26 ga watan Yulin shekarar 1999, rundunar sojin kasar ta sanar da samun nasarar kakkabe "Operation Vijay".
Yakin da aka kwashe kusan wata uku ana gwabzawa a tsaunukan Ladakh ya yi sanadiyyar rasa rayukan sojojin Indiya sama da 500.
Tun da fari a yau, ministan tsaro Rajnath Singh, da karamin ministansa Shripad Naik, da babban hafsan hafsoshin tsaro Janar Bipin Rawat, da babban hafsan hafsoshin soja Janar M Naravane, da babban hafsan hafsoshin sojin sama R K S Bhadauria da kuma babban hafsan sojin ruwa Admiral Karambir Singh su ma sun kai ziyarar ta'aziyya ga Amar Jawan Jyoti a bikin tunawa da yakin kasa.
A shekarun da suka gabata tun daga Kargil, dangantakar Indiya da Pakistan ta yi tsami biyo bayan wasu jerin hare-haren kunar bakin wake da aka kai.
Indiya ta dage kan cewa tattaunawa da kuma ta'addanci ba za su iya tafiya hannun-riga ba kuma Pakistan na bukatar kawar da duk wani sansanin 'yan ta'addan da ke aiki daga kasarta.
Gwyneth Paltrow na son yara su samu kyakkyawar'dabi'a'
Gwyneth Paltrow ta ce tana so ta reni 'ya 'yanta don su samu kyakkyawar dabi'a mai daraja a yayin da ta ke kokarin'ba wai kawai ta ba su abubuwa ba'.
Paltrow yana da 'ya 'ya biyu, Apple (16) da Musa (14), tare da tsohon maigida Chris Martin kuma tana so su kasance da dabi'u masu kyau kuma kada su sa iyayensu su yi suna.
"Shi ya sa na ke ganin yana da matukar muhimmanci... A wajen rainon yaro da ke da dabi'ar aiki kuma dabi'arsa na da alaƙa da naka ko kuma da irin tasu ma'anar ko su wanene, da dai sauransu", ta faɗa wa Rob Lowe a shafinsa na waƙa.
"Gaskiyar al'amarin shine za a iya bude maka kofa, amma idan ka na tunanin duk mutanen da su ka yi kokari kuma hakan bai faru ba".
Ta kuma kara da cewa, "a matsayina na iyaye kana ganin, duk abin da zan iya yi wa wadannan yara shi ne in koya musu abin da ya dace daga abin da ba daidai ba, in kuma koya musu irin aikin da suke yi, na yi matukar kokari ba wai in ba su abubuwa kawai ba".
Paltrow ta kuma dauki matakan da za su ba 'ya 'yanta damar yin rayuwa cikin sirri kamar yadda ya kamata, da kuma tabbatar da cewa sun ci gaba da bibiyar shafukansu na sada zumunta cikin sirri.
"Ba zan bari su zama jama'a a kowacce kafar sada zumunta ko wani abu makamancin haka ba, ina kokarin ganin na kakkabe su daga idon jama'a yadda ya kamata", a cewarta.
"Ka sani, yanzu abin ya banbanta,'dalilin da ya sa yara suke kamar haka,'Zan iya samun tashar YouTube kuwa?'Ni ma haka nake,'A'a, ba za ka iya ba.
Babu makawa".
Imam-Ul-Haq Na Pakistan Ya Musanta Zargin Da Aka Yi Masa Na Fuskantar Barazana Bayan Garkuwa Da Shi
Pakistan da Ingila za su fafata da juna a Gwaje-Gwaje guda uku da kuma T20Is masu yawa.
Wani baturen kasar Pakistan Imam-ul-Haq da likitan kungiyar ya ayyana cewa ya dace ya bat shi bayan da likitan kungiyar ya cireshi a hannunsa na hagu a lokacin da ya ke fafatawa a wasan share fage na cikin 'yan wasa a Derby.
"Baturen dan damben ya shiga cikin zaman dirshan kafin soma wasan a rana ta biyu", a sanarwar da Hukumar Kwallon Kafar Pakistan (PCB) ta fitar a wata sanarwa.
PCB Whites'Imam ya daga hannunsa na hagu a lokacin da yake fafatawa da PCB Greens'Naseem Shah a ranar daya ga watan Fabarairu.
An tilastawa Imam yin ritaya cikin rauni a yammacin ranar Juma'a bayan da kwallo ta buge shi a hannun hagu daga Shah, amma ya samu damar yin zaman dirshan na gargadi da safe kuma zai ci gaba da zaman dirshan a rana ta uku.
"The Persians" Review: Hotunan Aeschylus na ban mamaki na Defeat
Babu wani aiki da yawa, kawai har ma da karuwa, a cikin "Farisa".
Mutane kawai niƙa game da, magana (admittedly rather intensely) game da abubuwan da suka faru (admittedly of the tragic kind) da suka faru nesa ba kusa.
Amma duk da haka wannan National Theater of Greece na samar da sautin taurari marasa karfi da kuma fushi.
A kololuwarta, wasan kwaikwayon yana bugawa ne kamar ragargazar plexus na hasken rana, yana kawar da numfashinka - tasirin yana dan raguwa ne kawai ta hanyar kallon layi.
Da farko an samar da shi a 472 B.C., "Farisawa" na Aeschylus ana kallonsa a matsayin mafi tsufa da ya tsira a wasan Girka.
An watsa wannan salo na Dimitris Lignadis kai tsaye a ranar Asabar daga gidan sinima na zamanin da na Epidaurus; a halin gidan sinima, babu wani rikodi da ya wanzu a yanar gizo.
Wurin ya samo asali ne daga wani bangare na birni mai suna Asclepeion (cibiyar warkarwa) saboda Girkawa sun dauki daidaito tsakanin jiki da rai da muhimmanci ga koshin lafiya.
Bari dukanmu mu yi wasici da wannan falsafar.
Wasan kwaikwayon na kulla alaka ne da bayan Salamis, yakin da sojojin ruwa suka yi wanda Girkawa masu yawa suka yi nasara a kan sojojin Farisa masu yawa shekaru 2,500 da suka wuce.
A daidai lokacin da abubuwan da ke wakana a gabanmu ke rufewa, ya yi kasa-kasa a tsaye don kusan shiga sahun masu sauraro kai-tsaye wajen kallon (subtitled) 'yan wasan kwaikwayo na rayuwa duk dai a kasar Girka yayin da suke yin wani wasan kwaikwayo na shekara dubu.
Shi kansa Aeschylus ya gwabza a Salamis, amma wasansa ya karkato: Wannan tsohon soja na bangaren da ya yi nasara ya kafa labarinsa a tsakanin wadanda suka sha kashi, yana mai zura idon basira kan abokan gabansa na baya-bayan nan da ke cikin tashin hankali".
Wata kirar mutanen Farisa, sanye da doguwar riga mai launin tankiya da kuma farar riga mai dauke da button-butumi, ta bude hanyoyin.
Suna cikin babban birninsu cikin alhini suna jiran labarin sarkinsu Xerxes, wanda ya yi tattaki zuwa Athens tare da shi.
Shigar da mahaifiyar gwauruwa Xerxes, Sarauniya Atossa (Lydia Koniordou), a maimakon babbar bakar fata wacce ta ke bayyana cewa ita ta ke sa ta, a maimakon baya; ita 'yar adam ce a cikin wani abin sha'awa na masana'anta, mai rauni da kuma dabara.
Koniordou, wacce ta ke cikin fitattun ƴan wasan kwaikwayo na Girka, ta san irin rawar da ta ke takawa a ciki - ta bayar da umarni kuma ta fito a wani shirin National Theater of Greece mai suna "The Persians" wanda ya fito a Cibiyar Birnin New York a shekarar 2006 - kuma ta ankara da cewa za a ci gaba da shari'ar ba tare da kamar an yi galaba a kanta ba.
A mafi yawancin lokuta, tana tsaye ne a tsakiyar matakin madauwari, ba tare da la'akari da fushi mai hayayyafa da tashin hankali ba yayin da aka bayyana ire-iren bala'in da ya faru da sojojin gida.
An tabbatar da fargabar da kowa ke ji, a bayanan da ke harzuka wani manzo (Argyris Pandazaras) da ya dawo daga rakiyar gaba.
A wani yanayi mai cike da ban sha'awa, ya bayar da labarin yakin, inda ya karrama kansa cikin zullumi yayin da 'yan kungiyar kiristoci ke rawa a kusa da shi da kuma Giorgos Poulios mai kama da bugun tazara, abin da lallai ya kasance matakin kuruciya.
Daga baya kuma sai mijin Atossa da ya mutu (Nikos Karathanos), ya taho da su daga karkashin kasa, da Xerxes (Argyris Xafis), wadanda suka yadda suka tsere da rai daga hannun wadanda suka yi garkuwa da su.
Guda daga cikin kirtani a kan jinin alamarsa ta tunkaho (kudaden da Eva Nathena ta ke fitarwa a koda yaushe na taimakawa wajen bayar da labari).
Haruffan na jimamin rasa rayukan da aka yi da kuma barnar da aka yi tare, a wani mataki na zaman makoki na al'umma.
Quite a bit na gargajiya gidan wasan kwaikwayo da muka gani a Amurka ƙoƙarin yin shi mafi m, a wata hanya ko wata.
A wasu lokutan a kan yi hakan ne da karatun layi na zahiri, a kokarin da a ke yi na ganin rubutun bai kai na kasashen waje ba, ya fi saukin narkewa.
Amma Lignadis da damarsa sun rungumi ragwanci sosai, wanda hakan na iya dan tilasta wa kunnuwa na zamani, amma ya nuna irin karfin ikon da rubutu ke da shi na rudani.
Duk da cewa a zahiri ba sa rera waka, alal misali, jagororin 'yan wasan hudu da gaske suna sadar da arias, suna samun karfin tursasawa da suke jin cewa ba sa cikin duniya.
Amma, ba za mu manta da cewa, wasan kwaikwayo ya kafu ne a kan motsin zuciyar da dukkanninsu mutane ne.
Sunday tare da Oliver Spencer: "Ba zan yi ado ba, ranar lahadi don sakarci ne"
Ta yaya ranar Lahadi za ta soma?
Da ni ka tuntsire da tuntsire da faduwa kan karen da ke kan hanyata ta sa matata ta zama kofin shayi.
Idan na yi sa'a, za mu tsere Landan zuwa gidanmu da ke bakin gabar teku a tsibirin Wight.
Mu biyun za mu zauna tare mu na kallon ruwa a cikin shirme.
Yana sauti serene...
Shi ne, har zuwa karfe 8am a lokacin da yaranmu biyu ko uku suka yi bankwana da kofa suna bukatar karin kumallo.
Kwayoyin cuta ne da kwai a gare su, da leda da kuma naman kaza a gare mu; sannan idan yanayi ya yi kyau, sai mu kori yaran.
Za mu yi iyo, filafilai ko kuma mu yi tafiya a kusa da kyakkyawan Quarr Abbey, wanda ya yi kama da wani abu madaidaici daga Game of Thrones.
Da kuma a lokacin dokar kulle?
A makonni biyu na farko ina cikin jimami, ban yarda cewa an rufe min kasuwancina ba.
Na janye hankalina ta wajen lura da rayuwa ko kuma mutuwar sabon lambunana da aka dasa.
In ba haka ba, na yi gwaji a dakin dafa abinci: Tsananin dandano eel da shiitake broth da kuma cin hancin cream guda biyu sun kasance abubuwan da na sa a gaba.
Ta yaya za ka kasance ba tare da iska ba?
Ba zan yi ado ba, ranar lahadi na yin kwalliya ne da kwalaben dinki na alfarma da kuma T-shirt mai farin jini.
Bayan cin abincin rana na dabbar kaza, zan yi waiwaye tare da takardunku a kan kujera a cikin lambu.
Na yi kokari kada in sha: Yana taimakawa wajen share kaina kafin ranar Litinin ta zo kira.
A ranar Lahadi hakan ya tsaya cik?
Bayan shafe tsawon daren Asabar a bikin cikar Mataimakina shekara 40 da haihuwa a New York, da tsakar dare sai matata mai dauke da juna biyu ta yanke shawarar cewa za mu fi samun sauki.
Ta kuduri aniyar jin dadin kanta, tana mai fadawa mutane cewa ita ce ta uku ballantana ta kai ga gaci.
Mun fice daga jam'iyyar sai ta mike tsaye ta shiga yajin aiki.
Da kuma daren ranar Lahadi?
Da misalin karfe 7 na yamma mun yi cincirindo da motar kuma mun shiga cikin motar zuwa Portsmouth.
A drive up da A3 kuma mun dawo London ga mako: Yara a gado, Ina tafiya da kare da kuma samun kwano na yumbu.
Ina da kyau in bar tsibirin Wight in koma cikin birni, na san idan ban yi haka ba, ba zan iya samun gida a wurin ba ko kadan.
Masu ba da lamuni na yanar gizo sun yi gargadin cewa tsarin rancen kudi na SME na iya rasa alamar
Bangaren kananan kamfanoni da a wasu lokutan manyan bankuna ke gudanar da harkokinsu a karkashinsa, ya dada juya akalarsa ga masu bayar da lamuni ta yanar gizo domin biyan bukatun kudade.
Sai dai Mista Callaghan ya ce masu bayar da lamuni ta yanar gizo ba su da wani amfani idan aka kwatanta da manyan bankunan saboda ba su samu damar yin amfani da wannan dan karamin farashi ba, ya kuma yi gargadin cewa sakamakon haka tsarin bayar da lamuni na SME ba ya samun karbuwa.
"Ina ganin watakila an rasa inda duk mutanen da suka kira mu, suke kira a zatonsu za su iya samun kudade masu arha maimakon gwamnati ta goyi bayan kashi 50 cikin 100 na bashin", in ji shi.
"Don haka suke kira kuma su yi matukar bacin rai saboda an fitar da tsammani cewa za a samu rangwamen farashi kuma muna duba kudin da muke kashewa na kudade wanda hakan bai canza komai ba".
Mista Callaghan ya kara da cewa idan masu kudi suka samu damar samun kudade masu rahusa suka kuma zartar da hakan ga kananan 'yan kasuwa tsarin ba zai zama "babu kwalliya ba".
"An dan kama 22 manyan bankunan sun samu damar yin amfani da kudade masu dan karen tsada amma sun fi fuskantar hadari saboda haka ba za su fita su bayar da bashin yadda ya kamata ba, ba za su iya samun damar yin amfani da bayanan ba kuma ba za su ji dadi ba sai kana da dukiya", in ji shi. "Har sai mun samu damar samun wannan kudade masu rahusa ina ganin akwai karbuwa a kasuwa kan yadda tsarin zai kasance".
Melbourne-Moula ita ma ta shiga cikin shirin kuma babban jami'i Aris Allegos ya ce amfanin garantin kashi 50 cikin 100, da ke cikin tsarin gwamnati, kamata ya yi a zartar da shi ga kananan kamfanoni amma masu hannu da shuni daban-daban ne ke tafiyar da hakan ta hanyoyi daban-daban.
"Na fahimci cewa za a iya samun wasu da ba sa wucewa ta wannan tsarin kudin", in ji shi.
"Hakan na iya zama wani aiki na yadda aka tsara kashe kudadensu kuma hakan na iya zama wani aiki kuma na irin kudaden da suke kashewa da kuma yadda za su tantance hadarin da ke cikin wadannan nau'ukan".
Mista Allegos ba zai bayar da cikakken bayani game da adadin basussukan da Moula ya bayar a karkashin tsarin ba, amma ya ce tsarin da aka farfado da shi "wata babbar fahimta ce kan abin da ake bukata a sauya" don bayar da karin sassauci ga masu bayar da bashi da kuma masu hannu da shuni.
Sai dai ya ce babban abin da ya fi damunsa shi ne "tattalin arziki mai saurin tafiya biyu" da ke aiki da kuma tasirin da hakan zai yi ga kananan kamfanoni.
"Babban batun da Moula zai fuskanta da kuma masu bayar da bashi game da kananan sana'o'i shi ne, karin magana da kuma yadda za a gudanar da shi a cikin wannan maudu'i", in ji shi.
"Duk lokacin da muke magana game da bukatar ba mu koma matakan riga kafi ba kodayake ana samun karuwar ci gaba".
ASX-wacce ta lissafa Prospa mai bayar da lamuni ta yanar gizo ba za ta yi cikakken bayani kan adadin basussukan da ta bayar a karkashin tsarin ba kamar yadda ta ce bayanan na da nasaba da kasuwanci sai dai shugaban hukumar Greg Moshal ya ce karin wa'adin aikin da gwamnati ta yi na maraba ne da shi.
"Muna goyon bayan duk wani haɓaka ga tsarin da zai ba ƙananan kamfanoni damar samun dama ga samfurori masu yawa na kudade waɗanda suka cika bukatun su, ciki har da samfurori masu sassaucin ra'ayi na tsabar kudi a kan gajeren sharuddan", in ji shi.
Flat, Ilimi Kyauta Ga Mai Sayar Da Kwai Paras Raykar Wadanda Aka Yi Garkuwa Da Su Sama Da Rs. 100 Bribe
An yi zargin cewa katon Paras Raykar dauke da kwai ne ya kifar da shi a ranar Alhamis daga hannun jami'an 'yan sandan farar hula a Indore.
Kwanaki biyu bayan labarin wani katon mai sayar da kwai dan shekara 13 da jami'an kwastam suka kifar da shi a shafukan sada zumunta, yaron mai suna Indore-based ya samu tallafi mai yawa daga mutane a fadin kasar, wanda hakan ya taimaka musu wajen farfadowa daga asarar da suka tafka, suka kuma samu nasarar fara kasuwancinsu kuma.
Iyalan yaron sun kuma yi ikirarin cewa 'yan siyasa ciki har da shugaban majalisa Rahul Gandhi da kuma babban ministan birnin Delhi Arvind Kejriwal sun kai musu dauki tare da ba su goyon baya.
Iyalan yaron sun kuma samu leburori tare da bayar da damar kula da kudaden karatun yaran da ke cikin iyali.
An yi zargin cewa katon Paras Raykar da ke dauke da kwai ya kifar da shi ne a ranar Alhamis daga hannun jami'an fararen hula a Indore, inda gwamnati ta aiwatar da "tsatstsauran hukunci" saboda dagewar da aka yi na bude shaguna sanadiyyar annobar cutar Korona.
A wani faifan bidiyo da yaron ya yi zargin cewa jami'an sun gargade shi da safe da ya cire katinsa ko kuma ya biya Rs 100 kamar yadda cin hanci ya yi ta yawo a shafukan sada zumunta.
Da ya ki amincewa, sai jami'an suka taho da katon nasa, suka fasa masa duka, kamar yadda yaron ya yi zargi.
Yaron ya kuma yi ikirarin cewa sayar da shi da ake yi a kullum ya ragu saboda annobar Koronabirus da kuma asarar hannayen jarin da ya yi, za su kara masa nauyin kudi, a bidiyon.
Tun a ranar Alhamis ne iyalan yaron suka cika da alhini tare da samun tallafi daga mutane a fadin kasar, yawancinsu suna bayar da taimako ne ta fuskar tsabar kudi da alheri.
Iyalin sun kuma samu taimako daga wuraren da suke.
Yayin da tsohon babban minista Digvijaya Singh ya ba da tallafin kudi da taimako don shigar da yaran a kwalejin, BJP MLA daga Indore, Ramesh Mendola, ya ba da tabbacin samar da wani gida a karkashin Pradhan Mantri Awas Yojana ga yaron.
Kungiyar 'yan jarida ta Indore Press Club ita ma ta bayar da kudin hijirar da kuma kudin ga yaron.
Ofishin shugaban majalisa Rahul Gandhi da kuma babban ministan birnin Delhi Arvind Kejriwal suma sun bada tasu gudummuwar.
Mun cika da mamakin irin tallafin da ake samu daga mutane a fadin kasar.
(Biyafara MLA) Ramesh Mendola ya tabbatar da cewa wani lebur a karkashin Pradhan Mantri Awas Yojana.
Ya kuma samar da wani sake zagayowar kuma Rs 2,500.
Digvijaya Singh ya bayar da Rs 10,000 da kuma tabbacin da zai sa ido kan ilimin yaran biyu.
Ofishin Rahul Gandhi shi ma ya yi kira tare da ba shi goyon baya.
Wata mata daga Delhi Babban Minista Arvind Kejriwal ta yi kira kuma ta ba da taimako.
"Jyothiraditya Scindia ita ma ta ba da tallafi", in ji kakana Paras.
Angola: An Taimakawa Asibitin Pedalé Ga Ma'aikatar Kiwon Lafiya
Shugaban kasar Jamhuriyar Nijer, João Lourenço, ya nunar da cewa a wannan Jumma'a za a mayar da aikin kula da asibitin Pedro Maria Tonha Pedalé, da ke karkashin gine-gine a birnin Luanda, zuwa ma'aikatar lafiya ta kasar.
A cikin bayanin da ya yi, ofishin yada labarai na shugaban kasar Jamhuriyar Nijer ya sanar da cewa, matakin na da nufin karawa gwamnatin kasar ka'idar gine-gine da fadada cibiyar sadarwar asibitocin jama'a domin tabbatar da samun kyakkyawar kulawa ta fuskar kiwon lafiya da magunguna ga jama'a.
"A cikin wannan takamaiman lamarin, ra'ayin shine a samarwa da 'yan Angolan wani asibitin bincike, wanda aka banbance shi kuma aka tanade shi da fasahar zamani da kuma daidai-wa-daida wajen ganewar asali da kuma lura da cututtuka masu wuyar sha'ani", a cewar takardar.
Yana mai jaddada cewa, shawarar shugaban kasar Angolan ta kuma yi la'akari da alkiblar ci gaban kasar, wadda ta motsa "babbar bukata" ga ayyukan kiwon lafiya masu inganci a fannoni daban daban.
Wannan bukatar, bayanin kula ya ci gaba, ya ba da hujjar hada asibitin na musamman don lura da cututtuka masu rikitarwa, koyarwa da bincike, abubuwan da suka danganci ilimin lissafi da likitancin jarirai, wuraren da dabarunsu da gudanarwa suka cancanci zama a karkashin alhakin Ma'aikatar Lafiya.
"Sunday Morning" Matinee: Bikin Rodgers & Hart
Shekarar 2020 ta zamo somin tabi na bajintar Broadway na hadin gwiwar kwararrun 'yan wasa na farko da daya daga cikin shahararrun 'yan wasan kwaikwayo, Richard Rodgers da Lorenz Hart.
Don karrama wakokin da suka yi na son-kai, taurarin Broadway Jelani Alladin ("Frozen", "Hercules") da Christiani Pitts ("King Kong", "A Bronx Tale"), tare da dan rawa Richard Riaz Yoder ("Hello, Dolly!", "Shuffle Along"), sun gabatar da wani take na zamani a kan mizanin Rodgers & Hart "The Lady Is a Tramp", wanda aka rubuta musamman ga "Sunday Morning" masu sauraro.
Music shugabanci da kuma shirye-shirye da drummer Bryan Carter, wanda ya yi tare da taimaka Russell Hall.
Sama Da Ma'aikata 30 Ne Suka Yi Gwajin Cutar Coronavirus A Reshen Bankin Single A Tamil Nadu
Akalla ma'aikata 38 na babban reshen bankin kasa da ke Tiruchirappalli, Tamil Nadu ne suka kamu da cutar Koronabirus, kamar yadda jami'ai daga bankin da kuma hukumar kula da fararen hula na yankin suka bayyana.
A cewar jami'an, an kuma shawarci abokan huldar da suka ziyarci bankin da su bayyana da son ransu domin yin gwajin cutar coronavirus.
Tun da farko, wani babban jami'in reshen da ke fama da wasu rikita-rikita, ya mutu sakamakon kamuwa da cutar COVID-19.
Alkaluman wadanda suka kamu da cutar sun fito karara ne bayan da aka gudanar da binciken kwakwaf a sansanin likitocin da ke bankin kwanan nan, in ji jami'an.
Manyan jami'an bankin sun ce an kammala aikin kawar da cutar kuma bankin na iya ci gaba da gudanar da ayyukansa daga gobe.
Jami'an kiwon lafiya na Kamfanin na tuntubar abokan huldar da suka ziyarci bankin.
Tamil Nadu, ita ce ke da mafi yawan wadanda suka kamu da cutar a kasar bayan Maharashtra, ta ba da rahoton cewa gaba daya mutane 2,06,737 ne suka kamu da kwayar cutar a ranar Asabar.
Kanye West ya bayar da hakuri ga jama'a ga matar Kim Kardashian bayan sauye-sauyen aure
Kanye West ta nemi gafarar uwargida Kim Kardashian saboda fita bainar jama'a da ta yi da "wani al'amari na sirri".
Rapper ta bayyana hakan ne a yayin wani taron da aka yi a South Carolina cewa ma'auratan sun yi la'akari da zubar da cikin da ya yi musu na farko.
Bayan wani mako mai cike da rudani da ya yi wasu jerin ikirari kan matarsa da iyalinta, yanzu West ta aika da sakon neman gafara.
West ta kuma bayar da rahoton cewa ta kai ziyarar gani da ido asibiti awanni bayan da Justin Bieber ya ziyarce shi a fadarsa da ke Wyoming.
Ya ce: "Ina son in nemi gafarar matata Kim saboda fita bainar jama'a da ta yi da wani abu da ya zama sirri.
Ban rufe ta ba kamar yadda ta rufe ni.
"Ga Kim ina so in ce na san na bata maka rai. Don Allah ka gafarce ni. Na gode da ka kasance a wurina a koda yaushe".
Sakonnin da West ya yi na kura-kuren da suka hada da ikirarin da ya yi cewa matarsa ta yi kokarin sa likitoci su kulle shi kuma ya yi wasu jerin zarge-zarge kan uwargidansa Kris Jenner.
Ya kuma ce ya yi kokarin kashe aurensa da Kardashian West wacce ya aura a shekarar 2014.
A yayin da ake cikin fargabar halin da mijinta ke ciki, Kardashian West, mahaifiyar 'ya 'yan West su hudu, ta bayar da sanarwa mai tsayi tana mai cewa ita da iyalinta ba su da "karfi" da za su shiga tsakani, ta kuma tunatar da magoya bayansa cewa yana da matsalar nuna wariyar launin fata.
Ta ce: "Mutum ne mai amana amma mai rikitarwa wanda a saman matsin lamba na kasancewarsa mai zane kuma bakar fata, wanda ya fuskanci rashin mahaifiyarsa mai zafi, kuma ya kan yi fama da matsin lamba da kadaici da ya ke fama da shi sakamakon bi-ta-da-kullin da ya ke yi".
Ta kuma kara da cewa ba ta tattauna halin da yake ciki ba a da, saboda "tana da matukar kariya ga 'ya 'yanmu da kuma damar da Kanye yake da ita ta tsare kansa idan ya zo ga lafiyarsa".
Ta kuma kara da cewa: "Amma a yau, sai na ji kamar in yi tsokaci a kai saboda tababa da kuma rashin fahimta game da lafiyar kwakwalwa".
West ya yi ikirarin cewa ya zubar da cikin ne a yayin wani taron da aka yi a ranar 19 ga watan Yuli.
Yawan wadanda suka kamu da cutar Koronabirus a Isra'ila ya kai 60,000 yayin da wadanda suka kamu da cutar suka tsallake
Rahotanni daga birnin Jerusalem (Reuters) - Yawan mutanen da za a yiwa gwajin cutar Koronabirus a Isra'ila ya kai 60,000 a ranar Asabar yayin da gwamnati ke fama da shawo kan sake kunnowar cutar a yayin da ake tsaka da fama da cutar.
Alkaluma na baya-bayan nan a kowacce rana sun nuna sabbin kamuwa da cutar 1,770, wanda ya kawo adadin wadanda suka kamu da cutar zuwa 60,496, kamar yadda ma'aikatar lafiyar kasar ta ruwaito.
Da yawan al'umma miliyan tara, Isra'ila ta ba da rahoton adadin mutane 455 da suka mutu sakamakon annobar.
Isra'ila na daya daga cikin kasashe na farko da suka sanya dokar ta baci a kasar kuma da farko an samu nasara wajen dakile barkewar cutar.
A kowacce rana yawan wadanda suka kamu da cutar da yawansu ya kai ɗari ya ragu zuwa ƙarancin lambobi biyu.
Cikin damuwa da matsin tattalin arziki, gwamnati ta sassauta waɗannan takunkumin - cikin sauri, wasu jami'ai tun da fari sun yarda - kuma an sake yin kira ga yawan kamuwa da cutar.
Sabili da rufe fannoni daban daban na tattalin arziki, ya zurfafa yin kwaskwarima ga jama'a, lamarin da ya haddasa zanga zangar yau da kullum.
Dominic Raab: Gwamnati ba za ta iya neman gafara kan matakin da Spain ta dauka na keta mata haddi ba
Dominic Raab ya kare matakin da gwamnatin kasar ta dauka na sake tsaurara matakan tsuke bakin aljihu a kan kasar ta Spain a takaice.
Ministocin sun sanar a ranar Asabar cewa masu rike da madafun ikon da ba su dawo daga Spain da tsibiranta ba da tsakar dare, za a tilasta musu killace kansu na tsawon kwanaki 14.
Kasar ta kasance cikin jerin kasashe masu "tafiye-tafiye" da ake zaton suna da hadari da za su ziyarce ta kan titin Downing, sai dai karuwar wadanda suka kamu da cutar Koronabirus a baya-bayan nan ya janyo fargabar sake barkewar cutar a karo na biyu.
A ranar Lahadi, Sakataren Harkokin Waje ya kare sake kakaba takunkumin kwata-kwata a matsayin "martani na ainihi" ga wani abin damuwa na yawaitar kamuwa da cutar da aka bayar da rahoto a yankin.
Ya ce sai da aka tantance lamarin a jiya da rana "kuma mun dauki matakin cikin hanzari kamar yadda za mu iya".
"Ba za mu iya neman gafarar yin hakan ba", ya kara da cewa.
"Dole ne mu iya ɗaukar mataki cikin hanzari, na yanke hukunci, musamman dangane da wuraren da aka killace, ko kuma duniya baki ɗaya dangane da Spain ko kuma wata ƙasa, inda muka ga dole ne mu ɗauki mataki.
"Idan ba haka ba, za mu yi kasadar sake kamuwa da cutar a Birtaniya, da yiwuwar sake barkewar cutar a karo na biyu a nan sannan kuma a sake samun bullar cutar".
An tilastawa sakataren sufuri cikin masu rike da madafun iko a Spain keta haddi
An yanke wannan hukunci ne bayan da kasar Spain ta samu sabbin wadanda suka kamu da cutar Covid-19 sama da 900 a kowacce rana har na tsawon kwanaki biyu da ke gudana.
Sakataren harkokin wajen ya amince cewa yawancin masu yawon bude idanu ba a barsu a baya ba wajen soke su ko kuma canza tsare-tsaren su.
"Na fahimci cewa wannan ruɗani ne ga waɗanda ke faruwa a Spain ko kuma an yi la'akari da cewa za su je amma dole ne mu iya ɗaukar mataki cikin hanzari, na yanke hukunci don kare Burtaniya", in ji shi.
"Mun samu irin wannan ci gaba wajen samun raguwar cutar da kuma hana cutar sake bullowa a kasar Birtaniya".
Fasinjoji sun iso filin jirgin saman Gatwick a safiyar ranar Lahadi bayan sanarwar da hukumar kula da zirga-zirgan jirage ta kasa (PA) ta fitar a ranar Asabar
Sakataren Kiwon Lafiya Jonathan Ashworth ya yi Allah wadai da yadda gwamnatin kasar ta ke "nuna halin ko in kula" kan yadda matakin ke gudana.
Ya ce matakin da fadar Downing Street ta dauka ba zato ba tsammani ya jefa masu rike da madafun iko cikin "tashin hankali da tashin hankali".
'Yar jam'iyyar Labour MP ta fadawa Sophy Ridge cewa: "Na fahimci dalilin da ya sa suka yanke wannan shawarar amma, yadda aka yanke wannan shawarar a cikin awanni 24 da suka gabata shine a zahiri shambolic ne.
"Akwai masu rike da mukamai a Spain a lokacin cikin rikici da damuwa, akwai mutanen da ke gab da tafiya hutu zuwa Spain da kuma tsibiran kamar Tenerife wadanda suka rikide, kuma ba su sani ba ko ma'aikatansu za su ba su damar daukar hutun makonni biyu.
"Gwamnati dai tana cewa ne,'muna fatan ma'aikata su hada kai.'"
"Hanyar da aka bi wajen yanke wannan hukunci a cikin awanni 24 da suka gabata, a gaskiya abin kunya ne".
Me kasar Spain da ke cikin jerin wadanda aka kebe ke nufi ga masu rike da madafun iko?
Ya bukaci ministocin da su bayar da "Karin haske" kan ko wadanda aka ce su killace za su samu tallafin kudi idan ma'aikatansu sun ki biyan su a lokacin da aka kebe musu.
Ya kuma kara da cewa, ana kuma bukatar bayanai a bayyane "ga wadannan masu rike da madafun ikon da a halin yanzu suke kasar Spain wadanda suka ajiye aikinsu yadda ya kamata duk shekara domin hutun iyalinsu wadanda suka rikide suka koma cikin wahala".
"Yadda aka yi magana kan wannan mataki babu makawa yana haifar da damuwa", yana mai jaddada cewa.
Mista Raab ya ce babu wani ma'aikaci da ke bin wannan sabuwar ka'ida da ya kamata ma'aikata su zartar da hukunci a kai, ciki har da ta hanyar sa shi biyan marasa lafiya albashi.
Ya ce: "Muna sauya dokokin ne - an sauya dokar ne dangane da masu rike da mukamai da kuma matafiya - kuma ba shakka muna sa ran ma'aikata za su nunawa ma'aikatan da za su killace kan su saboda dokar sassaucin da suke bukata".
"Idan wani na bin doka dangane da killacewa da kuma killace kansu yadda ya kamata, ba za su iya yanke hukunci a kan su ba".
QB Herbert na daga cikin daftari 4 da Chargers ya sanya wa hannu
Costa MESA, Calif (AP) - Kungiyar Los Angeles Chargers sun rattaba hannu a kan daftarin wasanninsu guda hudu, ciki har da Justin Herbert na kwata-kwata, kuma sun amince da sharuddan da sauran 'ya 'yan kungiyar biyu na ajin daftarin aikinsu.
Masu Cajin sun samu damar yin kwangilarsu ne da ajin daftarin aikinsu a ranar Asabar a lokacin da suka kai rahoto sansanin horas da likitocin da kuma kayan aiki.
Tare da Herbert, wanda aka zaba tare da wanda ya zo na shida gaba daya, kungiyar ta sanar da alamun masu karbar bakunci Joe Reed (zagaye na biyar) da KJ Hill (zagaye na bakwai) tare da Alohi Gilman mai tsaron gida na zagaye na shida.
Sun amince da sharuddan da mai tsaron gida na zagaye na farko Kenneth Murray Jr. da kuma dan wasan baya Joshua Kelley, wadanda aka zaba a zagaye na hudu.
Herbert ya soma buga wasanni 42 a Oregon, inda ya tattara tarihin cin kwallaye 29-13 tare da wucewar yadudduka 10,541 da kuma tazarar kwallo 108 baki daya.
Ya jagoranci gasar tseren motoci na Ducks zuwa gasar tseren motoci na Pac-12 a kakar wasan da ta wuce, inda ya jefa kwallaye 32 da bugun tazara da kuma tazara shida a wasanni 14.
Ya kama aikinsa ne da nasara a kan Wisconsin a gasar Rose Bowl, inda ya yi gudun yada kanin wani har sau uku, aka kuma kira shi da sunan MVP mai cike da hadari.
Herbert zai fafata da tsohon soja Tyrod Taylor domin fara aiki.
Masu Caji za su samu wani sabon koma baya bayan da Philip Rivers ya tashi ta hanyar kyauta bayan kakar wasanni 14 a matsayin mai farawa.
Murray shi ne na 23 a gaba daya bayan da Los Angeles ta yi ciniki da New England ta koma zagaye na farko.
Ya kasance dan rukuni na uku Associated Press All-America selection a kakar wasan da ta wuce bayan ya jagoranci Sooners tare da 102 tackles, ciki har da 69 solo.
Kanye West ya ce zai iya doke Joe Biden "daga rubuta zunubai" - RT USA News
Sabo da sama wa iyalinsa datti a shafinsa na dandalin sada zumunta na Tuwita, rap enigma Kanye West ya sake numfasa rayuwarsa ta son rai a matsayinsa na dan takarar shugaban kasa na jam'iyyar masu ra'ayin rikau, yana mai ikirarin cewa, zai iya doke Joe Biden a kan kuri'un da ya samu na marubuta kadai.
Kwanaki kadan bayan sanar da sabon kundin wakoki da kuma bayyana cewa yana kokarin sakin matar Kim Kardashian har na tsawon shekaru biyu, Kanye West ya sake mayar da hankalinsa ga yakin neman zabensa na shekarar 2020 a ranar Asabar, a cikin sanarwar da ya fitar mai taken "Zan Iya BEAT BIDEN OFF OF WRITE INS".
Idan har kasashen Yamma suna da matukar muhimmanci game da takarar shugabancin kasar, kuri'un da marubuta suka kada na iya zama tafarkinsa daya tilo na samun nasara, ko kuma hakika kowanne irin nunawa ne.
Mai shigar da karar ya sanar da aniyarsa ta sake tsayawa takara ne a ranar 4 ga watan Yuli, da ya wuce wa'adin da aka diba na shigar da kara a matsayin dan takara a akalla jihohi shida.
Duk da haka, West ya matsa gaba kuma ya shigar da takardun da suka dace tare da Hukumar Zaɓe ta Tarayya (FEC), kuma ya sami nasarar samun sunansa a kan ƙuri'u a Oklahoma.
Tun daga wannan lokacin ya ke gudanar da gangamin yakin neman zabe daya tilo, a lokacin da ya ke jawabi ga taron jama'a daki-daki a cikin falmaran bulletproof, ya na mai gabatar da jawabinsa ba tare da makirufo ko talbijin ba.
West ya fito karara ya ki jinin zubar da ciki, yana kuka yayin da ya ke gabatar da wani sako na addinin Kirista mai cike da rudani yana mai cewa hakan zai sa kafofin yada labarai "su fada maka cewa ni mahaukaci ne"
Har ila yau a shafin rt.com Kanye West ya yi ikirarin cewa ya yi kokarin kashe Kim Kardashian, yana mai zarginta da kuma uwargida "Kris Jong Un" na WHITE SUPREMACY
Hakan gaskiya ne, kuma an bayyana gangamin da kasashen yamma suka yi a shafukan labarai da kuma maganganun gulma a matsayin wani bugu na ban mamaki, ko shaidar rashin lafiyar kwakwalwa, ko duka biyun.
Sai dai kuma, wata kuri'ar jin ra'ayin jama'a da aka yi a baya-bayan nan, ta saka West a kashi biyu cikin dari a kasa, wuyansa da kuma wuyansa tare da Jo Jorgensen na Jam'iyyar Libertarian da kuma wani batu da ke gaban Howie Hawkins na Jam'iyyar Green Party.
Duk da cewa ba zai yiwu ya zarce wanda Joe Biden ya yi ada da kashi 48 cikin 100 ba, amma zai iya samun isassun kuri'u daga Biden don ganin Shugaba Donald Trump ya sake darewa karagar mulki a karo na biyu - wani abu da mahukunta a bangarorin biyu ke zargin cewa shirinsa ne.
Koriya ta Arewa ta ayyana dokar ta-baci yayin da aka bayar da rahoton bullar cutar Covid-19
Shugaban kasar Koriya ta Arewa Kim Jong-un ya yi ganawar gaggawa ta siyasa bayan da wani mutum da ake zaton yana dauke da cutar Covid-19 ya dawo daga Koriya ta Kudu bayan ya tsallaka iyaka ba bisa ka'ida ba a wannan watan, in ji kafofin yada labaran kasar a ranar Lahadi.
Idan har aka tabbatar da hakan, zai kasance mutum na farko da hukumomin Koriya ta Arewa suka amince da shi a hukumance, wanda ya zuwa yanzu suka ce kasar ba ta da wani wanda aka tabbatar ya kamu da cutar ta coronavirus.
Kim ya ayyana dokar ta baci, ya kuma kakaba dokar kulle a birnin Kaesong da ke kan iyaka, yana mai kiran ta da "wani mawuyacin hali da za a iya cewa mummunar cutar ta shiga kasar", a cewar kamfanin dillancin labaran kasar KCNA.
A cewar KCNA, mutumin da ya yi kariya ga Koriya ta Kudu shekaru uku da suka wuce ya dawo kan iyakar da aka shinfida wacce ta raba Koriyoyin biyu da alamun da ke nuna cewa Covid-19 ce.
"Wani lamari na gaggawa ya faru a birnin Kaesong inda wani dan gudun hijira da ya je kudu shekaru uku da suka wuce, mutumin da ake zaton ya kamu da kwayar cutar mai karya garkuwar jiki ya dawo ranar 19 ga watan Yuli bayan ya tsallake layin aljannu ba bisa ka'ida ba", in ji KCNA.
KCNA ba ta ambaci takamaimai ko an gwada mutumin ba, amma ta ce "an samu sakamako maras tabbas daga binciken likitoci da dama na asirin gabobin jikin mutumin na sama da kuma jini", wanda hakan ya sa jami'ai suka killace mutumin tare da bincikar duk wanda ya yi mu'amilla da shi.
Koriya ta Arewa ta karbi dubban kayayyakin gwajin cutar Koronabirus daga Rasha da sauran wasu kasashe, kuma ta sanya dokar rufe kan iyakoki mai tsanani.
An killace dubban mutane a asirce, sai dai a baya-bayan nan an sassauta dokar hana fita.
A cikin makonnin da suka gabata ma, Koriya ta Arewa ta zafafa wani gangami na sukar lamirin jami'an tsaro ga Koriya ta Kudu a matsayin "abin kunyar mutum" da kuma kira ga Koriya ta Kudu da ta fatattaki kungiyoyin da ke aikawa da sakonnin farfaganda da taimakon abinci a cikin Koriya ta Arewa.
Kim ya bayar da umarnin a gudanar da bincike a rukunin sojoji da ke kan iyakar inda ake zargin mutumin da tsallakawa don "aiwatar da hukunci mai tsanani da kuma daukar matakan da suka dace".
Paul Pogba ya shiga tsaka mai wuya kan makomarsa bayan da Man Utd ta kai bantanta a gasar zakarun Turai
Dan wasan gaba na kungiyar kwallon kafa ta Manchester United Paul Pogba ya bayar da shawarar cewa zai ci gaba da zama a kungiyar a wannan bazara bayan da kungiyar Red Devils ta rufe wani wuri a cikin kungiyoyi hudu na saman tebur.
Nasarar da Leicester ta samu da ci 2-0 na nufin United ta ƙarƙare a matsayin ta uku, a gaban Frank Lampard na Chelsea.
United tana da maki 14 a kan Leicester a wasa 12 da suka wuce, amma wani gudu na azo a gani da Red Devils ta yi ya kare a cikin 'yan hudun saman teburi.
An sa ran cewa Pogba zai bar kulob din a wannan bazarar bayan da sau biyu yana neman barin kungiyar a shekaru biyu da suka gabata.
Sai dai wannan annoba na nufin kulob-kulob kalilan ne za su kashe kudi sosai a wannan bazara kuma babu wani mai saye da zai iya hada kudin musayar 'yan wasa da kuma albashin da Pogba zai biya domin ya kore shi daga Old Trafford.
Wannan bayyani ya taimakawa Pogba a makonnin da suka gabata yayin da wasanninsa da kuma harshensa na jiki suka inganta.
Shi kuwa dan kasar Faransan ya kore wani sabon ambato da ke nuna cewa zai ci gaba da zama a kungiyar ta hanyar sanya a shafinsa na sada zumunta na Instagram bayan nasarar da kungiyar tasa ta samu da ci 2-0.
Duk da cewa watakila Pogba yana murnar komawar kulob din gasar ne kawai, amma magoya baya da yawa suna fassara hakan da cewa shawara ce mai karfi da ke nuna cewa har yanzu yana nan daram a kulob din yayin da suke fafatawa da mafi kyau a nahiyar Turai.
Pogba yana da shekara guda da zai yi takara a yarjejeniyarsa da ke akwai, duk da cewa kungiyar za ta iya tsawaita hakan nan da wata 12 ma'ana yana da sauran shekaru biyu da zai yi a kungiyar.
United na dab da tsawaita yarjejeniyar Pogba kuma suna son karin haske kan halin da yake ciki kafin kakar wasa mai zuwa.
A nasa bangaren Pogba yana jin dadi a kulob din kuma zuwan Bruno Fernandes ya saye shi.
Dan wasan dan asalin Portugal ya kasance wani sauyi a Old Trafford kuma zuwansa ya baiwa Pogba damar taka leda a wani matsayi mai zurfi a tsakiyar fili, wanda kuma hakan ya inganta yanayinsa.
